### ISSUE TITLE
Always be able to switch between text and visual editor with an empty source

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1004]
When creating a new Geoblock and enter the editor you start with `{}` in the text editor. You can switch to the visual editor, starting with a blank canvas. However, if you want to switch back to the text editor, you can't because there is no output block yet (frontend validation message). This may be something many users are going to run into.

Is there a way to ignore validation as long as the user hasn't changed anything?

**Comment by hoanphungt** [comment]
If the source of the geoblock is empty (`null` or `{}`) then it will pass all the validations.
