### ISSUE TITLE
Add raster_store blocks to the geoblock type definition

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#1015]
According to @arjanverkerk, we are missing two important blocks from the raster-store: `Interpolate` and `GroupTemporal`. The documentation for these blocks can only be found in the raster-store source code.

Note: there are some other blocks in the raster-store but they are for internal use only (e.g. ThreediResult, ThreediGrid ...)

**Comment by lexvand** [comment]
Seems to work as expected, although we need to see how we want to handle these when it comes to documentation.
