### ISSUE TITLE
Some disallowed or unclear blocks in Geoblocks management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1017]
Based on feedback from @caspervdw:

- [x] MemorySource and RasterFileSource are not allowed for use through the API. These are blocks for local use of dask_geomodeling only. They should be excluded from the list of usable blocks.
- [x] The button RasterBlock generates a LizardRasterSource block. It is therefore better to name it RasterSource instead of RasterBlock.

**Comment by lexvand** [comment]
Changes look good.

**Comment by hoanphungt** [comment]
on production
