### ISSUE TITLE
Layer collections field only searches in first 10 API results

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1025]
When opening the management client the layer collections are retrieved on startup. This limited set of 10 items is used in the layer collections field in the raster layer and WMS layer screens, based on client side filtering. Therefore, you cannot select out of all available layer collections.

Either make the layer collections field dynamic and use backend filtering or retrieve all layer collections on startup with paginated requests.

**Comment by hoanphungt** [comment]
@lexvand 
Can I add a raster layer of one organisation to a layer collection of another organisation?

**Comment by lexvand** [comment]
@hoanphungt Yes, you can. For instance as an administrator you should be able to add a public layer of another organisation to a layer collection of your organisation. So I guess, based on the authorisation model, the layer collection should be writable=true for the user that wants to add a layer to it.

**Comment by hoanphungt** [comment]
I made the layer collection field a dynamic field and used backend filter on slug in the raster layer, wms layer and geoblock forms. The layer collections are now also removed from the Redux store as it is not being used anymore.

**Comment by lexvand** [comment]
@hoanphungt I found a backend bug in the authorisation model, which enables non-administrator/-suppliers to add layers to a collection they should not be authorised to write to. Also in the management client this should be prevented by adding the `writable=true` parameter to the layer collections query (like I mentioned in my previous comment). Can you add this for all layer collections fields? I will create a backend issue to solve the authorisation issue.

**Comment by hoanphungt** [comment]
Yes, indeed you are right. I added the `writable=true` parameter to the layer collections query. It should works correctly now.

**Comment by lexvand** [comment]
Works as expected now.
