### ISSUE TITLE
Maintenance items for lizard-management-client

### ISSUE THREAD

**Issue by remcogerlich** [nens/lizard-management-client#1028]
See the Regular maintenance Excel sheet in the Frontend team ( https://nelenschuurmans.sharepoint.com/:x:/s/IT/EZGwogcDfPBLhG7q5_F0zqoBLA1XCWtKgPfLrjEuOlXJXg?e=qz17qV )

Version updates for lizard-management-client (all expected to be trivial):
- Update react-scripts to 4.0.3
- Update React to 17.0.2
- Update Typescript to 4.1.2

Improve the code so that there are no "any" identifiers left, as these disable Typescript's checks: substantial amount of work, as there are more than 700 occurences of the word 'any'. 2 days work.

Improve the code to refactor javascript components to typescript components (quite many). 1-2 days work.

Solve the problem where npm cannot install this repositories' dependencies, and as a result cannot run npm audit --> Needs to run `npm i --package-lock-only` first to run `npm audit`. Otherwise, can also use `yarn audit` directly.

**Comment by hoanphungt** [comment]
@remcogerlich 
Apart from the "any" issue, there are also certain components that are written in js/jsx instead of ts/tsx. For example: index.js, action.js, reducers.js and some other components. Do you expect to refactor them into .ts/tsx within this ticket as well? I think action.js and reducers.js can take quite some efforts to rewrite them into .ts.

**Comment by hoanphungt** [comment]
Continue with the maintenance items for the lizard-management-client part 2. Part 1 (biggest part) has been reviewed by Remco and merged to master.

**Comment by hoanphungt** [comment]
Run `yarn audit` gives 6 critical issues. 4 of them can be solved by upgrading storybook to v6. Only 2 critical issues left.

**Comment by hoanphungt** [comment]
Update estimate to 4 due to changes as described in the description.

**Comment by hoanphungt** [comment]
Tested on Staging, everything works well.

Not directly a results of this maintenance items but some bugs were found during the testing for this ticket (which already existed before):

- https://github.com/nens/lizard-management-client/issues/1046
- https://github.com/nens/lizard-management-client/issues/1047
