### ISSUE TITLE
Add date column to scenario table

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#1029]
Requested by @Patrick-Nijman:

We should be able to sort the scenarios by date (either by `date_created` or `date_modified`). 

The default view of the scenario list will initially be sorted by `date_created` or `date_modified`. Currently, `date_modified` is not available in the scenario API yet but if it is available, Patrick prefers to use this field over the `created` field to sort the scenarios.

------
**LINKED TICKET:**

Linked ticket to add `modified` field in scenario API: https://github.com/nens/lizard-nxt/issues/5385

**Comment by hoanphungt** [comment]
@lexvand @Patrick-Nijman 
Hi Lex and Patrick,

I made this ticket based on Patrick's request. Could you guys determine the priority of this ticket?

**Comment by lexvand** [comment]
The `last_modified` field is in case of scenario's indeed more valuable than `created` as you can easily find operational models then as well. Is in line with nens/lizard-nxt#5148. 

@RemieJanssen Candidate for last minute inclusion in the still open PR?

**Comment by RemieJanssen** [comment]
> @RemieJanssen Candidate for last minute inclusion in the still open PR?

Yes, will do

**Comment by hoanphungt** [comment]
Done, deployed to production
