### ISSUE TITLE
Improve work flow for geoblock management (open in viewer button)

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#1037]
The open in viewer is placed in the geoblock build modal. This is not very good for the work flow as it makes users to think that the geoblock has already been updated after the editting in the lizard viewer. This is not true because the changes has not been saved to the database yet. Only when the geoblock form is saved and you are back to the geoblock table then the changes can be visualized in the Lizard viewer. 

The proposed solution by Joep/Lex is that to place the Open in viewer button under the Actions button of the geoblock table.

**Comment by lexvand** [comment]
Tested on staging: It works better this way. It makes room for an actual preview feature we may want to add later on.

**Comment by hoanphungt** [comment]
Deployed to production. 

Question for @lexvand : should this ticket be in the "Awaiting for production release" pipeline after you tested it on staging instead of being closed? I didn't keep track of it until today when I checked the release versions in GitHub.
