### ISSUE TITLE
POST/PATCH raster layer when saving GeoBlock in editor

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1038]
Currently, you need to save both in the editor and in the form to store the graph you have created/edited in the GeoBlocks management screen. This is quite confusing and may even lead to unsaved work.

We have decided to only enable opening the editor when the required fields in the form have been filled in. Therefore, it is safe to POST or PATCH on saving in the editor.

It may depend on the use case whether it makes most sense to return to the form or the table after saving a graph. The user may or may not want to make changes to the rest of the configuration (e.g. colormap) after making changes. I think it is best to return to the form by default, even though the object no longer needs to be saved there.

Create graph workflow: Open new form -> configure required form fields -> open GeoBlock builder -> build graph -> save -> POST new raster layer to API -> return to form -> [optional] make changes in form -> close or save to return to table

Change graph workflow: Open existing form -> [optional] make changes form -> open GeoBlock builder -> edit graph -> save -> PATCH raster layer in API including  -> return to form -> [optional] make changes in form -> close or save to return to table

**Comment by hoanphungt** [comment]
@lexvand 
I am checking the workflow. IMO, it makes more sense to by default always return to the table after saving either from the form or from the geoblock editor. In that case, the workflow would always be the same for both creating and editing a geoblock:

1. Open new form/existing form => configure form fields => open GeoBlock editor => build/edit graph => save => table

2. Open existing form => configure form fields only => save => table

In this case, the process is simpler and there will only be one time that users have to click on the save button (either in the form or in the geoblock editor).

**Comment by hoanphungt** [comment]
In addition, because the "Open in viewer: button will be in the table so landing back to the table also makes more sense.

**Comment by lexvand** [comment]
Tested on staging: This is a great improvement of the workflow. Works for both new items and changes in existing ones.

**Comment by hoanphungt** [comment]
Deployed to production
