### ISSUE TITLE
Changes in Scenario metadata

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1044]
- [x] Adjust to name changes in attributes
- [x] Make all relevant attributes editable
  - [x] name
  - [x] access_modifier
  - [x] description
  - [x] source
  - [x] project
  - [ ] simulation_start
  - [ ] simulation_end
  - [x] simulation_identiefier
  - [x] model_name
  - [x] model_identifier
  - [x] model_revision
  - [x] extra_metadata
- [x] Add Scenario(s) to Project

See results of: nens/lizard-nxt#5443 and [description](https://github.com/nens/lizard-nxt/issues/5416#issuecomment-1087330846) of backend changes

**Comment by hoanphungt** [comment]
@lexvand I don't see `source` in the api
