### ISSUE TITLE
Add management for Projects (groups of Scenarios)

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1045]
- [x] List Projects per organisation in table
- [x] Create/edit Projects in form
- [x] (optional) Overview of Scenarios in Project: from the three dot icon, select "List of Scenarios" to open the scenarios table for the selected project in a new Tab

See results of: nens/lizard-nxt#5442 and [description](https://github.com/nens/lizard-nxt/issues/5416#issuecomment-1087330846) of backend changes

**Comment by hoanphungt** [comment]
For projects, I am missing the icon for the Project tile. Could you please make an icon for it, @gijs ?

In addition, I grouped Projects and 3Di Scenarios under 1 tile: Scenario (similar to Time series) and plan to use the 3Di scenario icon for this tile. 

How do we want to show overview of scenarios of a project? @lexvand

**Comment by hoanphungt** [comment]
@lexvand 
I created this icon for the Project tile based on the 3Di icon and the monitoring network icon:

![Screenshot from 2022-04-14 13-51-47](https://user-images.githubusercontent.com/43402556/163385160-16179e08-9d32-49d0-990e-6d6d81d3f23a.png)

![Screenshot from 2022-04-14 13-50-25](https://user-images.githubusercontent.com/43402556/163385000-091c168c-9909-4002-b51f-c7349f45fe5e.png)

What do you think?

**Comment by lexvand** [comment]
@hoanphungt
- Icon looks good, for now. We want to make scenarios no longer exclusive for 3Di. That means we do not want to brand it with the 3Di logo anymore. That means we need an alternative for both the Scenarios and the Porjects logo. @gijs 
- The grouping under one tile makes sense. I just think that will break the links to scenario management, e.g. in the catalogue and in the result email ([example](https://nxt3.staging.lizard.net/management/data_management/scenarios/bc157bc3-b607-48ab-b816-fdd777829202)) that a user receives when postprocessing is done. We should adjust it both in our frontends and in the email. Can we make this backwards compatible by forwarding to the right page?
- Overview of Scenarios in a Project: I guess it is best not to make this into a separate feature. We do not want to include a (paginated) list of Scenarios in the Project form. Best would be if we link to the Scenarios table with a filter on the specified Project. Is that doable?

**Comment by hoanphungt** [comment]
- So I keep the icons as they are for now but we might want to change them again in the future.
- I keep the grouping. However, some configurations/adjustments need to be made for the catalgoue and the result email. In the meantime, it's best to keep it backwards compatible.
- Overview of scenarios in project: I think it's a good idea. I investigated a bit on it and it's possible by adding a query parameter to the link to the table. Something like this: `/management/data_management/scenarios/scenarios?project__uuid=c11a5a65-6e0e-4ccf-b3b4-caa0c4d59043`. Then I can use this query parameter to add a filter to the scenario table. I think this is quite a neat solution.
