### ISSUE TITLE
Remove organisation filter from temporal raster selection for raster alarms

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1055]
Currently, administrators can only use configure raster alarms for raster layers within their own organisation. This is an unnecessary limitation, as the authorisation model allows setting an alarm for any temporal raster the user has read rights for, also public objects. It also isn't consistent with timeseries alarms, which do not use an organisation filter.

Feature requested by Joeri and wished before April 25th.

**Comment by lexvand** [comment]
@hoanphungt Can we change this in a separate branch as a quick fix, such that we can release it before the Scenario changes?

**Comment by hoanphungt** [comment]
@lexvand yes, that is not a problem at all. The scenario changes are all in a separate branch and we can roll it out after this fix without any problem.

**Comment by hoanphungt** [comment]
@lexvand deployed to staging. Could you please test it before it can go to production? I'd like it to be on production soon.

**Comment by hoanphungt** [comment]
Deployed to production
