### ISSUE TITLE
A couple of filtering issues for scenarios

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1059]
Some things I missed in earlier tests:
- [x] Page goes blank when entering a single digit in the UUID filter: https://github.com/nens/lizard-management-client/issues/1060
- [x] Username filter uses old specs (should use supplier__username__icontains)
- [x] Default ordering should be inversed (`-last_modified`)

**Comment by lexvand** [comment]
@hoanphungt Ah, I didn't know that. But it is exactly what we want for all tables. It is a good assumption that the objects that are last modified are most relevant to the user. Go ahead with changing it.

**Comment by hoanphungt** [comment]
deployed to both staging and production. Staging worked correctly. Production still needs to wait for the fix by backend to be deployed to production.
