### ISSUE TITLE
Validation on uniqueness of threshold attributes

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#1075]
Configurators of alarms sometimes make a mistake in setting up thresholds for an alarm, using duplicate values or warning_levels, which breaks the alarm trigger mechanism. We've added validation for this in the API. The management client should inform the user properly by passing the error in the snackbar when this happens.

API response in this case is:
`{"status":400,"code":20,"message":"Incomplete request content. #400.20","detail":{"thresholds":["Thresholds must have unique attributes"]}}`

**Comment by lexvand** [comment]
Great! We can release this to production in advance. So whenever it suits you, @hoanphungt.

**Comment by hoanphungt** [comment]
Deployed to production but it has to wait for backend release to work correctly.
