### ISSUE TITLE
[Deadline 7 july 2020] Raster management-client compatible with new raster backend

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#236]
The Raster backend was previously one database object, but from 7 july 2020 onward the production lizard database will consist of 2 different raster objects.
**Goal** is to make the current management client compatible with the new raster backend before 7 july 2020.
Related Question: which other clients might be impacted by this change (for example the catalogue?).

**Short term goal** is also to decide on 2020 June 12 which of the below 3 options we should choose.

The current fields as they are now on the rasterform will be devided over the 2 new database objects as follows:
detail van een raster, velden. oorsprong is aangegeven met L (api/v4/rasters) of S (api/v4/rastersources):
• S + L organisation
• L shared with organisation (shared_with)
• L authorization type (access_modifier)
• S + L name
• L description
• L aggregation type
• L observation type
• L color map
• S + L supplier
• S supplier_code
• S raster series (temporal)
• S raster series interval (interval)

The above described change in the backend is currently already on staging.

This change can high level be accomplished in 3 Options:
**CONCLUSION: Remco and Tom decided on option 2, because of the deadline.**

1). We change nothing or almost nothing on the client and make the backend perform some magic behind the screens to actually manage the 2 objects. This looks now NOT like the preferred solution, because the new rasterforms (according to new graphical design) will also eventually have 2 seperate forms for the 2 different tables. SInce we eventually are going to change it, it is probably a bad idea to implement this 'magic' on the backend.
**2). We change nothing on how the client looks, but let the client manage that different fields are retrieved from and posted to different api endpoints. A problem might be if the api call is done to the 2 different endpoints that one api call might succeed and the other fail causing causing inconsistent state, but we expect the chance to be low and accept this for now. Since we have a deadline this option is probably the preferred one.**
3). We change the management client completely according to the new graphical design which already takes intoo account the different database objects. This would be the preferred approach if we can make it on time. 

Here design for raster tables and navigation tiles:
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/2e403a90-ee28-402b-8643-e6783a54c76f/Data-managment

Design for rasterforms will appear in short term.

**State of the backend:**

https://github.com/nens/lizard-nxt/pull/3562

1. on rasterlayer creation, a rastersource is created automatically (unless is_geoblock=true is in the POST body)
2. on rasterlayer update, the supplier_code is copied automatically into the rastersource (unless is_geoblock=true on the model)
3. on rasterlayer deletion, the rastersource is deleted automatically (if not used by another rasterlayer)

To go for option 2, I'll have to remove these 3 things. There is already a pending PR for number 3. Removing 1 and 2 is trivial. Currently, one could use is_geoblock=true as a workaround to make the mgmt screen.

Then we have the "flush" functionality: remove the raster data while keeping a backup of the original. One could do a series of requests (I think you need 4) or, the backend could implement rastersources/{uuid}/flush. My guess is that we want to keep this functionality, so implementing this API endpoint might be preferred.

**Comment by Derryrover** [comment]
@joeriverheijden 
@caspervdw 
@LirryPinter 
@remcogerlich 

I created the previous ticket under the wrong repository (namely 3di-livesite).
I could not transfer it (because this repo is public but 3di live is private).
I had to recreate this ticket.
excuses

**Comment by LirryPinter** [comment]
@remcogerlich @Derryrover @lexvand @caspervdw @joeriverheijden 

I now made a design for the 'new raster source' form.  For clarity I made a new link with just the design elements, and a mockup page what it should look like. 

https://xd.adobe.com/view/888acd29-5144-40fb-5bef-9d925cdd48f6-febb/


- First design elements are buttons etc, you probably seen it already
- The second design elements page are form fields (that were necessary for raster sources, will fill them later on for the others). This includes an 'anatomy' of a field with rules for margins distances etc.
- The third is the mockup page for the page, complete with an explanation on the side concerning the interaction design and rules.

This is the first time I have done it this way but I really like the structure of working. Let me know what you think!

Additionally, I have started with a list of form fields and their traits:
https://docs.google.com/document/d/1FSWx3TZOBvaoOLb2mj3sjDiH_JMGc-JeThhAZJy8_As

Here I list the fields, which category they belong to and where they are used. I suggest we use this document to check if we are all on one page.

**Comment by caspervdw** [comment]
So it is decided! Let's not look back and proceed with this option.

The current state of the backend is:
 1. on rasterlayer creation, a rastersource is created automatically (unless is_geoblock=true is in the POST body)
 2. on rasterlayer update, the supplier_code is copied automatically into the rastersource (unless is_geoblock=true on the model)
 3. on rasterlayer deletion, the rastersource is deleted automatically (if not used by another rasterlayer)

To go for option 2, I'll have to remove these 3 things. There is already a pending PR for number 3. Removing 1 and 2 is trivial. Currently, one could use is_geoblock=true as a workaround to make the mgmt screen.

Then we have the "flush" functionality: remove the raster data while keeping a backup of the original. One could do a series of requests (I think you need 4) or, the backend could implement rastersources/{uuid}/flush. My guess is that we want to keep this functionality, so implementing this API endpoint might be preferred.

**Comment by LirryPinter** [comment]
@remcogerlich @Derryrover @lexvand @caspervdw @joeriverheijden 

Lastly, this is a document where I justify my choices for the designs:

https://docs.google.com/document/d/1Bcr6j2EMzkWJ_4vJdu3jupk8E9BS-ZrGsRxwCSGhr50/

Feel free to respond or comment and let the discussion flow

**Comment by caspervdw** [comment]
Update: we did a backend staging release. The current state is simplified. Documentation is lagging behind, this can be read from the code at https://github.com/nens/lizard-nxt/pull/3570

*Creation*
Here are examples for a complete POST:
https://github.com/nens/lizard-nxt/blob/82942a925066abcb99ef3397de90b2b81409a858/lizard_nxt/api/v4/tests/test_rasters.py#L501

https://github.com/nens/lizard-nxt/blob/82942a925066abcb99ef3397de90b2b81409a858/lizard_nxt/api/v4/tests/test_rastersources.py#L78

Remark: the "access_modifier" field of a rastersource should be always Private (=default)

*Update*
See Creation. Remark: the fields "temporal" and "interval" cannot be edited after creation.

*Delete*
A rasterlayer can be deleted as previous. Previously, the data was also deleted on deletion of a raster; now you need to delete the rastersource as well. For that:
1. first check if is_geoblock=false in the (to be deleted) raster. Keep track of the raster_sources field.
2. DELETE the raster
3. if is_geoblock=false, also DELETE rasterlayer.raster_sources[0] (=url to the rastersources endpoint)
4. The response is one of three:
   - 204 Gone
   - 412 Precondition failed. The latter means that another rasterlayer is using the source. Ignore the error.
   - 403 Permission Denied. This means that the rastersource was owned by another organisation. Ignore the error.
   - or: raster_sources[0] did not exist. In that case the rastersource is not visible for the current user. Skip deletion of the rastersource.

*Flush data*
Only available for is_geoblock=false and source is not None
1. Unlink the rastersource by PATCHing rasterlayer.source to None
2. Delete the rastersource (ignoring errors as with normal deletion)
3. Create a new rastersource (copy some parameters from the old rastersource)
4. Link the rastersource

*Upload data*
Only available for is_geoblock=false and source is not None. The rest of the API is unchanged.

**Comment by remcogerlich** [comment]
Is the v3 API also changed? Lizard-client would be affected, e.g. animations probably wouldn't work anymore. And don't external customers use the raster API?

On staging I tried to animate the "Regen" layer, but got a 500 error from /api/v3/raster-aggregates/ . Also related?

**Comment by caspervdw** [comment]
We took effort to leave API v3 as is (luckily it is read-only). That also should have been tested by now. That you receive a 500 is not good ;) I'll have a look.

@lexvand Do you know if the raster functions on staging have been tested already?

**Comment by remcogerlich** [comment]
I'm confused on the basic way this should work.

When I create a new raster, I think I should either:

1. Create a new raster source
2. Then create a new raster layer, using the import path and uuid of the created source in the "graph" part of the request, as in that test_raster example.

But that doesn't work as I don't know the import path.

Or

1. Create a new raster layer without source
2. Create a new raster source, adding the layer in "layers".

But that doesn't work as layers is read-only.

How is it supposed to work? It would be nice if there existed a test that created both (without using LizardRasterSource.get_import_path() as the import path as I can't do that on the frontend)

**Comment by remcogerlich** [comment]
Also for flushing the data (currently that was done by only PATCHing source to None) -- if I delete the raster source, doesn't that cause problems with sources that are shared by multiple layers?

**Comment by LirryPinter** [comment]
@remcogerlich @caspervdw 

Casper gave an explanation for this earlier.. When a user deletes/flushes a source the user should get an warning that this will cause some raster layers to be 'empty'. Thus this is the responsibility of the user.

**Comment by caspervdw** [comment]
> Also for flushing the data (currently that was done by only PATCHing source to None) -- if I delete the raster source, doesn't that cause problems with sources that are shared by multiple layers?

For the new screens we want a nice warning mechanism, but for the current one you can just try to delete the source and do nothing if it fails. Because it won't work if the source is still in use. Then you get the 412 Precondition Failed (see above). To skip that warning, you should add force=true to the URL (that is for the new screens)

**Comment by remcogerlich** [comment]
https://github.com/nens/lizard-management-client/pull/238

I implemented the new logic as described by Casper. Only editing is still a bit unclear: Several fields exist on both the raster and the raster source (name, description, organisation, supplier, supplier_code). I opted to only change them in the raster, not the raster source, because there may be multiple rasters using the same source. But that means there is no way to edit the values on the raster source.

As this is probably somewhat temporary until we go to the new form design, I thought it didn't matter that much either way, but if some of those fields also need to change on the source then that can be added easily.

**Comment by caspervdw** [comment]
Great! One question: did you develop while testing against staging or master?

**Comment by remcogerlich** [comment]
Tested against staging but look at the unit tests in my locally checked out master branch.

Part of it (flush and deleting the sources) isn't tested yet as the URLs of those from raster_sources are absolute and don't work with the proxy setup we use in development, but I'll test that as soon as I can make a staging release.

**Comment by caspervdw** [comment]
Good to know. I'll have a look at the PR to check for inconsistencies with the backend

**Comment by caspervdw** [comment]
> upload/cloud icon of newly made raster shows that it is not allowed to update because derived raster. This is probably a bug

See my remark in the PR, the frontend logic needs to be adjusted

> Updating (change name) the newly made raster shows 500 http {"status":500,"code":13,"message":"Technical error. #500.13","detail":"can't set attribute"} probably backend bug, need to be investigated.

Backend bug, solution is currently under review.

> flushing data receives 404 {"status":404,"code":10,"message":"Resource not found. #404.10","detail":"No RasterSource matches the given query."} Bug needs to be investigated

No idea what this is

**Comment by Derryrover** [comment]
@caspervdw 
> > flushing data receives 404 {"status":404,"code":10,"message":"Resource not found. #404.10","detail":"No RasterSource matches the given query."} Bug needs to be investigated
> 
> No idea what this is

It happens when we do the following api fall for flushing the raster:
https://nxt3.staging.lizard.net/api/v4/rasters/688b0d88-cef5-4ffd-8790-8a687e248489/
payload/body: {"source":null}

**Comment by caspervdw** [comment]
> @caspervdw
> 
> > > flushing data receives 404 {"status":404,"code":10,"message":"Resource not found. #404.10","detail":"No RasterSource matches the given query."} Bug needs to be investigated
> > 
> > 
> > No idea what this is
> 
> It happens when we do the following api fall for flushing the raster:
> https://nxt3.staging.lizard.net/api/v4/rasters/688b0d88-cef5-4ffd-8790-8a687e248489/
> payload/body: {"source":null}

Either a wrong UUID or something is messed up in the credentials.

**Comment by remcogerlich** [comment]
Wait, the code to edit rasters PATCHes /api/v4/rasters/uuid:$uuid/ , this PATCHes /api/v4/rasters/$uuid/ . 

I thought the `uuid:` was strange but it was the existing code so I copied it and forgot about it. Is that necessary? For which requests?

**Comment by caspervdw** [comment]
I have never seen this `uuid:` prefix. It should not end up in the url. Or is it some casting syntax of typescript?

**Comment by remcogerlich** [comment]
I had never seen it either, but I just tested with the version that is currently on staging, it does send a PATCH to https://nxt3.staging.lizard.net/api/v4/rasters/uuid:b61b3821-5ea6-49b5-8105-50f894a32edb/ and it did work.

**Comment by Derryrover** [comment]
@remcogerlich 
@caspervdw 

Hi I did some tests with the raster management screens on production and most looks good.
I did find 2 problems though. I could not reproduce them on staging.

- When making new raster or updating existing supplier_code is not saved. (It is send to api)
- In raster list the cloud icon is greyed out even if data is uploaded or data uploading is available.

kr Tom

**Comment by caspervdw** [comment]
I can't reproduce both issues:

 - made new raster, that raster gets a greyed out upload icon, after an upload it becomes green
 - change of supplier_code has effect (supplier_code is changed on the rastersource); only thing is that supplier_code gets PATCHed to both /rasters and /rastersources, while only the latter is needed.

It is possible that these issues were caused by an incomplete data migration. 
Maybe you tested before the data migration was complete.

**Comment by caspervdw** [comment]
Flush, however, does not work, because of a client error::

 1. On the POST to rastersources, the request body contains a nested entry (organisation). This should be the uuid only.

  now: ```"organisation":{"url":"https://demo.lizard.net/api/v4/organisations/70b0c750-d234-43b9-bb75-3454b05c2b0d/","uuid":"70b0c750-d234-43b9-bb75-3454b05c2b0d","name":"Geoblocks Masterclass"}```
  should be: ```"organisation": "70b0c750-d234-43b9-bb75-3454b05c2b0d"```

**Comment by Derryrover** [comment]
@remcogerlich 
@caspervdw 

-Yes the problem with supplier code is fixed now. -> no action required

-There is still a potential problem with the cloud icon in rasterlist though: A newly made raster without rasterdata shows that "it is unable to upload data for derived rasters". Also after I flush another raster that does have data this 'unable to upload for derived' icon is also shown. -> need investigation, I think this is not desired behaviour

-Yes, like you observed Casper, the flushing does give 500 network errors. -> probably needs the fix Casper proposes 1 comment above.

Remco do you have time to look at these problems? 
I think these are quite moderate to high prio problems, but maybe you can align with Joeri?
Let me know if you need help.

kr Tom

**Comment by remcogerlich** [comment]
I will look at them.

**Comment by lisannewapstra** [comment]
@remcogerlich  have you looked at it already? Can you also please take a look at https://github.com/nens/lizard-nxt/issues/3707
