### ISSUE TITLE
Design of components for raster management [CONTAINS LINKS]

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#237]
The design is going to include:

- Overall design for user flow of making a raster
https://xd.adobe.com/view/80bc79b4-fbd2-4d42-9d7f-00b84d2e89c3-d5ef/

- Design for raster sources:
https://xd.adobe.com/view/7db69dd3-8f90-43f9-8cd5-c9f850d69d80-28e5/

- Design for the raster layers:
https://xd.adobe.com/view/eda684bb-be65-4b2b-879f-fc6b96240847-b8f5/

- (separate, but for the layers) Design for colormap modal
https://xd.adobe.com/view/70294934-13dc-48fb-8fb1-f02a2109ce9e-257a/

**Related tickets:**
ticket-froms: https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/240
ticket-pagination: https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/239

**Comment by Derryrover** [comment]
Hi Lirry,

I am checking out your new design. Looks good !
I do have some questions about existing functionality like on the current rasterform here:
https://nxt3.staging.lizard.net/management/#/data_management/rasters/f85c153f-c303-444b-8635-0daf017c8424
Namely the following fields are missing in the new design:
- shared with organisations
- authorisation type
- observation type
- etcetera

Some of these fields need to be on the rasterlayer form. -> Is there a rasterlayer design? How does the flow look if the user creates a new raster (source+ layer+data)? 
Some of the missing fields are maybe not interesting for all users. -> Still we need to support these usecases for customers that do use them.

We can talk about this tomorrow in our meeting.

kr Tom

**Comment by LirryPinter** [comment]
We re-evaluted the the flow of having raster sources and layers. We came to a few conclusions:
-	The usecase for now is the same as in the old management screen, users want to add a raster (which includes a source and a layer)
-	Making a geoblock (which will include multiple layers and sources) is implemented in a later stage, so for now we won’t account for it in the design.
-	We still need to make two management screens (sources and layers) , but to make a new raster we need to make sure they can do it in one ‘flow’.
So the plan is:
-	The user fills in the raster (source) form, when they completed it and uploaded the data, a modal pops up asking the user if they want to ‘publish’ the raster. 
-	This modal sends them directly to a ‘new raster layer’ form, with information pre-filled from the raster source.
-	The fields: source, organization, access modifier and temporal are all filled in according the raster source.
-	The description will start with: This layer is based on [SOURCE NAME].
-	This flow is one-way, that means people can be send from the source to a layer, but no the other way around. 
-	People can still make layers, but then they have to choose from existing sources.

**Comment by Derryrover** [comment]
>     * The user fills in the raster (source) form, when they completed it and uploaded the data, a modal pops up asking the user if they want to ‘publish’ the raster.

@LirryPinter 
@joeriverheijden 
@caspervdw 

Hi Lirry, Joeri and Casper,

Is it possible omit this modal and automatically generate the rasterlayer at all times (and redirect to it)?
If I remember correct then some users were only allowed to make sources and not layer. Is this a hard / strict requirement?
I think it would be good that if a user makes a raster source that a default layer is always created automatically.

This is a often encountered pattern. For example when you open a bank account a pinpas is automatically added. Or when you rent a car the first driver is also assumed. 

kr Tom

**Comment by LirryPinter** [comment]
@joeriverheijden @caspervdw @Derryrover 

Sounds fine by me ( to automatically create a layer) , but the modal still needs to be there to notify the user that they will navigate somewhere else. To suddenly switch management interface is confusing, and a small heads up will help a lot with that. I can change the text in the modal so that the user knows where he or she is going.

**Comment by LirryPinter** [comment]
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/36cf110a-d52f-46d4-a873-9633db16af9b)

**Comment by LirryPinter** [comment]
@hoanphungt @Derryrover @caspervdw @lexvand 

After talking to Casper and Lex, i found out that colormaps are now in the backend either chosen from a dropdown (exisiting) or made custom for that rasterlayer. This means minor changes in the design for the raster layers.

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,
I am looking for the image on the left side of table for raster layers.
Do not see it along assets here:
https://xd.adobe.com/view/eda684bb-be65-4b2b-879f-fc6b96240847-b8f5/screen/aef92ae2-84ab-4686-81ed-23683007ba69/specs/
Thanks in advance!
kr Tom

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,
I am looking for the backbutton icon above the explaination menu.
I am changing the current back character to the icon like in the design as part of this ticket:
https://github.com/nens/lizard-management-client/issues/487

Could you help me export the icon?
kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

I am free today, but I put the back button in the stylesheet of the raster sources.
https://xd.adobe.com/view/7db69dd3-8f90-43f9-8cd5-c9f850d69d80-28e5/
This one.

Good luck!

**Comment by LirryPinter** [comment]
@hoanphungt 
@Derryrover 

The design for the userflow is ready (see the ticket description)
Steps to take (WITHOUT ARROWS TOM :) )
1. Click on 'new source'
2. (Pretend to fill in some stuff) Click the browse button in the drop data box
3. (you will see some mockup files that were added) Now click save
4. (you will see the notification of a starting upload, the upload queue has a badge to indicate there is something going on) 
Click on 'continue' to go to the new raster layer screen
5. (you will see that this layer is based on the previously made source in the description and source fields)
Click on upload queue in the header to open de queue. 
6. Click on X to remove it again
7. Click on save
8. (you will see a notification of a newly made raster and are directed to the layer list)
