### ISSUE TITLE
New design for pagination bar, to develop as separate component

### ISSUE THREAD

**Issue by remcogerlich** [nens/lizard-management-client#239]
Design in https://xd.adobe.com/view/0d95eb0c-fa72-41c5-aac6-4767746f09d1-58c6/

As first step for #237, this component will be made to show how component-based design can work.

Will create a new library with this component in it, demo-able in Storybook, to be used in the management-client.

**Related tickets:**
ticket-froms: https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/240
ticket-design: https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/237

**Comment by remcogerlich** [comment]
https://medium.com/swlh/develop-and-publish-a-react-component-library-using-create-react-app-typescript-8f73bb66335b
@Derryrover

**Comment by lexvand** [comment]
@Derryrover Can this issue be closed? I see you made an issue for making the pagination bar.

**Comment by Derryrover** [comment]
Closed as duplicate:
Proceed here:
https://github.com/nens/lizard-management-client/issues/481
