### ISSUE TITLE
Find right technology management forms

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#240]
For the new management screens there will be a new design.
https://nelen-schuurmans.atlassian.net/browse/FRNT-932
There will be quite a lot of work implementing the new designs and making new forms.
Forms is one of the biggest amount of work. Which technology should we use?

Make a list of possible technologies to use for the form:
- https://react-hook-form.com/ (idea Hoan)
- Use usereducer + useEffect as described here:
https://medium.com/javascript-in-plain-english/react-controlled-forms-with-hooks-538762aab935
https://medium.com/@ReactEurope/which-react-form-library-should-you-use-in-your-app-in-2020-469894c687d
- Use another method described here: https://medium.com/@ReactEurope/which-react-form-library-should-you-use-in-your-app-in-2020-469894c687d
- Let form defenitions be generated from swagger (idea Remco)
- Let form defenitions be generated from a form and field table in the database (idea Tom)

Technologies can be combined.

**Related tickets:**
ticket-pagination: https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/239
ticket-design: https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/237
Decide/ test which technologies to use.

**Related ticket 3di**
In these tickets for 3di I (Tom) did also some research concerning the froms:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/threedi-live-site/647undefined
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/threedi-live-site/572undefined
My conclusion:
- prefer standard form functionality of HTML over libraries
- prefer styling over :invalid or :disabled selectors over custom classes
- use standard validity message of browser over setting own error messages
The 3di livesite windmenu offers a good example, but some additions can also be found in the right sidemenu

**Comment by hoanphungt** [comment]
Some references for building forms using react custom hooks and reusable components:

https://www.codebeast.dev/react-forms-then-and-now/ (build useForm custom hook)
https://www.codementor.io/@blizzerand/building-forms-using-react-everything-you-need-to-know-iz3eyoq4y (make form container and reusable components)

Conclusion:

- Use standard HTML form to make form
- Use React Hooks (to build custom hooks) to manage form logics and validations and to reuse it for different forms --> build custom `useForm` hook
- Make reusable components for form fields --> build new field components: `TextInput`, `TextArea`, `Select`, `Checkbox`, `Button` ...
- Styling using built in attributes of form inputs and their selectors (i.e. :disabled, readonly, :invalid)

**Comment by Derryrover** [comment]
For the forms using standard html css javascript api's is a very good option.
It is a bit a contrived api, but has the advantage that 
- it will not change with every yearly framework change 
- does not require styling of error messages of invalid fields
- allows css selectors with pseudo selectors for invalid fields and buttons. This makes the css more semantic and requires fewer classes.

Technical details:
1)
When clicking the button the onclick should have a check if the form is valid
The function checkValidity() will return false is any field in the form is invalid and hass as side effect that it will automatically display browser errors in these fields:

<button
                // this can also work if type != submit (for buttons in the form that do not submit the form, but for example toggle visibility)
                type="submit"
                name="submit"
                onClick={e=>{
                  const target = e.target as HTMLButtonElement;
                  if (target.form && target.form.checkValidity && target.form.checkValidity() ) {
                      // do click submit logic here
                  }
2) The whole form including fields and buttons should be inside form and fieldset tags. The fieldset tag is usefull to disable parts of or the whole form. preventDefault is needed to prevent reloading the page on submit buttons:
<form
          onSubmit={e=>{e.preventDefault();}}
        >
        <fieldset disabled={disableWholeForm}>
// all form components. Fields and buttons
</fieldset>
</form>

3) Fields in react need to be using a ref. On each render cycle the validity of the fields needs to be set based on the input.
const NumberInput: React.FC<Props> = (props) => {
  const myInput = useRef<HTMLInputElement>(null);

 if (input is valid)
      myInput.current.setCustomValidity('')
    } else{
      myInput.current.setCustomValidity("reason invalid string")
    }
   
      <input
        ref={myInput}

If all these steps are followed then it should work. This is how it is done for the 3di livesite

**Comment by Derryrover** [comment]
@hoanphungt 
Hi Hoan,
See above how I think we should try to display and style invalidate form fields.
kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Nice, thanks for posting it here. I will take a look and try to implement them.

**Comment by hoanphungt** [comment]
@lexvand 

In this PR: https://github.com/nens/lizard-management-client/pull/489, I attempted to make reusable form logics in a custom hook called `useForm` and reusable fields as React components. Made a demo for @remcogerlich and @Derryrover  and received positive feedbacks about it.

Summary of the new form:

> **Overview:**
> - Form is made by fields which are small reusable React components. These components are stateless and only receive “props” from the form.
> - All logics and event handlers of the form are handled by a custom hook called “useForm” (i.e. handleChange, handleSubmit, clearInput, handleReset …).
> - Form validation is done by form’s built-in function “setCustomValidity()” and by validators defined in “validators.ts”.
> 
> **To create a new form:**
> - Use “useForm” hook by providing it “initial values” and “onSubmit()” parameters. Tell the form what to do when submitted in the “onSubmit()” function.
> - Make up fields by using existed “field” components (i.e. TextInput, TextArea, IntegerInput, CheckBox, Dropdown, Select, DurationField) or create a new component if necessary.
> - Provide validation for each field in the “validated” parameter by reuse validator functions in validator.ts or create a new validator.

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

I had another look at the form hook you made and i think it looks like a great solution!
I think we can use it.

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Thanks for your review!
