### ISSUE TITLE
New Management client 2020

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#241]
Main Epic for the new management client design and features.
All new tickets regarded to the management client should be made part of this epic.
The high level enhancements:

    Add management for time series

    Add management for labels

    New style based on lizard.net

    Consistency of all the screens

    Improved form 'new'  objects

Design:
https://xd.adobe.com/view/888acd29-5144-40fb-5bef-9d925cdd48f6-febb/

(OLD DESIGN) https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/

Discussion and explanation files:

(for form fields)
https://docs.google.com/document/d/1Bcr6j2EMzkWJ_4vJdu3jupk8E9BS-ZrGsRxwCSGhr50/edit?usp=sharing

(for list views)
https://docs.google.com/document/d/1zWPsSdD9j533V6vsf5RYa5XBtaYSAzPATt_IjINz57Q/edit?usp=sharing

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

I somehow lost the links to the google docs and other relevant docs.
Could you help me by adding them to the description of this ticket?

kr Tom

**Comment by LirryPinter** [comment]
Will do!

**Comment by Derryrover** [comment]
@LirryPinter 
@joeriverheijden 
@lexvand 

Hi all,

A look and feel redesign for the management client was done previously in this ticket:
https://nelen-schuurmans.atlassian.net/browse/FRNT-455
leading to this pr:
https://github.com/nens/lizard-management-client/pull/209/files

As you can see quite a lot files were touched and I can re-assure that it took longer then the estimated 2 points (understandable, given how much needed to be changed).

The current way styling is set up we can not easily change styling very fast.
Will this be the last time we will make maior styling changes?
Otherwise we might consider refactoring some css as part of restyling it.

kr Tom

**Comment by Derryrover** [comment]
![new_raster.svg](https://images.zenhubusercontent.com/5ede648087ac51301b8149ff/85a79c81-ecdf-4cbe-9121-97c69c861730)

Created a wirefram about how a flow could look like if we created the store upfront gathering all other data from the user.

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,
Here the feedback points from our last meeting:

+ User no longer has to step through whole form
+ Similar fields are grouped together
+ Styling consistent through app
+ Unneeded footer is removed
+ There is a strategy for the user to keep track of uploaded raster .tiff files after she leaves the raster screen. Namely a queue in the header.
+ Creating and updating the raster is greatly simplified
0 The flow for creating a new raster might still take more effort then it needs
0 Uploading .tiff file data gives not a lot of feedback. For example we could attempt to show the uploaded tiff on the map and we could show how the asynchronous task is proceeding. Although a queue is now in the design, we have not thought out the specifics of the queue and no also not the technical implementation of storing that data.
0 Fields that cannot be changed anymore later are not marked clearly as such and are not in a distinctive part of the flow
- The relationship between raster sources and raster layers is not very clear from the forms and lists only

kr Tom
