### ISSUE TITLE
Management screens for Geoblocks 

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#392]
<ul class="alternate" type="square">
	<li>Vanuit use stories een management scherm ontwerpen</li>
	<li>In kaart brengen welke eisen er aan de API zijn</li>
</ul>

<i>[FRNT-24] created by casper.vanderwel</i>

**Comment by LirryPinter** [comment]
@lexvand 

I discussed a solution with @caspervdw and going to propose it to joeri.
