### ISSUE TITLE
Use transifex for react translations with react-intl

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#398]
<p>Voor de managementschermen moeten we bij het vertalen nu de .json file updaten.<br/>
Dit is technisch en geen handig werk voor een vertaler.<br/>
We kunnen daarom ook proberen transifex te gebruiken zoals we ook doen voor lizard client.</p>

<p>Deze library zou een optie kunnen zijn<br/>
<a href="https://www.npmjs.com/package/reactifex" class="external-link" rel="nofollow noreferrer">https://www.npmjs.com/package/reactifex</a></p>
<i>[FRNT-106] created by tom.deboer</i>

**Comment by lexvand** [comment]
@Derryrover Is this relevant for #496? Or can this issue be closed?

**Comment by hoanphungt** [comment]
Close this issue as translation will be investigated separately in the new frontend monorepo.
