### ISSUE TITLE
Confirm window vs Modal

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#401]
<p>Momenteel worden er in de lizard management schermen op meerdere plekken confirm windows (popupjes) gebruikt, waar op die plek ook modals gebruikt kunnen worden (wordt nu nog maar op een enkele plek gebruikt).</p>

<p>Voordelen om (meer) modals te gebruiken:</p>
<ul>
	<li>Tekst wordr beter vertaalbaar</li>
	<li>Meer consistentie in de code</li>
</ul>

<p>Bij een volgende refactor slag zou dit misschien meegenomen kunnen worden.</p>
<i>[FRNT-51] created by madeleine.vanwinkel</i>

**Comment by LirryPinter** [comment]
Het design van de notifications ligt al klaar.

De volgende lijst lijkt me goed/minimaal:

- Aanmaken van een nieuw element
- Verwijderen van een nieuw element
- Aanpassen van een element
- Errors

**Comment by LirryPinter** [comment]
Ook de modals zitten inmiddels in de component library!
