### ISSUE TITLE
Refactor AppIcons into AppTiles

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#413]
<p>The app tiles are named AppIcons in most of the code.<br/>
To make the code more consistent and comprehensible, we should probably refactor the AppIcons into AppTiles (except for the actual AppIcon of the Lizard icon in the header).</p>
<i>[FRNT-534] created by madeleine.vanwinkel</i>

**Comment by lexvand** [comment]
@hoanphungt Can you determine whether this issue is still relevant? If not, please close it.

**Comment by hoanphungt** [comment]
it's not the case anymore, so I will close this issue.
