### ISSUE TITLE
Fix UUID with or without "-" in frontend code.

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#415]
<p>For the  management client we have code conversions from UUID with and without dashes all over the place.<br/>
We should either:</p>
<ul class="alternate" type="square">
	<li>make sure this conversion is no longer needed by verifying it in the backend OR factor this code out to a seperate function.</li>
</ul>

<p>Previous attempts to do this have always let to bugs in production and reverting this so BE AWARE</p>
<i>[FRNT-555] created by tom.deboer</i>

**Comment by lexvand** [comment]
Solved in backend

**Comment by Derryrover** [comment]
We still need to fix this in the frontend

**Comment by lexvand** [comment]
@hoanphungt Could you check if any of these conversions are still in place and whether they can be removed?

**Comment by hoanphungt** [comment]
Done in this commit: https://github.com/nens/lizard-management-client/commit/8e9b26b0deeb4782b731dab4c613e77b308a5325

@lexvand I checked the code. Currently, only API v4 is used to fetch organisations so they all have dashes in the UUID. So removed the piece of code to convert UUID with dashes to UUID without dashes and tested it on both staging and production. Nothing is broken so far. Will deploy it to staging soon.
