### ISSUE TITLE
Refactor empty tables

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#416]
<p>The code for showing no content in a table when no data is visible for the user differs for the different management pages<br/>
(scenarios, rasters, wms layers, alarm notifications, alarm recipients, alarm contact and alarm templates)</p>

<p>The css is in the /src/data_management/scenarios/Scenarios.css file and should also be put somewhere else.</p>
<i>[FRNT-570] created by madeleine.vanwinkel</i>

**Comment by lexvand** [comment]
@Derryrover I guess this is part of the new design.

**Comment by Derryrover** [comment]
yes can be closed
