### ISSUE TITLE
Get rid of message "Your internet connection seems to be online"

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#422]
This again happens in the new client. Don't know whether we fixed it earlier or closed the issue for another reason.

**Comment by hoanphungt** [comment]
merged to feature branch for new management client without review

**Comment by lexvand** [comment]
Not sure how it is triggered, but haven't seen it since.

**Comment by hoanphungt** [comment]
I can test it by turning off wifi to disconnect internet connection and turn it on again. Should be fixed.
