### ISSUE TITLE
Revert removal of "include 3di results" option in raster management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#431]
[This PR](https://github.com/nens/lizard-management-client/pull/234/) turns out to be blocking work for some of our customers. It was part of a larger update issue that was put on hold. We didn't think this through very well.

Pay attention to the refactoring work that was done in the mean time.

**Comment by hoanphungt** [comment]
@lexvand 
Hi Lex,

I reverted it back and deployed it to staging. Remco reviewed it. It seems working fine. Could you test it more on staging before I release it to production?

**Comment by lexvand** [comment]
@hoanphungt 
Great, it works. You can release to production. And once again apologies for the inconvenience.

**Comment by hoanphungt** [comment]
@lexvand 
No problem! I just released it to production.

**Comment by Derryrover** [comment]
@joeriverheijden 
@LirryPinter 

Hi Joeri,

The new design of the management client as linked in this ticket:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/241undefined
does again not mention the "include 3di results" link.

Is it this time gone for real?
Is it correct that 3di results will get their own screen for 3di results?
Will this "3di results screen" be finished on time? (before the raster management screen refactor is finished?)

kr Tom

**Comment by lexvand** [comment]
No, we need to keep it there as long as we do not have another management screen specifically for rasters that belong to scenarios. Admins mainly want to apply different colormaps to these layers, I believe.
