### ISSUE TITLE
Data management -> 3di scenarios List

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#439]
Design approved by HHNK:

https://xd.adobe.com/view/c69b4792-e778-401c-982d-5c57caedf761-93c8/

**Comment by Derryrover** [comment]
Done:
- delete raw data bulk and single
- set columns: size 

Todo:
- make delete and delete raw modal

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Do you have time to review this one?
https://github.com/nens/lizard-management-client/pull/561

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Code looks good! Only one small thing I noticed that the checkmark in the checkbox is not always positioned in the center of the box.

Kr, Hoan
