### ISSUE TITLE
Geoblocks List

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#440]
design: https://xd.adobe.com/view/d2ef027c-c01f-45e7-9bac-c871f4bcdbf4-87bc/

To Do:

- [x] Show list of geoblocks in the table (by using `is_geoblock` filter in the raster endpoint) --> blocked by https://github.com/nens/lizard-nxt/issues/5227
- [x] Decide which columns to show in the table --> name, user, assesibility
- [x] Decide if New Button is needed
- [x] Decide which actions are available in the three dots and in the form --> Delete
- [x] Make the geoblock form as in design
- [x] Decide which field to show / to edit for a geoblock
- [x] Create the button to open the build modal from the form
- [x] Make a simple build modal to edit the JSON data
- [x] Investigate which library to use to view / edit JSON data --> created a ticket: https://github.com/nens/lizard-management-client/issues/943
- [x] Investigate rete.js library to visualize the JSON data

**Comment by lexvand** [comment]
After fixing the exclusion of scenario layers it works as currently expected.
