### ISSUE TITLE
Geoblocks Editor

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#441]
Updated design: https://xd.adobe.com/view/d2ef027c-c01f-45e7-9bac-c871f4bcdbf4-87bc/
--------------------
Editor view:
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/215c3244-2bfe-415f-80f6-3797c7cd4561

Code view:
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/b47766af-ece7-4a2c-abc4-3b7d8cb12177

Result view:
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/49bb90b8-4368-4a4f-b701-c08234fee98b

**Comment by joeriverheijden** [comment]
@LirryPinter can you please update and edit this issue with the latest designs of the GeoBlocks editor? 

@lexvand

**Comment by hoanphungt** [comment]
This is tentative estimate for the geoblock editor.
