### ISSUE TITLE
Alarm management contact - List

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#442]
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/9b170ae7-8b0c-42c5-8ccc-ef8dd9b8c39c

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review: https://github.com/nens/lizard-management-client/pull/668/?

I added the search toggle dropdown to handle different filter options.

Also, the contact only contains `id` not `uuid` so I have to make some tweaks here to make the `TableStateContainer` checkbox also works with `id`.

Kr, Hoan

**Comment by Derryrover** [comment]
Hi Hoan,
Looks good!
Ready to merge
kr Tom
