### ISSUE TITLE
alarm management groups - form

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#447]
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/0ff9ec58-482f-40d8-869d-950bd76393c6

**Comment by hoanphungt** [comment]
@lexvand @LirryPinter 
Hi Lex,

The current group management page includes quite a hidden feature here:

![Screenshot from 2021-02-18 14-15-49](https://user-images.githubusercontent.com/43402556/108362775-71321a80-71f4-11eb-9133-c757b289aaa8.png)

So when you click on group settings and choose send message, it gives you the option to send message directly to the group contacts. We don't have this in the new design for now but it can be included in the "Action" button for the form. However, could you check if we still want to support this feature in the new group form and if yes, whether this feature is still supported by backend in API v4 (I am currently switching all contacts, groups and templates pages to use API v4).
