### ISSUE TITLE
raster - list

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#452]
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/3a9c2858-755b-4371-afcf-1e132f287885

BEWARE: As mentioned here:
https://docs.google.com/document/d/1zWPsSdD9j533V6vsf5RYa5XBtaYSAzPATt_IjINz57Q/edit#heading=h.acsw0isy0nj
but also in other communication channels we now have raster sources and raster layers.
This ticket will probably be become 2 seperate tickets later

Todo:

Must
- delete raster sources not implemented
- flush raster sources not implemented

Could
- improve styling to exactly match design
- routing should be able to set filters in table
- refactor styling, not sure about some choices

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

In your design the navigation tiles for "rasterlayer" and "rastersource" seem to navigate to the same rasterlist page.
See here:
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/2e403a90-ee28-402b-8643-e6783a54c76f

Is this correct?

kr Tom

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
As part of the generic raster table layout, I am going to make a component that deals with the layout of the explainbox visible on the left.
Let me know if you already did this or see other problems
kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,
That's great! I didn't do it yet. Thanks!

**Comment by Derryrover** [comment]
@caspervdw 

Hi Casper,

I am currently building the new raster lists (sources + layers) and run into the following things:

- in the raster_layer api the raster-sources are an array of urls. In the management client in the table I am supposed to show "based_on". I assume this is the source. 
Would it be possible to include the name of the raster source here? 
Otherwise I have to do a api call for each rastet layer to retrieve name of the raster source. 
This is not only very costly for the backend, 
,but also is going to be tricky to program on the frontend since I created a generic state manager to keep the state of the table.

- flushing rasters now works with deleting and recreating the source. How will this work with the current raster sources layers strategy?

kr Tom

**Comment by Derryrover** [comment]
@remcogerlich 
@hoanphungt 

Hi Remco and Hoan,

Here is the pull request for the table component:
https://github.com/nens/lizard-management-client/pull/475
It is not finished yet:
- still needs more type annotations
- some architecture might still change.

kr Tom

**Comment by Derryrover** [comment]
@LirryPinter 
@remcogerlich 

Hi Lirry,

I received the following 2 comments from Remco concerning ui ux:

- There is a lot of whitespace left right top and bottom. Not a lot of table rows fit on the page. Would it not be more logical if we can fit as many rows as possible on the page?
My own thoughts on it:
Optionally we can make the tablerows background color switch on even odd (like in your previous design) and remove space between the rows.
Also currently row height is based on content. We could make the row height fixed instead.

- Right now I build that there can still be a scroll on the table body. Remco thinks we should either have scroll or pagination not both. 
My own thoughts:
Not sure if we can completely prevent scroll from happening.  Should we make the table row height fixed instead of based on content? Or should we make scroll on the whole page instead of table body? Also do we have maximal 10 items per page? because when user sets more it will also create a scroll. Optionally we can also move pagination to the top and remove table footer.

kr Tom

**Comment by caspervdw** [comment]
>     * in the raster_layer api the raster-sources are an array of urls. In the management client in the table I am supposed to show "based_on". I assume this is the source.
>       Would it be possible to include the name of the raster source here?
>       Otherwise I have to do a api call for each rastet layer to retrieve name of the raster source.
>       This is not only very costly for the backend,
>       ,but also is going to be tricky to program on the frontend since I created a generic state manager to keep the state of the table.
> 

That is certainly doable. I do think the response would become to large for the list view. Is it OK to hide the `raster_sources` field in the list view, and display a nested version in the detail view?
Or another approach: hide the field altogether and make a separate endpoint `rasters/{uuid}/sources/` or a filter `rastersources/?layer={uuid}`

>     * flushing rasters now works with deleting and recreating the source. How will this work with the current raster sources layers strategy?

The term "flushing" applies to the rastersource, and not to the rasterlayer. So a "flush" button on the raster[layer] management screen would be confusing.
That said, the feature just isn't there currently. We should make it in the backend.

**Comment by hoanphungt** [comment]
Code looks good! Some small comments (mostly about missing css files and type definitions) but we can have a look at them later. For now, it's good to merge into the feature branch.

**Comment by Derryrover** [comment]
@LirryPinter 
Concerning the ordering on size.
See the dependent ticket
