### ISSUE TITLE
Find out where the pagination apiv4 is used

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#464]
Find out where the pagination apiv4 is used.
- Where is pagesize=9999 or high number used ?
- where is pagesize=-1 used ?
- in general where is apiv4 pagination used in our clients?
- How much effort would it cost to use the previous next buttons.

**Comment by Derryrover** [comment]
Blocking:
https://github.com/nens/lizard-nxt/issues/4254

**Comment by caspervdw** [comment]
Hi @Derryrover 

Do you have any updates on this? I'd like to start working on changing towards cursor pagination in the coming months as API v4 will probably become stable soon now. We'll need to get it in before.

**Comment by Derryrover** [comment]
@lexvand 

Hi Lex,
I moved this intoo current milestone, because we need to do it next sprint.
kr Tom

**Comment by Derryrover** [comment]
Searching through github:
https://github.com/search?p=5&q=org%3Anens+api+v4+page&type=Code
https://github.com/search?p=3&q=org%3Anens+api+v4+page_size&type=Code

Find 3 apps that need close inspection:
- management client
- catalogue
- tile dashboard

**Comment by Derryrover** [comment]
@lexvand 
@caspervdw 

Hi Lex and Casper,

To my understanding we might need this soon.
I estimated 18 points (see above for details).
Maybe next sprint?

I think this is a useful ticket,
but i also see a lot of uncertainties still (even after this research).
While working on this we might realize we need some backend things as well.
I think we should start asap.

kr Tom

**Comment by caspervdw** [comment]
That is a lot of work, 18 days. I had to give this some more thought.

We wanted to do all endpoints with the same pagination style, as consistency benefits usability.

However, if it is so much work, I do not think it is worth so much effort to have the consistency there.

The only places where we _really_ need the cursorpagination is the large (N > 100000) endpoints: timeseries, locations, and all assets (parcels, bridges, measuringstations). Rasters and scenarios endpoints are doubtful, they are more in the 1000-10000 range. The rest of the current v4 endpoints will most probably never grow beyond 100000 records.

What if we would only do timeseries, locations, all assets? @byrman What do you think?

**Comment by Derryrover** [comment]
@caspervdw 
@byrman 

Hi Casper and Carsten,
18 days for client cursor pagination is in fact a lot, but we might still seriously consider it. 

Do keep in mind that some of these 18 days we likely need to perform sooner or later anyway:
- remove the page_size=99999 6 days
- remove / improve old code of management client 2 days

Also because this is a api breaking change it is hard for me to make an accurate estimate.
I may over estimate, because I need to keep in mind usages that I am unaware of. 
Just like you I also prefer the pagination to work everywhere the same.

kr Tom

**Comment by lexvand** [comment]
I close this issue. Continue conversation in nens/frontend-tasks#8.
