### ISSUE TITLE
Management 2020: Design 3Di scenarios clean functionality

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#465]
For HHNK we need additional functionality for the management screens:

Design is ready and approved by customer:
https://xd.adobe.com/view/c69b4792-e778-401c-982d-5c57caedf761-93c8/

**First meeting**
Belangrijke punten overleg HHNK (Scenarios in Management 2.0) :
-	Berekening moet reproduceerbaar zijn
-	Persoonlijke verantwoordelijkheid
-	Hoe ze het nu doen: lange excelsheet  beslisssen welke weg moeten (filtering)
-	Hoe maak je schoon? NetCDF mag vaak weg, neemt veel ruimte in
-	Soms zitten er foute berekeningen bij 
-	Ze hebben behoefte aan tags om aan te geven wat er met het scenario aan de hand is.
(1 Via 3Di van tevoren)
(2 Misschien op Lizard nog kunnen aanpassen)

**Comment by LirryPinter** [comment]
- Derived maps (rasters) listview in het scenario details scherm.
- Die moeten verwijderd kunnen worden 
- Andere dingen die aangepast kunnen worden (denk aan colormaps)
- Vragen bij eerste feedback sesh, en/of wouter en marcel bellen over wat ze dan willen met die maps

**Comment by LirryPinter** [comment]
- Andere manier van deleten binnen een scenario

**Comment by lexvand** [comment]
@LirryPinter 
Waar ik eerst dacht dat bepaalde raster layers niet onafhankelijk verwijderd konden worden, blijkt dat met de huidige opzet van raster sources en raster layers wel mogelijk. Daar hoeven we dus niet per se rekening mee te houden.

In de bijlage de mogelijke results op een rijtje. Ze zijn gesorteerd op de opties voor de postprocessing vanuit 3Di. Dat lijkt me ook de logische verdeling qua opties om onderdelen van de resultaten te verwijderen.

[3DiResultsSortedForDeletionInManagement.xlsx](https://github.com/nens/lizard-management-client/files/5341588/3DiResultsSortedForDeletionInManagement.xlsx)

**Comment by LirryPinter** [comment]
@lexvand Ik ga het verwerken! Bedankt!

**Comment by LirryPinter** [comment]
Notes from the first feedback:

* NetCDF is logischer om Raw results te noemen
* Namen zijn eigenlijk altijd te lang voor de velden. Vooral scenario naam belangrijk (misschien iets meer spacing?)

**Comment by LirryPinter** [comment]
Tickets for the backend are being made by @byrman

**Comment by LirryPinter** [comment]
Tickets for the frontend are being made by @Derryrover
