### ISSUE TITLE
Layer Collections (rename Datasets and add management)

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#477]
Currently on rasterlayer form there needs to be a dataset field.
Is there a need to manage datasets by itself ?
Should they have their own table form ?
Or can we just manage them as part of the rasters / wms / other? items they belong to?

~Dataset record on the backend also has no Django admin screen.~ (They do)
Dataset itseelf contains authorisation fields like acces-modifier, organisation and supplier.
Dataset has a m2m relationship with rasterlayers **and wmslayers**. It is basically a tag on layers. One layer can have multiple tags and the same tag can be added to multiple layers.

**Comment by lexvand** [comment]
Yes, should have its own management page. We need to discuss whether this is is crucial for the first version or that we pick it up right after that.

**Comment by lexvand** [comment]
@LirryPinter @joeriverheijden We need to decide what to do with datasets. Do we want to rename them to tags and simplify the model by getting rid of the access_modifier? This determines whether we need a separate management page for datasets and whether backend work is needed first. Of course it also influences the catalogue setup.

**Comment by LirryPinter** [comment]
@joeriverheijden @lexvand 

Lets have a meeting about this soon

**Comment by joeriverheijden** [comment]
@LirryPinter can you plan a meeting for this?

**Comment by LirryPinter** [comment]
- Rename to layer collection because that handles the load better

**Comment by joeriverheijden** [comment]
@daanvaningen @Derryrover kunnen jullie hier a.u.b. tickets voor aanmaken n.a.v. het overleg over dit onderwerp?

**Comment by Derryrover** [comment]
I made this ticket for the frontend work.
https://github.com/nens/lizard-management-client/issues/870

@LirryPinter 
Lirry could you also link the design ticket?

@joeriverheijden 
@lexvand 
Are we sure about this name change? It is causing extra work for backend.
Which other names have been considered?
Can we have a userstory to verify the namechange actually covers the load?

**Comment by joeriverheijden** [comment]
Yes we're sure.

**Comment by lexvand** [comment]
@Derryrover I'm missing an issue for adjustments to the catalogue. And can you check whether the Klimaatatlas uses datasets?

**Comment by joeriverheijden** [comment]
@lexvand @Derryrover Klimaatatlas doesn't use the API-call. It links to the catalogue and might visualize layers through a WMS link. 
The WMS link does not refer to the word "dataset". E.g. if a dataset is named "klimaatatlas" then the WMS link becomes demo.lizard.net/wms/klimaatatlas/?request=GetCapabilities. 
So i think Klimaatatlas will be fine. Or am i missing something @Derryrover?

**Comment by lexvand** [comment]
@daanvaningen Can you create an issue for the backend work of this epic?

**Comment by daanvaningen** [comment]
Will do!
