### ISSUE TITLE
Icons Layout header footer body

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#480]
Todo:
- [x] Icons in profile dropdown like in screenshot below. Wating for icons to be exported
- [x] Restyling the user dropdown
- [x] background color of primary header should be #008080
- [x] check color other components

Layout header footer body
The layout is currently done with flexbox, the original grid seemed to be removed.

Somehow scaling the body to fit screen fails. 
Possibly in combination with the grid table layout or maybe already on itself.
Needs investigation

_______________________________--

more info:

Header Body must fill screen.
For the table we currently have the prolem that scrolling the table creates the whole page to scroll not only the body of the table.
I suspect this has something to so how the header and body of the whole page are setup.
Possibly it is also mismatching with the grid layout of the table itself.
I need to investigate this.

Currently for the table we decided the body of the table to scroll (so not the whole page).
Will this also be the case for Forms and tiles? most convenient if it iv everywhere the same.

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,
Just to make sure: Is it correct that we remove the footer? (like in your design)
I think removing the footer is a good move, it wasted a lot of space for very little value.

We do need to find a new place for:
- support
- documentation
- language picker -> probably no need to find a new place for this one, see here: https://github.com/nens/lizard-management-client/issues/496#issuecomment-724730185

Could you pick that up?

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

Hi Tom,

In my design I put these elements in the user menu in the right top! 
![image](https://user-images.githubusercontent.com/44164164/98925317-222e6800-24d6-11eb-8387-a4b9a4dfa046.png)

I made it a component, but it appears to be not included in the design for the rastermanagement

**Comment by Derryrover** [comment]
merged header color without review

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

I cannot find the assets for the icons of your above screenshot.
Could you export them?
For the time being I use the old icons.

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

The color of the header is still not the correct one.. Its this hexcode:  #008080.

I can make a pull request myself if you want

**Comment by Derryrover** [comment]
@LirryPinter 
I added it to the todo on top of ticket (feel free to update description of ticket yourself). 
I will pick it up as soon as you promise me the icons (see previous comment ;) )

**Comment by LirryPinter** [comment]
@Derryrover 

I already did that! ;)

![image](https://user-images.githubusercontent.com/44164164/100360455-42dbdf00-2ff9-11eb-9138-09f734f2b499.png)

**Comment by GeOdin** [comment]
@Derryrover 
Hey Tom :)

I checked the following, and they look good!

- [ ] Icons in profile dropdown like in screenshot below.
- [x] Restyling the user dropdown
- [x] background color of primary header should be #008080
- [x] check color other components

For the documentation icon in the drop down: the right side of the icon is not entirely visible in Chrome on the resolutions 1366x768 and 1920x1080. 
Is this easy to change or shall I make a new ticket for it?

![20210120-raster-management-staging-header.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/a569fcff-5f90-4c39-bd62-4b0d378103d4)


Kind regards,
Madeleine

**Comment by GeOdin** [comment]
Hey Tom,

It looks good. :)

- [x] header fills screen nicely
- [x] table raster layer and raster sources now scrolls nicely the body of the table

Kind regards,
Madeleine

**Comment by Derryrover** [comment]
@GeOdin 

Hi Madeleine,

Goed dat je het probleem met het icon hebt gezien !
I just deployed a fix to staging.
Could you verify the problem is resolved for you?

kr Tom

**Comment by GeOdin** [comment]
@Derryrover 
Hey Tom :)

Thank you for fixing the icon!
It looks nicely. :)

Kind regards,
Madeleine
