### ISSUE TITLE
Modal for deleting raster sources and layers

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#482]
Done for Wms and raster-layers.
Todo: raster-sources.
Also review related ticket.

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

The modal for deleting raster sources is still a bit abstract.
Especially if the user deletes multiple raster sources at once (do we support that? I thought yes).
Do we want to list which layers are dependent on the source? Do we inform the user what happens to dependent layers? etc
Perhaps this needs a design.

kr Tom

**Comment by Derryrover** [comment]
I am going to start on this for WMS-layers and raster-Layers.
For raster-sources I wait for a design.

**Comment by LirryPinter** [comment]
@Derryrover 

Going to do this today!

**Comment by LirryPinter** [comment]
@Derryrover 

We can use the same modal as the one we use for going to the layers when we make a new raster source. If I remember correctly, the backend does not support yet showing which layers are connected to it. 

We make a warning message, I suggest something like:

"You are about to delete a raster source. This will cause some or multiple layers to stop working. Are you sure you want to delete this raster source?"

**Comment by LirryPinter** [comment]
@Derryrover @lexvand 

For WMS we can put the text:

""You are about to delete a WMS layer. It can not be viewed anymore in the Lizard Portal. Are you sure you want to delete this WMS layer?"

**Comment by Derryrover** [comment]
@LirryPinter 

> If I remember correctly, the backend does not support yet showing which layers are connected to it.

I think the backend may be able to do this.
Check here the "layers" field:
https://nxt3.staging.lizard.net/api/v4/rastersources/
Further under "delete" you can see a warning is given and delete fails if still layers are connected.
We may need to incorporate that in the design somehow.

**Comment by LirryPinter** [comment]
> Further under "delete" you can see a warning is given and delete fails if still layers are connected.

How do you mean? You can't delete if there are layers connected? That would be a problem. Or we need to delete the layers as well

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Had a first attempt at the delete modal.
Could you review?
https://github.com/nens/lizard-management-client/pull/538

Decided not to move all logic to the tableStateContainer yet.
I first wait for the design of the rastersource delete.

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover starting to review

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I reviewed and have some comments in the PR. Please have a look.

Kr, Hoan

**Comment by Derryrover** [comment]
merged the solution for wms and raster-layers.
Todo: raster-sources

**Comment by Derryrover** [comment]
![Screenshot from 2021-01-04 17-15-29.png](https://images.zenhubusercontent.com/5ede648087ac51301b8149ff/c9f38f82-08e7-4432-9392-9e0f8ddb472f)

**Comment by Derryrover** [comment]
@LirryPinter 
See comment above for screenshot from delete not yet allowed modal

**Comment by Derryrover** [comment]
During our meeting today we decided:

- raster source cannot be deleted via management client if it is used by other organisations. In this case user will see a modal that tells her to contact servicedesk. 
- Currently we need the 412 api response to decide raster is in use outside organisation. Showing if a raster is used outside organisation in advance of api call is complicated so now out of scope.
- if used by objects within organisations this needs be resolved before deleting. This is communicated in a modal similar to screenshot above. Modal might change graphical design.
- The links in the modal go preferably to the form, where a delete button/component will be added (or alternatively the links will go to the list or links can be a delete button themselves)

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Do you have timeto review this one?
https://github.com/nens/lizard-management-client/pull/564

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
I found a bug. For this raster source: http://localhost:3000/management#/data_management/rasters/sources/8e9af3f8-85ee-4086-8a1d-62b6e5e65b8b/. It previously has a connected layer: https://nxt3.staging.lizard.net/api/v4/rasters/e2cf8cda-7a6b-4867-984f-ffdf2df641a8/. I then deleted this layer by using the raster layer table. The layer is then deleted successfully. However, I still can't delete the original raster source. The modal said that it is still connected to the same layer (which has been deleted).

It worked well when I delete raster source without any layer connected to it.

**Comment by hoanphungt** [comment]
@Derryrover 
Apart from the above bug, the rest looks good. You can merge.

**Comment by Derryrover** [comment]
We have the following options for deleting labeltypes:

1. - deleting them straight inside the modal with a small button / link
2. - in the modal, place a link to the labeltype form (but both labeltype form + list + tile then first should be made)

I know that option 1 looks like less work, but I strongly prefer option 2. Why?

- It keeps the modal simple. Adding delete actions in a modal that was itself already for another delete action? We may have a modalception here.
- It re-uses already programmed components. We enhance and improve upon existing code instead of adding another exception to the ui.
- The modal list and form do not need to be that complicated. Even then they can easily provide more context then what can be spatially added in a modal.
- If we lateron support changing the source of a labeltype this can easier be supported in a form then by adding another link in the modal

**Comment by lexvand** [comment]
@Derryrover Talked to Joeri. He gives a GO for option 2 (estimated 1 day work).

Within the main management screen you can make a tile for labels, with a tile to labeltypes on the next level. As we discussed we leave all properties read-only. Just an option to delete labeltypes.

I guess one of the main things to look at is how the graph (json, possibly quite extensive) can be presented in the form. If this can be included as a scrollable text field that would be nice. If it becomes problematic we could decide to exclude this field from the form.

@LirryPinter There may be some priority design questions resulting from this coming your way.

**Comment by Derryrover** [comment]
I continue in this ticket:
https://github.com/nens/lizard-management-client/issues/566

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

regarding the bug.
I believe it is a backend bug so I created this ticket:
https://github.com/nens/lizard-nxt/issues/4737

kr Tom

**Comment by Derryrover** [comment]
merged

**Comment by lexvand** [comment]
Works neatly.
