### ISSUE TITLE
Restyle alarm management with components

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#483]

**Comment by hoanphungt** [comment]
@lexvand @Derryrover @LirryPinter 
Hi,

When checking the epic for the new alarm management, I noticed that there is no ticket and design for the new alarm form. Maybe there is a design for it but not included here, maybe not. It's quite an important part of the alarm management page. Please check this.

Kr, Hoan

**Comment by LirryPinter** [comment]
@hoanphungt @Derryrover @lexvand 

I can make a design just for the alarms, but its quite a lot. Which things are we planning to work on first?

In my understanding there are:

- Alarms
- Contacts
- Groups 
- Templates

Please tell me which one to prepare first

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry, in the epic, I can see that there are already tickets for contact form, group form and template form. There are also design links in these tickets (not sure if they are all updated). So the only one missing here is the alarm form (raster alarm and timeseries alarm).

**Comment by LirryPinter** [comment]
@hoanphungt 

I'll check now!
