### ISSUE TITLE
Styling table

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#487]
-	The checkboxes are too small -> coded
-	The ordening arrow doesn’t make sense (why is it too the side) -> use two arrow solution when not ordered -> coded
-	Spacing between columns doesn’t look good -> wait unclear if this is really a problem
-	The Actions need more margin between, this is too small -> coded css only solution -> might go for component based solution later
-	The delete button should be bold -> coded font-weight 600
-	The button of new should have a hover effect -> coded
-	Spacing between items per page and the dropdown -> coded
-	Going back arrow is not at all like in the design (why)? -> coded
-	Size should be in gigabyte not byte. We probably need to do trnalation from byte to gb clientside -> coded so it shows most appropriate unit byte mb gb
-	Pagination use real icons -> coded
-	Center spinner and no data elements. See comment Lirry below -> TODO!

**Comment by LirryPinter** [comment]
@Derryrover 

My notes based on the demo:

-	The checkboxes are too small
-	The ordening arrow doesn’t make sense (why is it too the side)
-	Spacing between columns doesn’t look good
-	The Actions need more margin between, this is too small
-	The delete button should be bold
-	The button of new should have a hover effect
-	Spacing between items per page and the dropdown
-	Going back arrow is not at all like in the design (why)?

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

Thanks for the feedback!
Sometimes it can be way faster to use some standard html component (for example the checkbox and backarrow). We can still follow the design eventually, but my priority is always to get a working product first.

Question:
 "The ordening arrow doesn’t make sense (why is it too the side)"  
---> This is how it shows if a column is orderable, but currently not ordered. Also here I didnot yet use icons but instead the standard characters >v^  How should this column look like in your opinion? I could not yet find it in the design.

This ticket will be picked up in this sprint and we might add more to the list as well.
Maybe you can perform some user tests on staging and find more items that need improvement.

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

Additional points:

- All the sizes are now listed in Bytes. I know it comes from the API like this, but nobody will know how much 5784374832748 bytes actually are (without a calculator). In the design they are also listed as GB, so would be good to fill the sizes in like that.

- About the ordening arrow: you see in the design just the ordening arrows as they should be. 
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/450f0556-e8ba-4e5a-9ed0-e3f368477aeb)
So we can do that it is ordened already like that. 
OR we can do two arrows that are activated once they are clicked. We can have a short meeting about this.

**Comment by Derryrover** [comment]
@LirryPinter 
I made a meeting to talk about the ordering.
We can look a bit at some examples maybe:
https://ux.stackexchange.com/questions/40772/how-to-show-the-user-the-possibility-to-sort-a-column-with-space-problems

I added the byte gigabyte problem to the list in the description.
Please add new items to that list and put in order of priority if needed.

kr Tom

**Comment by Derryrover** [comment]
@hoanphungt 
Hi Hoan, for your information:
I will be picking up styling of the checkboxes for the table now.
We probably will be able to re-use that for the form.
kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

Hi Tom,
Small feedback on the table:
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/3405288c-013f-4b45-8dea-c81947298f6a)

This text, and the spinner (which is probably the same component) are not centered. Also they don't seem part of the table since they move if you resize your screen.

Can  you add this to the list?
