### ISSUE TITLE
Scenario form field to delete scenario results

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#494]
Probably as in design:  by showing the available results grouped in the 4 export types.

Still investigate if we can use related list, but probably not.

Design: https://xd.adobe.com/view/c69b4792-e778-401c-982d-5c57caedf761-93c8/screen/8e00c8ec-d289-4cb1-b875-5752546ea9a8/

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/559?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Good!
Looks and works well!
We may lateron try to refactor the delete result component, but maybe there is really no need for that since this will be the only place we use it.
Ready to merge

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Thanks Tom, I merged it
