### ISSUE TITLE
Data used | Data not used scenario measurement

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#495]
This item is a dynamic item in the left side of the explaination column.
The backend is not ready yet to support it.
It is in the design currently a pie-diagram without the inside (donut diagram).

I think either a bar or whole pie will be better.
A bar diagram has the advantage we can easily place the legend right next to it.

Design here:
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/b22580f9-52f2-4a1a-9839-dc4b5d768b6d

https://github.com/nens/lizard-management-client/pull/925

**Comment by Derryrover** [comment]
@daanvaningen 
@lexvand 
Hi Daan en Lex,
https://xd.adobe.com/view/113cd145-2091-4d91-45c9-198c4b05f5bd-670d/screen/b22580f9-52f2-4a1a-9839-dc4b5d768b6d

- I think the "your storage" as in the graphical design is not possible currently via the API, correct?
- Shall we leave that out for now? 
- Place a "your storage ticket" in icebox or in won't do? 

gr Tom

**Comment by lexvand** [comment]
There is an endpoint for usage per user (`/users/{uuid}/usage`), but it is not specifically for one organisation. For many users it will be exclusively for one organisation, but it becomes unclear when a user is supplier to multiple organisations.

For now indeed leave it out and make a new issue for it in the New issues pipeline. We need to discuss whether we can support this better in the API.

**Comment by Derryrover** [comment]
@lexvand 
Okey made a ticket for "your usage" here:
https://github.com/nens/lizard-management-client/issues/926
So for now this is out of scope for this ticket

**Comment by Derryrover** [comment]
Old component:
__________________________
import React from 'react';

import {
  accessModifierHelpText,
  HelpText,
  organisationHelpText,
  supplierHelpText,
  uuidHelpText
} from './defaultHelpText';
import { bytesToDisplayValue } from '../../utils/byteUtils';



export const defaultScenarioExplanationText = (usedSpace:number, totalAvailableSpace: number, organisation: string) => {
  console.log('totalAvailableSpace', totalAvailableSpace)
  const usedSpaceString = bytesToDisplayValue(usedSpace);
  const totalAvailableSpaceString = bytesToDisplayValue(totalAvailableSpace); 
  const availableSpaceLeft = totalAvailableSpace - usedSpace
  const availableSpaceLeftString = bytesToDisplayValue(availableSpaceLeft); 

  const barchartHeight = 340;
  const fractionUsed = usedSpace / totalAvailableSpace;
  const fractionNotUsed = (totalAvailableSpace - usedSpace) / totalAvailableSpace;
  return (
    <div
      // style={{
      //   display:"grid",
      //   gridTemplateColumns: "1fr 1fr",
      //   columnGap: 5
      // }}
    >
      {/* <span>Organisation:</span>
      <span style={{ fontWeight: "bold" }}>{organisation}</span>
      <span>Used storage:</span>
      <span style={{ fontWeight: "bold" }}>{usedSpaceString}</span>
      <span>Available storage:</span>
      <span style={{ fontWeight: "bold" }}>{availableSpace}</span> */}
      {/* <span>Used storage:</span>
      <span style={{ fontWeight: "bold" }}>{usedSpaceString}</span>
      <span>Storage left:</span>
      <span style={{ fontWeight: "bold" }}>{availableSpaceLeft}</span> */}
      <div>
        <div
          style={{
            display:"grid",
            gridTemplateColumns: "1fr 1fr",
            columnGap: 5
          }}
        >
          <span>Total available: </span>
          <span style={{ fontWeight: "bold" }}>{totalAvailableSpaceString}</span>
        </div>
      
        </div>
        <svg width="264" height="400" viewBox="0 0 264 400">
          <rect
            x="10"
            y="50"
            width="80"
            height={barchartHeight}
            fill="blue"
          />
          <rect
            x="10"
            y={50+fractionNotUsed}
            width="80"
            height={fractionUsed*340}
            fill="red"
          />
          <g transform="translate(0 200)">
            <text x="0" y="0">
              <tspan x="0" dy="1.2em">Total space</tspan>
              <tspan x="0" dy="1.2em">{totalAvailableSpace}</tspan>
            </text>
          </g>
        </svg>
      </div>
  );
};


export const scenarioFormHelpText: HelpText = {
  name: 'The scenario name comes from 3Di. This name can be changed for your convenience.',
  uuid: uuidHelpText,
  modelName: 'The model that was used to create this scenario.',
  resultDeleteButton: (
    <>
      <p>Delete data that was saved in this scenario.</p>
      <p><i>Raw data takes up the most space, and deleting it will have no impact on the other layers created in this scenario.</i></p>
    </>
  ),
  organisation: organisationHelpText,
  supplier: supplierHelpText,
  accessModifier: accessModifierHelpText,
}

**Comment by hoanphungt** [comment]
Looks good! Approved

**Comment by lexvand** [comment]
Works and looks good to me.
