### ISSUE TITLE
Colormap modal to create custom colormap for raster layer

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#503]
Colormap modal to create custom colormap as in the design: https://github.com/nens/lizard-management-client/issues/237

Done:

- created modal
- added colormap type
- added colormap steps
- wired it to raster-layer form and api
- verify input

**Todo Important:**
- The colormodal needs to be smaller. The type radio buttons closer together. Investigate to make modal narrower.
- the buttons + - should be visible for amount of steps, but invisible for each seperate step.
- Make title components bolder

Todo Later:
- currently used backgroundmodal. has advantage over Modal.tsx that positioning is doen better and has fewer options. Disadvantage is that height needs to be hardcoded (not the case with Modal.tsx)
- Labels. labels are only applicable for discreet. A draft of labels exists within the code. We (Arjan + Tom) thought it became to complex because labels also have a language (englisth dutch etc.)
- preview colormap. The preview within the modal is not yet there and the preview in the raster-layerform only works with not-custom-colormaps.
The endpoint for previewing custom-colormaps is not yet in the backend so we might choose a client side solution?
- Name and description as in the design are not supported by the backend. I (Tom) think they are probably not that important so I will pressure them.

**Comment by Derryrover** [comment]
@lexvand 
@hoanphungt 
I extended the estimate to total 5 days

**Comment by Derryrover** [comment]
I am building the colormap picker as in the design here:
https://xd.adobe.com/view/70294934-13dc-48fb-8fb1-f02a2109ce9e-257a/screen/9a40ecda-959e-4980-a9dd-dedf9b02d6bd

I see there was a backend ticket here:
https://github.com/nens/lizard-nxt/issues/3912

Here is a rasterlayer with a custom colormap:
https://nxt3.staging.lizard.net/api/v4/rasters/09808eaa-0b17-4b4f-b653-4042eb476677/

**Comment by Derryrover** [comment]
@arjanverkerk 

Hi Arjan,
Do you have time to think with me about the colormap json?
Also I am looking for examples of a discrete and logarithmic colormap example in the api.
Plus a way to store "labels" for each step.
kr Tom

**Comment by Derryrover** [comment]
@arjanverkerk 
@LirryPinter 

Hi Arjan,

I got a happy flow working, but was wondering if the "name" and "description" field as in the graphical design should be added to the json.
If I add them to the json now I get "invalid key 'name'" error.
Another option would be to leave those 2 fields out for now.

kr Tom

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

For your information:
For me it is not entirely clear from the design when the colormap-modal should open end what should be shown when a custom colormap is selected in the colormap field of the raster-layer-form.
I will proceed a follows:
- the colormap modal will open if the user clicks (within raster-layer-form) on the colormap dropdown and picks the option "custom colormap".
  The option "custom colormap" will thus be added to the colormap dropdown/ select-options.
- If a raster-layer is currently using a custom colormap, then the colormap field in the raster-layer-form will also be populated with the text "custom colormap".

If this is not how you wanted it please let me know.

kr Tom

**Comment by arjanverkerk** [comment]
> Another option would be to leave those 2 fields out for now.

Leave them out, they are not supported on de raster layer objects - the colormap field there is just like the definition field of colormap objects.

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
Could you review this one?
kr Tom

**Comment by Derryrover** [comment]
![colormap.png](https://images.zenhubusercontent.com/5ede648087ac51301b8149ff/bf1162f3-6ac2-4c95-a6a2-d194fa81dd6c)

@LirryPinter 

Hi Lirry,

Thanks still for the feedback.
See screenshot above:
- I have moved the input arrow buttons.
- I have placed the radio-buttons (discreet, linear, logarithmic) buttons closer to each other. 
Let me know if you think I should also make the whole modal narrower. This is a bit more work, since the modal is used at different places and I need to put the width behind a parameter then.
- I took no action to support labels for now, but I will make a new ticket for it. Can you agree that this will be done in later iteration?
- other comments missed?



kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

Hi Tom,

Looks good! The only thing I miss now is making the colormap type, colormap steps and colormap values texts more bold to make them pop out (not too much please, just one level will suffice I think)

- Making it narrower would definitely be good because now we have a very wide fiels to support a small number, and the modal looks off that way. 
- About the label, I agree! Lets do it in a future iteration.

Asides from that nice work!

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Just reviewed the code and I have some comments. It's a lot of work and code to review, so I could not scan everything in details.

First, about its functionality and styling:
- The modal background component does accept width and height parameters to customise so maybe you can experiment more with it (default width and height is 70% for the modal box).
- When hover over the tiles for color map types, the cursor type should be pointer.
- The color steps have a very strong border around them which do not have in the original design. 

Secondly, about technical aspects, my biggest concern is that you use the form to make the color map modal. This requires a lot of changes in the structure of the form (as this color map form requires many exceptions). In my opinion, it would be simpler if it is just a modal component instead of a form with a value parameter that can be edited using the modal. What do you think?

Other than that, I have some small comments and questions in the PR. 

I would like to hear your opinions.

Kr, Hoan

**Comment by Derryrover** [comment]
Merged original branch.
Some changes needed in new branch:
- Make title components bolder
- When hover over the tiles for color map types, the cursor type should be pointer.
- The color steps have a very strong border around them which do not have in the original design.

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,
Good observation about the colormap form titles not being bold enough!
I checked it and it seems also to be a problem in all other forms (raster-layer, source, wms, scenario).
Could you verify on staging that you also think this?
I am going to fix it right now on dev.
kr Tom

**Comment by Derryrover** [comment]
merged without review:
https://github.com/nens/lizard-management-client/pull/587
- titles inform bolder
- cursor pointer custome radio select colormap
- cancel button wms-layer-form

**Comment by GeOdin** [comment]
@Derryrover 
Hey Tom :)

Currently, I am checking the color map modal.
If you save the default discrete or linear gradient color map, it seems that it is saved.
But, if you select the raster layer in the raster layer table, the color map field is empty again.

I have made a new ticket for it and asked Lex to plan it in: Default colormap is not saved (staging)#616
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/616

Kind regards,
Madeleine

**Comment by GeOdin** [comment]
The rest of the functionality works nicely. :)

I did notice that on screen resolution 1920x1080 and 1366x768, there seems to be a lot of white space above the save button.
You have to scroll down to go to the save button.
I made a ticket for that:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/622

Kind regards,
Madeleine
