### ISSUE TITLE
Find out how much time it takes to upload rasters 

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#506]

**Comment by LirryPinter** [comment]
Lex checked the last rasters, the range is in between 5 and 30 seconds. Noted that this is without the waiting queue/

Next step is to look at bulk (temporal rasters) that require a lot of uploads at once

**Comment by Derryrover** [comment]
Currently when uploading multiple rasters clientside via the managament screen, each consequetive raster .tiff file waits with sending data to the server untill all data from the previous call is finished sending to the server. Be aware, it waits untill it finished sending data to the server, it does not wait for the asynchronous task on the server to be complete.

**Comment by LirryPinter** [comment]
Made with Kibana, in seconds

![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/04a9ebc5-7da3-4fcc-8863-b08224610dc0)
