### ISSUE TITLE
Tile icons for rasters

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#514]

**Comment by Derryrover** [comment]
There exist a ticket for all tiles that need to be changed here:
https://github.com/nens/lizard-management-client/issues/449

**Comment by Derryrover** [comment]
https://github.com/nens/lizard-management-client/pull/515

**Comment by Derryrover** [comment]
merged without review

**Comment by GeOdin** [comment]
Hey Tom :)

It looks nice! :)

Kind regards,
Madeleine
