### ISSUE TITLE
Group Raster Sources & Raster Layers under Raster tile in Data Managemt

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-management-client#519]
![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/90a412c6-3786-4948-ba4b-2c5b337eb3e9)

**Comment by lexvand** [comment]
@LirryPinter Is this approved by you?

**Comment by LirryPinter** [comment]
@lexvand 

I agree, because then we can make it clear with the icons that raster layers and sources are inherently connected to each other!

**Comment by Derryrover** [comment]
@LirryPinter 
Good, which icon do we use for the initial raster tile?
One of the existing (see staging) or a new one?

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry, I temporarily use the icon for Raster Layers to represent Rasters. Is it ok?

@Derryrover 
I made a new screen for the tiles of raster layers and raster sources. Could you review? https://github.com/nens/lizard-management-client/pull/533

**Comment by LirryPinter** [comment]
@hoanphungt @Derryrover 

There is three icons in total:

The raster sources
![RasterSources.svg](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/7dd337dd-20e3-4df2-b4b7-2729ebf8bb9b)

The raster layers
![Rasterlayers.svg](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/60c25797-4f12-4cd0-8cfe-26eed510b19c)!

The top level rasters
[Rasters.svg](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/44266908-9736-4bcd-8437-7f0db87692b5)

**Comment by Derryrover** [comment]
@hoanphungt 

Good! ready to merge

**Comment by LirryPinter** [comment]
![Rasters.svg](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/15375ad2-22a8-4ce2-8243-d7ed878a3256)

**Comment by LirryPinter** [comment]
@hoanphungt @Derryrover 

Let me know what you think, I think it depicts correctly the relation between sources (being at the base) and layers (visualized on top)

**Comment by Derryrover** [comment]
@LirryPinter 
Hi Lirry, Icons for rasters look good!
The problem of a unclear relation between layer and source got improved.
It is now clear that both source and layer belong together and that layer somehow falls on top of a source.
We may still find ways to improve this even further.
kr Tom

**Comment by hoanphungt** [comment]
@Derryrover @LirryPinter 
I agree. So only for now, Lirry has 2 icons for the raster source. I prefer the 1st icon since the it takes up 1 layer and then the raster layer takes the remaining 2 layers. So it makes sense to me. What do you guys think?

**Comment by Derryrover** [comment]
Okey agree with you here Hoan and Lirry, first one seems more clear. But I am fine either way

**Comment by GeOdin** [comment]
Hey Hoan :)

The icons look nice.
Good work! :)

Kind regards,
Madeleine
