### ISSUE TITLE
Change guiding text in Raster Sources list view 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-management-client#520]
![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/e174c903-021a-4570-8255-52a260efdd21)

TEXT: 
Raster Sources are the container for your raster data. When uploaded to a Raster Source, your raster data can be published as a Raster Layer to be visualized in Catalogue and Portal or can be used in a GeoBlocks model.

**Comment by joeriverheijden** [comment]
@Derryrover @lexvand

**Comment by hoanphungt** [comment]
Merged without review

**Comment by GeOdin** [comment]
Hey Hoan :)

It looks nice!

Kind regards,
Madeleine
