### ISSUE TITLE
Enhance icons for raster management page 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-management-client#521]
![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/b9086f01-923f-4e44-8a97-0bec148c2aba)

**Comment by joeriverheijden** [comment]
@LirryPinter @lexvand

**Comment by LirryPinter** [comment]
@joeriverheijden 

Dit is inmiddels gedaan, moet je op staging zien. Kun je zeggewn of het zo ok is?
