### ISSUE TITLE
Change text in search bar for both Raster Layer and Raster Source listview

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-management-client#523]
New text: 
Type to search for name

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/c55fbe98-9001-4763-8769-45e14b7a7eac)

**Comment by joeriverheijden** [comment]
@Derryrover @lexvand

**Comment by hoanphungt** [comment]
Merged without review
