### ISSUE TITLE
Change guiding text in Raster Layers 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-management-client#526]
New text: 
Raster Layers are the visual presentation for your raster data. Choose the prefered Raster Source so that the Raster Layer fetches the right data and give the Raster Layer a name, description, observation type and styling. Once published, your Raster Layer will be visible in the Catalogue and Portal. 

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/f28174ed-1149-4da9-8c91-371dfe44c6ea)

**Comment by hoanphungt** [comment]
Merged without review

**Comment by GeOdin** [comment]
@hoanphungt 

Hey Hoan :)

I have 2 small comments:

* Would it be possible to change prefered into preferred?
* Would it also be possible to add the relationship between raster sources and raster layers here, to prevent confusion between them?

Kind regards,
Madeleine
