### ISSUE TITLE
WMS management - Form

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#528]
According to design by Lirry: https://github.com/nens/lizard-management-client/issues/500

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

I found the original ticket for which the getSpatialBounds button was added to the wms form:
https://github.com/nens/lizard-management-client/issues/351
According to the ticket that button is really a must have.

Also I added the slug field, because from the code it seems it is in some wms layers needed for this button to work, but I do not know in how many of the wms layers. Appearently some wms servers return multiple result layers and then based on the slug we can know which layer we are interested in. We can later remove it again if it turns out not needed.

kr Tom

**Comment by Derryrover** [comment]
@hoanphungt 
Hi Hoan,

Could you review 
https://github.com/nens/lizard-management-client/pull/530
(this pr is also on review for ticket https://github.com/nens/lizard-management-client/issues/443 )

kr Tom

**Comment by Derryrover** [comment]
Todo:

- Find out why in lizard-client legend is not working for "Tom copy natuurnetwerken", but for original "natuurnetwerken" it works
- Same with button getSpatialBounds, works for natuurnetwerken. Doesnot for copy.

**Comment by hoanphungt** [comment]
Hi Tom,

I am reviewing your PR. Here are some of my comments.

Functional wise:

- The dataset field is a multiple selection field. However, for Raster form, this is a single selection field. We should check which is the correct one to use here.
- The placeholder for WMS's description is `This is a layer based on raster_source`. I believe this is not correct.
- The `Tiled` field in design is named `Tiled WMS`. Anyway, I don't really understand this field.
- The `minimum` and `maximum` zoom fields and the `spatial bounds` fields when invalid do not have red border around the invalidated input fields.
- The `minimum` and maximum` zoom fields in previous WMS form only allow min 0 to max 31. Now, it allows any number range. Also, not sure if they are required fields. If yes, then they should have a `*` mark on these fields.
- The `organisation` and `supplier` fiels are read-only in the design.

Code wise:

- I am midway reviewing code. Mostly the spatial bounds field left. Some of my comments are in the PR.

I will continue to look at it. 

Kr, Hoan

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I have a PR for you to review: https://github.com/nens/lizard-management-client/pull/539. 

Kr, Hoan

**Comment by hoanphungt** [comment]
Hi Tom,

I noticed a few issues for the form in my previous comment are still there:

> The dataset field is a multiple selection field. However, for Raster form, this is a single selection field. We should check which is the correct one to use here --> I suppose the multi selection field you chose is a better choice.
> The placeholder for WMS's description is `This is a layer based on raster_source`. I believe this is not correct.
> The Tiled field in design is named Tiled WMS.
> The spatial bounds fields when invalid do not have red border around the invalidated input fields.

**Comment by Derryrover** [comment]
@hoanphungt 
Thanks for noting. I will start a new pr
