### ISSUE TITLE
explain side column needs to be dynamically filled based on the selected field item in form.

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#531]
Currently the explain sidebar shows static data based on the navigation / router.
But we also want to show data based on which fields in a form are selected (or something similar).

We probably need to save the currently active sidebar element in the redux store and dispatch actions from several gui elements.
Maybe we also need to dispatch an action when a user leaves a gui element, so the default element for that explainbox item is shown again.

Document with texts per field:

https://docs.google.com/document/d/16eU5w9JL1vSBLpeTH4lAXq3sMylvf_XQbLL0W1cvMAI/edit?usp=sharing

Still to do Lirry:
WMS
Scenarios (static for form?)
Static texts for the list views

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

Based on our conversation I made this ticket.
I do think this is a nice feature, but I tend to give it low prio for now because:
Currently I do not see any places in the design where the explain bar deviates from the more static content now working on staging.
This may be quite a lot of work to build. Also I think it works more intuitively if it works for all relevant elements. Not just some.

Imo we can build this if we have.
- A number of places / gui elements for which this needs to be implemented (including their design, image and help text)
- A strategy on when to show them. Is this on hover, on focus, onclick or all of them? This of course differs per element, but it needs to be thought out in concrete before we begin.

Please let me know what you think, and move in the right lane accordingly.

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

Hi Tom,

I am picking this up now, will make some drive documents with the points you described.

**Comment by LirryPinter** [comment]
@Derryrover @lexvand @hoanphungt 

see the document in the description. 

Lets have a meeting and discuss this

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/569? The text in the side column is changed dynamically based on the focus event of the elements.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Works good and code looks good too.
I like the way it is technically implemented in the useForm hook.
I think we are ready to merge.

Not sure about the shaking maybe being too obtrusive.
Also maybe it will be difficult to make this explainbox work for each little (sub)component or components outside form.
Let 's have a look what Lirry and Lex think of it.

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Thanks for your review. Yes, the shaking effect might be too much. Let's see. It can be easily changed to some smoother effect as well.

I am not worried about making this explain box work for other components, sub-components or components outside of the form since it only depends on the text that you pass to this explain box component.

**Comment by lexvand** [comment]
@hoanphungt Please adjust the shaking to only vertical as part of this issue.

**Comment by hoanphungt** [comment]
@lexvand @LirryPinter 
I just tried out the vertical moving effect on the explain box. However, it still looks not quite smooth. I tried the color changing effect as also suggested by Tom. It looks pretty nice and calm (using same color tone with the color used in the form), enough to draw attention to the box. I will deploy it to staging so you guys can have another look.

**Comment by lexvand** [comment]
I like it this way. It is more subtle and sufficient in combination with the size of the box that often changes when going from field to field.

**Comment by LirryPinter** [comment]
@hoanphungt @lexvand 

I think this can be a nice way, but its not perfect yet. As far as I can see there is no 'easing out' of the animation. Also we should make the action a bit longer (don't know how long it is now).

Could you add these things?

**Comment by hoanphungt** [comment]
@LirryPinter 
Sounds good! I will add the 'ease-out' effect and make it a bit longer (currently 0.8s to become 1s)
