### ISSUE TITLE
Design of Upload queue 

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#532]
Final design:

https://xd.adobe.com/view/5ecce11f-f196-4758-a8c6-c72b17e07562-0b9f/ 
(with downloadable assets)

**Comment by LirryPinter** [comment]
- Think about what we need to show
- Use knowledge gained from Kibana (times)
- Links to api?

**Comment by LirryPinter** [comment]
Design version 1

https://xd.adobe.com/view/eda684bb-be65-4b2b-879f-fc6b96240847-b8f5/screen/defe7dc4-08b8-4f0f-9555-b5961208a9d3/

**Comment by LirryPinter** [comment]
@Derryrover 
@hoanphungt 

First version of design is in the link.
Let me know what you think!

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry thanks for the design!

- I like the icons that indicate the progress.
- I think a single queue for all uploaded files is a good idea, but miss advantages/disadvantages concerning the alternatives.
- I miss a mechanism that prevents the user from closing the browser / app (if files are still waiting to be uploaded).
- I am wondering if users need to know to which raster a failed file belong for their convenience.
- I am not sure that a dropdown element should be used for a overview like this. People expect a select when they encounter a dropdown. That is not the case here. Also the space is just too small. Imo a fullscreen or big modal would be better.
- I can not abort certain upload actions, the existing solution has a abort button. We could even improve on that.
- I see 3 icons: waiting, failed, ready, but I believe there are 6 states: waiting to upload, uploading, uploaded waiting to start async task, uploaded async task running, finished, failed. Note the existing solution on prod also only handles the first 3 states. Among the 6 total states there are 4 states that could be considered waiting, but the first 2 of them will be aborted if the user closes the tab.

Let us talk about this on monday !

kr Tom

**Comment by hoanphungt** [comment]
@LirryPinter @Derryrover 
Overall, I like the icons that indicate the progress and the design. However, I think Tom has some valid points here. I agree with Tom on the followings:

- What will happen if user closes the browser/app while files are still being uploaded? Should we give them an alert if file uploads are not yet finished?
- Find out if we need to show our users which raster the upload files belong to and if uploading files to multiple rasters at the same time is an actual case?
- Concern over the use of dropdown. The dropdown seems small (although still enough space to display information). Maybe we want to include more information of the files (i.e. filesize, raster ...). Probably a big modal would be better.
- How do we support aborting action?
- States of async task: find out how many states are there and how we relate our flow with these states in the backend?

**Comment by LirryPinter** [comment]
@Derryrover @hoanphungt 


- I understand the closing the app only stops the process of the files that *are not even in the async queue yet* right? If yes, we will need a new icon/status for that, and indeed give users a warning (this can be the browser warning ofcourse) that there are still files that need to be put in the queue.

- The process is 'make a source' and then make a layer (based on a certain source), so this logic doesn't really apply right? There was decided earlier that we do not support the other way around. 

- I see, I think a big modal is no problem. Do you need a new design for that?

- I asked Carsten about aborting. If I understand correctly the moment it comes in the async task we can't stop it. 

- The user is concerned with 3 status, waiting/processing, success and error. Since the point above maybe requires a fourth we need to think about that. The other states Tom mentiones earlier we don't need to pass on to the user in the UI. 

Possible solution:

- Waiting, uploading, processing and success/failed states. The waiting and uploading are the same as the one tom mentioned: " waiting to upload, uploading ". These can be aborted, and the user will also get a warning if they try to close the browser. Once it is in processing the user does not get a warning since its then handled by the backend and can't be aborted anyway. Aftert that we show either succes or an error state. 

What do you guys think?

**Comment by Derryrover** [comment]
@LirryPinter @hoanphungt @lexvand 

Hi Lirry,
I think your "possible solution" and changing it to a modal would be an improvement.
I think we may proceed with a modal and your additions.
I still scheduled a meeting for this afternoon. 
I like to discuss:

- I miss the overview of the entire process when someone creates new raster source / or updates an existing one.
We have 3 different adobe designs for source layer and queue, but I believe integrating them together could help us.
I have some trouble clicking through the designs in the correct order.

- Perhaps we could go to a situation were you deliver several competing wireframes with pros and cons. After this the teams (or customers) can have one or several feedback sessions. The competing designs do not have to be perfect or look the most pretty, could be paper and pen. Currently any negative feedback is in terms of "I do not like this, have you thought of this", but with competing designs it will become: "I prefer a over b because ...". 

kr Tom

**Comment by Derryrover** [comment]
Additional notes
- the status uploaded waiting to start is relevant if we want to give estimation how long it may take
- do we need to show files waiting to be uploaded already in the queue? I think yes
- If user closes screen of unfinished tasks we have currently no way to save those task urls, so maybe localstorage

**Comment by LirryPinter** [comment]
- Make document for user flow through the raster sources and layers --> with the upload process included

**Comment by LirryPinter** [comment]
- Design modal for upload with the discussed points
- Find icons for processing serverside

**Comment by LirryPinter** [comment]
@hoanphungt 
@Derryrover 

Guys im working on the modal, what do you think of this idea?
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/8048addc-eb3c-4d15-905a-da760f94d51d)

We can split the ones in process with the finished ones to get a clearer overview? Or do you think its not necessary?

**Comment by Derryrover** [comment]
@LirryPinter 
Yes,

- I like how it looks
- I think seperating in 2 parts for finished and not finished is also a good idea.
kr Tom

**Comment by LirryPinter** [comment]
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/e1798305-2271-415d-9090-f4bda2a297ee)

Sereparated the two types of tasks.

**Comment by LirryPinter** [comment]
@hoanphungt @Derryrover 

Hoan mentioned that having seperate is  maybe redundant because the order is always the same. Also it poses a technical challenge to let the finished  uploads 'jump'  in to the next table!

Can we make a descision?

**Comment by hoanphungt** [comment]
@LirryPinter @Derryrover 
I prefer to have one queue over 2 separate queues like in this design:
![image (1)](https://user-images.githubusercontent.com/43402556/100749436-f3285980-33e4-11eb-8332-154cb72eb007.png) and keep the same order.

The reason is the file uploads happen one after another so it is easier to follow if the files are not jumping from `Uploads in Progress` queue to `Finished uploads` queue.

**Comment by Derryrover** [comment]
@LirryPinter 
@hoanphungt 
Okey one queue is also good by me.
I think we may easily add a second queue with another filter, in case we later change or mind
