### ISSUE TITLE
Authorisation of Access Modifier field in the Raster Layer form is not correct

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#534]
Currently, the access modifier field in the raster layer form is always disabled and the Private tile is always selected. The access modifier field in the raster layer should:

- Always inherit the access modifier of the selected raster source

**Comment by hoanphungt** [comment]
@lexvand 
The access modifier field in the raster layer form is not working correctly. I would like to add this one to the current sprint. And also, could you check if what I describe in the description is the correct way of how it should work?

**Comment by lexvand** [comment]
@hoanphungt 
I'm not sure what you mean by "always disabled". Can't the user change it in that case?

In case of a one-to-one relation between source and layer it would indeed make sense to have the same access modifier for both.

**Comment by Derryrover** [comment]
In my opinion a layer can be more restrictive than its source, but not be more open.
That means 

- a user can create a private layer on a public source
- but not a public layer on a private source

I also realize that this will be hard to implement failproof in our current authorisation model. Iagine if a user changes a source from public to private, should then all layers also change to private?
So a simple approach could indeed be to just use the same auth as from the source, but this opens the question:
why would a raster layer then have a auth field at all?

**Comment by hoanphungt** [comment]
@Derryrover 
As discussed during the standup, I keep it simple for now as it will inherit this property from the Raster Source. Could you review the connected PR?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

I think it is okey.
I feel we use some [kludge](https://en.wikipedia.org/wiki/Kludge) here,
but maybe we have to accept for now.

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Thanks for your review. Nice term kludge :) and yes, I also agree. Probably for now until we find better solution.

**Comment by GeOdin** [comment]
@hoanphungt 

Hey Hoan :)

It looks nice!
The raster layers get the same access modifier as the created raster sources.

Kind regards,
Madeleine
