### ISSUE TITLE
Deleting raster sources

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#540]
Here we can see that deleting a rastersource is possible with or without layers still connected:
https://nxt3.staging.lizard.net/api/v4/rastersources/

Deleting a rastersource has problems:
- What happens to existing layers?
- What do we communicate to the user about these layers?

Below I created a markdown with options, advantages disadvantages.
For updating that text I recomment using [**_Typora_**](https://typora.io/) (first locally save it as .md file)

**2 quick solutions may be:**
- allow layers without source. Allways allow deleting source (maybe with warning)
- delete source whenever last layer is deleted.

**Comment by Derryrover** [comment]
Source without layers | allowed | not allowed
-- | -- | --
advantages |   |  
  |   |

**Comment by Derryrover** [comment]
Source without layers | allowed | not allowed
-- | -- | --
advantages |   |  
  |   |

**Comment by Derryrover** [comment]
# Options

## Allow layer without source

| allow                                                        | not allow                                                    |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| + easier gui                                                 | + No layers with empty sources in the system                 |
|                                                              | + More predictable data                                      |
|                                                              | + less communication to user needed about potential missing sources |
|                                                              |                                                              |
| - Layers with empty sources in the system -> bugs?           | - gui somehow needs to prevent users from deleting sources that still have layers. (or also delete the layers!?) |
| - Communicate to the use that the empty layer is not working anymore |                                                              |

## Allow Sources without Layers

|               | allow                                                        | not allow                                                    |
| ------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| advantages    | easier gui                                                   | No need to communicate to user that she still needs to make a layer to actually use the raster |
|               |                                                              |                                                              |
|               |                                                              |                                                              |
| disadvantages | Layers with empty sources in the system -> bugs?             | No layers with empty sources in the system                   |
|               | Communicate to the use that the empty layer is not working anymore |                                                              |

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,
Please have a look at delete different options.
It is not perfect, but it is something.
kr Tom

**Comment by lexvand** [comment]
@caspervdw You investigated this in relation to scenarios. Can you give your opinion from the data model perspective. Mainly concerning layer deletion cascading into sources and vice versa. What actions are prevented by the backend?

Of course we can have a look if we can prevent any unwanted use by some frontend logic or by giving warnings.

**Comment by caspervdw** [comment]
The fact that we have chosen to make RasterSource and RasterLayer two entities with different authorization properties makes it that we can't really do a lot here automatically. There are issues everywhere.

The best we can do is offer the user to do a cascade in some specific cases.

# Cascade source -> layer

A source should not be deleted automatically when it is in use by a layer, because it will break the layers. It will be noted in the layer that it is broken: the layer.source will get a `"deleted_sources"` field with a list of deleted source uuids. It might lead to bugs, it is a situation I'd like to avoid. Still, users should be able to manager their own disk usage, so with enough warnings, it should be possible.

I like to propose the following on RasterSource deletion:
 - don't offer the delete option if source.layers or source.label_types are of nonzero length (it is in use - users should first delete associated objects)
 - DELETE to api/v4/rastersources/{uuid}/
 - if you get an error, we have an odd situation that the source is in use by objects that the current user cannot see. We have to
  explain this situation to the user, and offer the option to force-delete in a second step. This will break the associated layers, but   users should be able to manage their own disk use.

# Cascade layer -> source

Automatic deletion will lead to surprises, especially if a layer is a geoblock using multiple sources. Sources that could be cascaded into could still be in use by other rasterlayers/labeltypes (which are possibly not all even visible to the current user - see above)

I like to propose the following on RasterLayer deletion:
 - DELETE to api/v4/rasters/{uuid}/
 - Only incase is_geoblock=True *and* the associated source as no layers / label_types anymore, offer to delete the rastersource as well "because it became unused".
 - --> enter the logic described above, possibly leading to another question.

# Bulk deletion

Too complex to put all the questions into one flow, I think.

**Comment by Derryrover** [comment]
@caspervdw 
@LirryPinter 

Hi Casper and Lirry,

Casper, I like the overall description you give.
I see that we have no choice but to support deleting a raster-source still used (too bad). 
I like to add that for deleting a raster-source that still has layers we might benefit if we inform the user in advance instead of after she already attempted to delete (and received a 412). We currently have most (but not all) api information to predict a 412 will happen namely when the raster source still has layers or labeltypes.
The information we miss is when the rastersource still has layers or labeltypes that the user is not authorised to see.
Would it be possible to include a boolean (or other field) in the list api for raster-surces that indicates if the rastersource is used by items including those that the user is not authorised to see? This would give us greater flexibility.

Lirry, I think the overall framework of the design supports the 'formatted message' from Casper his latest comment.
I see the following 2 points we might need to consider.
- In case the raster-source is still used: Is a single confirm modal enough? Or do we need a second confirm? Or should we make a single confirm modal but somehow with more warning signs. 
Beware that the user actually might break things when deleting a source that is still used.
- the formatted message in Casper his latest comments also describes 'delete links'. Do we need these? Could we instead of delete links also make normal links that open the relevant record? How can the user then delete these records? What alternatives are there?

Some background:
I will continue working on this ticket as part of https://github.com/nens/lizard-management-client/issues/482
I will focus first on deleting a source that still has layers (because I think that is most important).
I will first focus on doing this for one raster source (because this is easiest).

kr Tom

**Comment by Derryrover** [comment]
@caspervdw 

Hi Casper,

In case a raster-source still has labeltypes the user should preferably first delete the labeltypes.
But to my understanding a api for that does not yet exist. Is this correct?
I am not so familiar with the label types.

kr Tom

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

I think it is still best to make a wireframe for full graphical design of the deletion for raster source.
Currently all I have is the latest comment of Casper + the existing modals.
I think for raster source deletion we might need some extra details.

kr Tom

**Comment by Derryrover** [comment]
@caspervdw 
@LirryPinter 

Hi Casper and Lirry,

Let us discuss this feature after the holidays.
My goal is also to prevent as much as possible buggy behaviour.
I currently like to add the following to what was already discussed:

- In case the raster source still has layers or labeltypes visible to the user (within the same organisation or for other reason visible),
I really see no reason why the user should not first remove these or connect them to a different raster-source. I think therefore we should make it "Forbidden" to delete a raster-source that still has these dependencies. 
The modal could attend the user to this and lead to the concerned records. Instead of showing a simple delete link we could link (open in new tab) to the form of the concerned objects instead. We of course will need a delete button on the form.

- In case the raster source only has dependencies that are not visible to the current user we will show a dangerous looking warning.
Additionally we may: 
Let the user check a checkbox before deleting.
Upon deletion create a new empty source for the affected organisations and connect the affected items to that. 

Because you are both on holiday and this seems currently our most urgent feature I must proceed already.
Let us discuss

kr Tom

**Comment by Derryrover** [comment]
@caspervdw 

Hi Casper,

I now realize that we do not hava a possibility to delete "labeltypes" if the rastersource still has dependent labeltypes.
Is it possbible to make a simple delete api for labeltypes? Or is this a big effort?

kr Tom

**Comment by Derryrover** [comment]
We have everything neede from the backend already.
I close this ticket
