### ISSUE TITLE
Timeseries alarm: Timeseries selection does not work since release

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-management-client#543]
Since release 9 december

(According to Lisanne, it worked 8 december)

If you got timeseries alarms -->  Timeseries selection✔ It remains empty.

Via F12 you get the following error: 

https://utrecht.lizard.net/api/v3/timeseries/https://utrecht.lizard.net/api/v4/timeseries/c53a0ac5-6c4b-4cc5-9f77-7e2b28a4f92b//
Request Method: GET
Status Code: 404 

Which makes sense, this url is not built up as it should. 

High prio, at least for Utrecht WRIS

@lexvand @joeriverheijden

**Comment by lisannewapstra** [comment]
Hi Tom, 
Lex said I could assign you.
WRIS Utrecht wants to demo the management screen tomorrow, so I hope it can be fixed today.

**Comment by Derryrover** [comment]
Okey I deployed a fix to staging.
Check it here:
https://nxt3.staging.lizard.net/management/#/alarms/notifications

If good I can go to production asap

**Comment by Derryrover** [comment]
The cause:
It seems to be that on timeseries-alarm endpoint the field "timeseries" was previously a uuid, but is a url now.

**Comment by lisannewapstra** [comment]
Yes, looks good.
