### ISSUE TITLE
Styling WMS Form

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#547]
Ticket to do remaining styling and other things for WMS Form:

- Datassets / Tags field
- slug
- [Lex] Placeholder 'http://example.com' looks too much like a filled in field. Please make lighter grey

**Comment by hoanphungt** [comment]
Fixed as part of https://github.com/nens/lizard-management-client/issues/614:

- Improve `datasets / tags` field
- Gave the value of the input field stronger color to distinguish with color of placeholder

**Comment by hoanphungt** [comment]
@Derryrover 
What styling improvement did you expect to do for the `slug` field in the wms form when you make this ticket?

**Comment by Derryrover** [comment]
@hoanphungt 

Not sure, I had expected that someone would had complained that it was not clear what the slug was for. But this didnot happen. So maybe just leave it. ;)

**Comment by lexvand** [comment]
Created #650 for some additional improvements later on. Okay for now.
