### ISSUE TITLE
Unable to upload new raster data

### ISSUE THREAD

**Issue by Wolfensteijn** [nens/lizard-management-client#551]
When using the Raster management screen, every raster shows the same message: "Uploading data not allowed for derived rasters"

![image.png](https://images.zenhubusercontent.com/5fd9ddc5bf69e00c20ee2972/0d81074a-095d-45ca-8038-c70efd6e2701)

I did a short smaple with several organisations, none of the listed rasters allow uploads now.

Example raster used in the screenshot:
https://nens.lizard.net/api/v4/rasters/bbff8543-55f6-4704-803d-78a6af84e31b/

**Comment by lisannewapstra** [comment]
@lexvand  @joeriverheijden gemeld door Water Insight 2012 0084 Uploading data not allowed for derived rasters

**Comment by lexvand** [comment]
@hoanphungt Could you have a look why the application doesn't recognize the writability of rasters? No change in the API concerning this expected, so it is a bit weird.

**Comment by hoanphungt** [comment]
@lexvand 
I just checked the code. Probably because it checked for `raster.source` but `raster.source` is not in the API anymore. There is now `raster_sources` instead which is an array of sources.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom, could you review the connected PR? https://github.com/nens/lizard-management-client/pull/552

**Comment by Derryrover** [comment]
Looks good and works.
approved

**Comment by hoanphungt** [comment]
@lexvand 
Fix deployed to staging

**Comment by Wolfensteijn** [comment]
Tested on staging, is looking good. I can upload rasters again to non derived rasters.

**Comment by hoanphungt** [comment]
@lexvand Hi Lex, does it need to go to production asap?

**Comment by lexvand** [comment]
@hoanphungt Go ahead.

**Comment by hoanphungt** [comment]
@lexvand @LirryPinter 
Cool! the fix is deployed to production successfully and I also put the new management client back to staging for Lirry.
