### ISSUE TITLE
Investigate: Table component, possible to handle delete of one row same as delete of many rows?

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#556]
Investigate: Table component, possible to handle delete of one row same as delete of many rows?

The files using the tableStateContainer component now implement a different function for deletion of single versus multiple rows.
Is it possible that the same implementation is used?

This would require giving the delete callback functions (many vs one) a identical signature in the TableStateContainer.

Investigate this.

**Comment by lexvand** [comment]
@hoanphungt Isn't this something you picked up in another ticket?

**Comment by hoanphungt** [comment]
yes, it's already done in another ticket: https://github.com/nens/lizard-management-client/issues/768. So this issue can be closed.
