### ISSUE TITLE
scenario list header filter checkbox size must be bigger

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#562]
The checkbox in the 3di scenario "only show own scenarios" should be bigger (see graphical design).

Probably best to pass size as a parameter to the checkbox component.
While at it we could also investigate if we can use the same checkbox also in the form.

Also note from Hoan that checkmark of checkbox is not always positioned in center of the checkbox:
https://github.com/nens/lizard-management-client/issues/439#issuecomment-752020088 --> Hoan checked again and this is not the case anymore.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/571/? I also used the new checkbox for the form.

Kr, Hoan

**Comment by Derryrover** [comment]
Yes looks good. ready to merge
