### ISSUE TITLE
Scenario list delete raw result action multiple only if possible

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#563]
The button "delete raw result" should only be visible if the scenario actually has raw results.
Also when using the checkboxes the header action "delete raw result (n)" n should be the number of the selection that actually have raw result.

**Comment by Derryrover** [comment]
@lexvand 

Hi Lex, 
I propose we put this to backlog, so we can work on the other 2 tickets instead.
kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/615/? I used the "has_raw_data" field in the API to know if a scenario contains raw data and to whether or not show the "Delete" button. I also refactored the TableStateContainer component a little bit as a part of this ticket to remove some unused codes (i.e. the mapStateToProps and mapDispatchToProps) and some "@ts-ignores".

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
Almost good!
Please have a look what you think about my suggestion in the pr.
kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Sounds good. I changed it to a function. Gonna merge it and make another deployment.
