### ISSUE TITLE
Delete labeltypes dependent on raster-sources

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#566]
UPDATE:
We decided to give creating the labeltype list form and tiles a go.
Given that the time spend is around one day.
_________________________________________________________

The link to labeltypes in the delete raster-source modal does not work.

api/v3 exists for labeltypes and also allows a delete:
https://nxt3.staging.lizard.net/api/v3/labeltypes/032f0a52-1aca-4e18-8a00-fa566b1ea88f/

Landgebruik is a raster-source that has one labeltype. So this one can be used to test.

We have the options to 

- allow the deletion of labeltype within the modal of delete raster source OR
- redirect to the labeltype form (that yet has to be builded together with a list and navigation tiles)

I prefer to navigate to the labeltype instead of deleting it in the modal because:
- it keeps everything using the same structure
- it might later give the user the possibility to swith labeltype source instead of delete
- no additional logic in the modal is needed

____________

**Comment by Derryrover** [comment]
Done:
- made tiles
- made list
- made readonly form

Todo:
- implement new icon (waiting design)
- implement delete button on form (waiting design)

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

So we decided to quickly draft a label type form in order to delete labeltypes.
It is in progress here:
https://github.com/nens/lizard-management-client/pull/568

What I need from you:

- A label icon
- a label type icon
- a design for the delete button on the form (perhaps included in the generic dropdown button with the 3 dots)

Thanks in advance!

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

![label.svg](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/11a9dfbb-007a-403d-9237-354aebf34f99)

This is the icon voor labels

**Comment by LirryPinter** [comment]
![label-types.svg](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/3cbd8788-e8c1-4121-9fbf-aa802459a561)

Label types

**Comment by Derryrover** [comment]
delete button in slack chat with Lirry.
ticket no longer blocked

**Comment by Derryrover** [comment]
![image.png](https://images.zenhubusercontent.com/5ede648087ac51301b8149ff/5242623b-c893-4bb4-9c33-801d9e171f32)

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Do you have time to review this one?
I have added delete buttons on the rastlerlayer form and labeltypes form.
I have alse made labeltype form and list in general

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom, 

Code looks good. There is a key missing in the render method of the ActionButton component. I added the key to remove the warning.

There is a small bug that I encountered. When I go to the Label Types list and use the arrow to go back to the LABELS. Now, if I click on the LABELS tile, it redirects me to a blank page (because of wrong URL navigation - it redirects me to `http://localhost:3000/management#/data_management/labeltypes` instead of `http://localhost:3000/management#/data_management/labels/labeltypes`

One extra comment, in the navigation tab, LABELTYPES should be LABEL TYPES (with space). Also in the tile, it should be LABEL TYPES instead of LABEL-TYPES (to be consistent with other places).

After fixing the above bugs and spellings, you can merge.

**Comment by lexvand** [comment]
@caspervdw I'm testing this issue and have a question about it.

Sources that are used in a labelType are handled correctly and receive a list of labelTypes in their detail endpoint. But in for instance [this labelType](https://nxt3.staging.lizard.net/api/v3/labeltypes/03145ef3-5538-4bde-be67-77cf3446a7e3/) a group of rasterlayers ("LizardRasterGroup") seems to be used that are not included in the dependencies.

Are we missing something here or does the labelType not actually make use of these layers and the related sources? The sources do not show a relation to the labelType.

**Comment by caspervdw** [comment]
In updating the `raster_sources` field, only the LizardRasterSource are indeed considered. We are indeed missings omething here.

https://github.com/nens/lizard-nxt/blob/master/lizard_nxt/modeldir/label.py#L334

**Comment by lexvand** [comment]
Created an issue for backend to solve missing dependencies.
