### ISSUE TITLE
Customer expressed that searching on different column would be a nice to have

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#574]
HHNK would for the scenario table also like to be able to search on other columns then just the name column.

Options:

- make the searchbar search other columns as well with a special search endpoint.
- put a dropdown in front of the searchbar to indicate in which column a search should be.
- Add a second searchbox for the specific column they want to search on, in this case user (nah)
- Add optional search boxes in the header for each searchable column

**Comment by lexvand** [comment]
@Derryrover @hoanphungt This may be picked up. See which search options are supported by the API and would be nice to implement for the different management screens.

**Comment by hoanphungt** [comment]
An example of this is done for the alarm contact list: https://nxt3.staging.lizard.net/management/#/alarms/contacts under this issue: https://github.com/nens/lizard-management-client/issues/651

**Comment by Derryrover** [comment]
WIP:
https://github.com/nens/lizard-management-client/pull/692

Do we also want to include UUID?
Or do we filter on uuid if no results are found initially (like in catalog)?
I just added the uuid filter at some places now.

Do we want to search on organisation_name? -> I assume no because user is already using it via an organisation.

Maybe best if we add all possible options, then test on staging exactly which searches we want, and comment out those we do not want.
I think I added all of them, except for uuid's on alarms and id's (not sure if id's possible)

**Comment by lexvand** [comment]
@Derryrover 
Feedback:
- Remove Dataset slug filter from WMS layers (not listed, no way to find the options)
- Remove Model revision filter from scenarios (not listed, part of model name)

Rest of the options are very useful and work correctly.

**Comment by Derryrover** [comment]
https://github.com/nens/lizard-management-client/pull/714

**Comment by lexvand** [comment]
@Derryrover This is the last open issue for the release "Alarm management (part 1)". Can you put this on staging so I can do a final test on Thursday morning?

If that goes well it can go to production and we have staging available for the rest of alarm management.
