### ISSUE TITLE
Loading monitoring network with lots of locations sometimes gives 504

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#577]
#### What went wrong?
Sometimes when you press on the select time series action (for timeseries), the loading screen crashes.

#### What did you do in which order?
Select a timeseries, 'Large N&S sample' in this case.
Select 'Select time series' from the actions.
The loading screen shows, but it hangs on the loading screen.

#### Who noticed it?
Internal

### Noticed where
Staging:
https://nxt3.staging.lizard.net/catalogue/?data=Timeseries&uuid=0026cda8-5497-4496-9a76-1c18b81c895c

### Used browser
Chrome (default for testing)

### Screenshot

![20210113-catalogue-staging-monitoring-network-locations-pagesize-10000-gives-504-error.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/454ccc98-2a9c-48fe-bc14-8ccdf6dae117)

![20210113-catalogue-staging-monitoring-network-locations-pagesize-10000-gives-504-error-2.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/4a2874b8-3c69-4e81-a25a-38238a2bab7c)

![20210113-catalogue-staging-monitoring-network-locations-pagesize-10000-gives-504-error-3.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/1b7e87d6-4d02-47d5-bfc0-4c7766868205)

Good luck!

**Comment by Derryrover** [comment]
@lexvand 

I think this ticket belongs in the catalog repo
