### ISSUE TITLE
Testing management screens - Design

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#579]
- [x] Lines around form fields thicker when selecting

- [x] Search bar and 'new item' button should allign vertically with the back button (so few pixels down)

- [x] Loading icon when searching is still not in the middle of the listview

- [x] Text in box should have more padding inside, and also more space between lines (24px)

- [x] When hovering over a bulk action (like delete), it should be underlined to indicate action --> separate ticket for this issue: https://github.com/nens/lizard-management-client/issues/509
- [x] Size of label and personal api key icons
- [x] New item button in personal api key table to the right side
- [x] Replace "/" by ">" in the nav bar
- [x] "name" field in personal api key form to become "Name *"

**Comment by LirryPinter** [comment]
- Lines around form fields thicker when selecting
- Search bar and 'new item' button should allign vertically with the back button (so few pixels down)
- When hovering over a bulk action (like delete), it should be underlined to indicate action
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/c77709cf-c3a7-4702-a7fa-206400d56cd4)

- Loading icon when searching is still not in the middle of the listview
- Text in box should have more padding inside, and also more space between lines (24px)
[Uploading... image.png]

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry, for this comment:

> Search bar and 'new item' button should align vertically with the back button (so few pixels down)

Which item would you like to move few pixels down (search bar or back button)? They actually belong to 2 different places (explain side column and the table), so it's a bit difficult to align them vertically.

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry, 
For your 2nd comment regarding the action button:

> When hovering over a bulk action (like delete), it should be underlined to indicate action

There is already an issue opened for this: https://github.com/nens/lizard-management-client/issues/509. This is because the HTML option tag is very limited to add custom styling. So I will not touch it here.

**Comment by LirryPinter** [comment]
@hoanphungt 

![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/191bd0e8-e139-4d12-ad80-1977cff1ec00)

Can you please add some padding on the inside, so the actions and checkboxes have more breathing room? :)

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry, 
I have 2 solutions to the padding issue:

1. To increase padding from 10px to 20px and it looks like this:
![Screenshot from 2021-01-26 12-03-50](https://user-images.githubusercontent.com/43402556/105837333-dc5e4780-5fce-11eb-93c8-58f50e613e38.png)

2. To position the checkbox and the actions button to the center of its parent container then it will have even more spaces around:
![Screenshot from 2021-01-26 12-04-19](https://user-images.githubusercontent.com/43402556/105837404-f1d37180-5fce-11eb-9858-0922be9002b0.png)

Which solution do you think better? I can of course combine both of them (so to increase padding between columns and position checkbox and actions button to the center).

**Comment by LirryPinter** [comment]
@hoanphungt 

The first option will be sufficient! Thank you!

**Comment by hoanphungt** [comment]
Merged: https://github.com/nens/lizard-management-client/pull/602 to feature branch

**Comment by LirryPinter** [comment]
@hoanphungt 

Some points:
- All the icons need to be the right size, right now the labels label types and personal api keys are too small. (on the left side of the list)
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/80e2d133-57c6-488c-889b-7bc263c8b67a)

- The 'new item' button at the personal keys should be on the right like the rest of the managementscreens.

- The '/' should be arrows to the right, like in the design

Overal looks very nice!

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry, I don't understand this one: `The '/' should be arrows to the right, like in the design`. Could you explain?

**Comment by hoanphungt** [comment]
All fixed under this PR: https://github.com/nens/lizard-management-client/pull/625/ plust with fixing "name" of personal API key form to "Name *"
