### ISSUE TITLE
Exclude 3Di scenario rasters in raster management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#584]
In the new management screens there is no option to exclude 3Di scenario rasters, which is going to cause a lot of clutter.

With the new scenario management I would expect that we exclude 3Di layers and sources by default in raster management.

A couple of problems with this:
- rastersouces endpoint doesn't support filter scenario__isnull=true
- rastersources of scenario's do not get a name (let alone a supplier_code), so there are a lot of nameless items in the list

**Comment by lexvand** [comment]
@LirryPinter Did we consider this in the design phase?

**Comment by lexvand** [comment]
We decide to exclude scenario results from the raster management. It's too much clutter for users of organisations that actively use both Lizard and 3Di and we don't like to include a checkbox for including/excluding again, like in the old client.

The backend already supports this for raster layers by the scenario__isnull filter. The filter is also going to be built for the sources.

In the next phase we will add a raster layer management screen within the scenario management environment. There the filter will be applied the other way around. Some of the options like deletion of layers and the link to the sources will have to be exclude in that copy of the raster layer management.

**Comment by hoanphungt** [comment]
@lexvand 
As far as I know, this scenario__isnull is only supported for the raster layer. For raster sources, we will wait for backend to also add this filter to the raster source. Could you link the backend ticket to build this filter here? Do we expect to have it done by this sprint? I will proceed with the raster layer first.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/599? As agreed with Lex during the stand-up, although the filter "scenario_isNull" is not yet supported for the raster sources in the backend, we still include this filter for the raster source table. It will not affect anything for now but will work once the backend is ready.

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
Please check my comment in the pr
kr Tom

**Comment by Derryrover** [comment]
Excellent ready to merge !

**Comment by lexvand** [comment]
Created #624 for a loose end. Rest looks good, in expectation of backend work.
