### ISSUE TITLE
Column 'Based on' is useless in raster layer list

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#585]
What is the purpose of this column?

- A link is shown, but you can't click it.
- It shows only one source. If a layer is based on multiple sources it is a wrong representation. (Same goes for source field in raster layer form)

In its current form I think it's better not to show it at all.

**Comment by lexvand** [comment]
@LirryPinter How to improve this?

**Comment by Derryrover** [comment]
@lexvand 
Hi Lex,
Some small changes can improve the situation.
Please have a look at the related ticket
kr Tom

**Comment by LirryPinter** [comment]
@lexvand 

Hi Lex,

"It shows only one source. If a layer is based on multiple sources it is a wrong representation. (Same goes for source field in raster layer form)"

There was decided before that this can never be based on multiple sources. So this point is not applicable!

**Comment by Derryrover** [comment]
Some decisions are made in the related ticket.

**Comment by hoanphungt** [comment]
Proceed further under: https://github.com/nens/lizard-management-client/issues/583
