### ISSUE TITLE
Checkboxes in management forms are clickable over the whole width of the form

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#586]
You can check/uncheck boxes by clicking to the right of them. This is very sensitive to unwanted actions.

For instance when filling in the shared with field you intuitively click above the list of organisations when you try to close what feels like a dropdown (it is in fact, but it is supposed to stay in place when you want to keep this option active).

I think it works better if only the box itself is clickable.

**Comment by hoanphungt** [comment]
Merged without review
