### ISSUE TITLE
Icon for Personal API key management tile

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#591]
@LirryPinter Could you create an icon for this?

EDIT:
Todo:

- Add Icon for api key management
- make explainbox api key management better fit page in chrome (currently scroll bar appears)

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry, 
Could you update this ticket with a link to the personal api icon?
kr Tom

**Comment by Derryrover** [comment]
@LirryPinter 
I moved this to your review column.
I am still missing the link for the icon, so I cannot proceed

**Comment by LirryPinter** [comment]
![key.svg](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/1ffdff77-dc20-4abb-bf9c-e45ced41c9e6)

@Derryrover @lexvand how about this?

**Comment by Derryrover** [comment]
@LirryPinter 

Thanks Lirry!

**Comment by Derryrover** [comment]
merged without review
