### ISSUE TITLE
Modal to show related rastersource(s) for layers

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#594]
The column 'Based on' will show the user whether it is a simple representation of a single raster source or a geoblock. First we showed this as plain text. Now we want to make this a link to open a modal in which (a link to) the rastersource is presented or in case of a geoblock the graph or a list of raster sources (to be decided).

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review the Modal to open clicking on the "Based on" column in the raster layer table to show related raster sources? I used the raster detail view API to get UUIDs of related sources. 

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Yes looks good !
ready to merge
