### ISSUE TITLE
Management client reachable for all users (because of api key management)

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#595]

**Comment by Derryrover** [comment]
There exist already the idea to make the "lizard-management-client" authorised for all users.
Currently only admins, managers and suppliers can reach it.

For the api key management it is nice if also 'normal' users (user role) can use it.
This was also already in the pipeline for the "landing-page".

Making management client reachable for all users has several problems we need to solve:
- Stop the redirect if or 404 if the user has only the user role.
- grey out all the tiles and input fields for the user that is not authorized
- more?

**Comment by Derryrover** [comment]
Almost finished, but blocked:
https://github.com/nens/lizard-nxt/issues/4786

**Comment by lexvand** [comment]
@GeOdin Just found one issue. Access to Personal API key management is only granted if you have the user role for an organisation. It should be available for any role, so for instance also for supplier-only users.

Check it out further and please create an issue for this and any additional problem you run into.

**Comment by GeOdin** [comment]
@lexvand 

Hey Lex :)

I made a new ticket for the findings here:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/632

Kind regards,
Madeleine
