### ISSUE TITLE
Raster source delete in list-page -> use detail api call to retrieve dependent layers and labeltypes

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#601]
Management client deleting rastersources in table page currently uses the list api to retrieve dependent layers and labeltypes.
Backend prefers to remove the layer andlabeltypes fields from list api.
Investigate (and implement?) the effort of using the detail api instead to get the dependent layers and labeltypes.

**Comment by Derryrover** [comment]
https://github.com/nens/lizard-management-client/pull/607

**Comment by Derryrover** [comment]
merged without review

**Comment by lexvand** [comment]
Tested it and works.
