### ISSUE TITLE
After creating new raster source without data, going back from create raster layer (via back arrow on website) crashes management screen

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-management-client#608]
#### What went wrong?
If you create a raster source without data, you get redirected to the create raster layer form.
If you now go back with the green back arrow on the top left of the create raster layer form (not the back button of the browser), the management screen crashes.

Note:
If you create a raster source without data, you get redirected to the create raster layer form.
If you now go back with the back button from the browser, you don't go back to the raster source you just created, but you get redirected to a new (empty) create raster source page.

Edit: found while testing the ticket:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/476

#### What did you do in which order?
Go to https://nxt3.staging.lizard.net/management/#/data_management/rasters/sources
Click on the '+ NEW ITEM' button on the top right.
Create a new raster source without data.
After clicking 'SAVE' in the botom right, you get redirected to the create a new raster layer form.
If you now click on the green arrow in the top left, the management screen crashes.

The page turns white and the console shows an error message:
Uncaught TypeError: Cannot read property '0' of undefined

Lex noticed that the next api request was done:
https://nxt3.staging.lizard.net/api/v4/organisations/61f5a464c35044c19bc7d4b42d7f58cb/users/?role=supplier
Pressing F5 or CNTRL-SHIFT-R no longer fixes this crashed state.
Could it be that the user does not have the rights to manage the raster? Or the user is in another page?
Could it be because the login is being worked on?

#### Who noticed it?
Madeleine (intern)

### Noticed where
Staging:
https://nxt3.staging.lizard.net/management/#/data_management/rasters/sources

### Used browser
Chrome (default for testing)

#### Pressing this back button crashes the management screens
![20210127-management-screen-staging-go-back-start.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/1b56a86f-fb59-471e-a78d-27d4bab00cfc)

#### Error message after the management screen crashes
![20210127-management-screen-staging-go-back-new-try-1.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/ce214d35-ec0c-43da-ae1c-8a7817755868)

Good luck!

**Comment by GeOdin** [comment]
@lexvand 
Hey Lex :)

I just made this ticket for the findings for uploading rasters with the raster management screens.

During reproducing the error, I wondered something else:

**Comment by GeOdin** [comment]
Since the ticket 'New source raster continue redirect goes to empty page' (https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/548undefined) is similar, it might be an idea to wait for that ticket to be finished before starting on this one.

I added that ticket as dependency to this ticket.

Kind regards,
Madeleine

**Comment by lexvand** [comment]
@hoanphungt Indeed I think it has to do with the fact that the request for users with supplier role only takes the first 10 results. In the Nelen & Schuurmans organisation we have 24 suppliers, so chance is that you are not on the first page. And because of that access is revoked.

**Comment by hoanphungt** [comment]
> During reproducing the error, I wondered something else (also mentioned in the description of the ticket):
> If you create a raster source without data, you get redirected to the create raster layer form.
> If you now go back with the back button from the browser, you don't go back to the raster source you just created, but you get redirected to a new (empty) create raster source page.
> 
> When a user starts from the raster layer table (https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers) and presses the create a new raster layer button in the top right, he goes to a create raster layer form. If he then clicks on a back button he gets redirected to the raster layer table.
> 
> What should happen when the user clicks on the back button if the user is directed to the create a new raster layer page after creating a raster source without data (whether this is done via the browser or the back button of the site itself)?

@GeOdin

When you click on the "BACK" button from the raster layer form, it is always supposed to redirect you to the raster layer table (as it is consistent with the use of the "BACK" button in all other places). In your case, in the 2nd screenshot, I see that the URL is `https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers` so this is the correct URL for the Raster layer table. The problem is it is now empty while it is supposed to be a list of 10 raster layers. Could you check the network tab for the API call to the rasters endpoint (https://nxt3.staging.lizard.net/api/v4/rasters/)?

**Comment by GeOdin** [comment]
@hoanphungt 
Hey Hoan :)

The fix you just did worked.
Thank you! :)

**Comment by hoanphungt** [comment]
@lexvand @GeOdin 
This bug happened due to the "raster.raster_sources" filed being removed from the API list view recently. Therefore, it is fixed after I made a new staging release for the new management client.
