### ISSUE TITLE
(TypeError) Cannot read property customColormap of 'null' (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-management-client#609]
#### What went wrong?
The raster management screen crashes when you select a custom color map that is none/ null.

Is this something to be handled in the frontend?

Edit: found while testing the ticket:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/476

#### What did you do in which order?
Create a new raster source without data and save.
Get redirected to create a new raster layer.
Select a none/ null custom color map.

#### Who noticed it?
Madeleine (intern)

### Noticed where
Staging:
https://nxt3.staging.lizard.net/management/#/data_management/rasters/sources
-> create new raster source -> create new raster layer

### Used browser
Chrome (default for testing)

#### Error message in the console
![20210127-management-screen-color-map-custom-color-map-cannot-be-null.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/1b3516b5-0ef5-48e0-9ecd-7248b5fc4c0e)

Good luck!

**Comment by GeOdin** [comment]
@lexvand 
Hey Lex :)

Just made the ticket for the custom color map is null error.

Kind regards,
Madeleine

**Comment by Derryrover** [comment]
@GeOdin 

Hi Madeleine,
Thank you for this finding.

I am investigating right now:
- I can fix the issue by giving the colormap a default value, but run into new issues when I do so:
the colormap itself now causes a crash in a validation part of the script
the colormap itself now valdates when it is actually empty
the min and max of the colormap invalidate correctly, but the errormessage is on on colormap field itself

I am investigating now

kr Tom

**Comment by Derryrover** [comment]
wip:
https://github.com/nens/lizard-management-client/pull/610

**Comment by GeOdin** [comment]
Hey Tom :)

Thank you for fixing the color map is null bug.

Kind regards,
Madeleine
