### ISSUE TITLE
Colormap min max validation error shows in colormap field instead of min max field

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#612]
The problem happens when you choose a max that is smaller then the min.
It does not happen when you choose a invalid number (for example in firefox it is possible to set in min a string 'qwerty', but then this problem does not happen)

**Comment by Derryrover** [comment]
@lexvand 
@joeriverheijden 

Hi Lex and Joeri,

I think this is a bug the user might often encounter so I moved it to the sprint

kr Tom

**Comment by joeriverheijden** [comment]
good!

**Comment by Derryrover** [comment]
Hi Hoan,
Works and looks good.
Ready to merge!
kr Tom
