### ISSUE TITLE
Default linear or discrete colormap is not saved (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-management-client#616]
#### What went wrong?
If you save a raster layer with the default linear or discrete color map, it seems that the color map is saved.
But, if you open the raster layer via the raster layer table, the color map field is empty again.
I would expect that the saved color map would be remembered if you open the raster layer from the raster layer table (https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers).

This seems to happen when you choose a linear or discrete color map, and do not change any of the other values in the color map modal. For logarithmic, this seems to be not a problem. I think this has to do with the fact that for the logarithmic default option, you have to change one of the steps, so that the saved color map is no longer the same as the default color map.

This happens when you create a raster layer from the raster layer table.
This also happens when you get redirected to the create a raster layer when creating a raster source from the raster source page.

Edit: this ticket was found out while testing the next ticket:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/503

#### What did you do in which order?
Create a new raster layer (https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/new).
Choose a default linear or discrete color map for 'Choose a color map' (do not change any of the other values!) and save that one in the color map modal.
The color map now seems to be saved.
Save the raster layer.
Reopen the just saved raster layer from the raster layer table (https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers).

#### Who noticed it?
Madeleine (intern)

### Noticed where
Staging:
Create a new raster layer
https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/new

### Used browser
Chrome (default for testing)

#### The settings for the default color map
Just let this modal be opened and press save in the bottom right.
![20210130-management-screen-staging-default-linear-color-map-not-saved-1-save-default-colormap.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/dd1d5fb3-0ac8-4e58-b905-9bf91372dbea)

#### The color map is shown as saved while still in the raster layer creation screen
![20210130-management-screen-staging-default-linear-color-map-not-saved-2-er-staat-wel-netjes-color-map-edit-na-colour-map-saved.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/394f663a-bb2e-4959-b466-cc30c60d8488)

#### The color map is no longer saved if you open the created raster layer from the raster layer table
![20210130-management-screen-staging-default-linear-color-map-not-saved-3-reopen-raster-layer-after-raster-layer-saved.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/9ec29895-dada-4d51-82f2-b0c77120e46f)

Good luck!

**Comment by GeOdin** [comment]
Hey guys :)

A small sidenote for the color map modal:
Shouldn't the color map types not be:
'Discrete', 'Linear Gradient', and 'Logarithmic'
instead of
'Discreet', 'Lineaire Gradient' and 'Logarithmic'?


Kind regards,
Madeleine

**Comment by GeOdin** [comment]
@lexvand 

Hey Lex :)

During the testing of the color maps, I found a bug.
The default color maps for discrete and linear gradient are not saved.
Maybe we could also improve the spelling a bit, mentioned in the comment above.

Would this ticket be something to plan in?

Kind regards,
Madeleine

**Comment by Derryrover** [comment]
@GeOdin 

Hi madeleine,
Well found !
I am investigating right now
kr Tom

**Comment by GeOdin** [comment]
Hey Tom :)

Thank you for improving the custom color map!

Kind regards,
Madeleine
