### ISSUE TITLE
Multiple drop down boxes can overlap (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-management-client#617]
#### What went wrong?
If you open a drop down box above an already opened drop down box, the items of the top drop down box fall below the bottom drop down box. This is a chaining effect. If you open yet another drop down box above the previously opened drop down box, the items of the newly opened dropdown  box fall below the previously top drop down box.
If you would, however, select an item of one of the previously opened drop down boxes, that drop down box would close.

I would expect that the top drop down boxes would be shown on top of the drop down boxes below it.
Or that the other drop down boxes would close.

I found this out while I was testing the Upload files raster form #476:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/476

##### Example 1 - 3 overlapping drop down
1. Go to https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/new and open the 'Observation type' drop down box.
2. Open the 'Aggregation type' drop down box without closing the 'Observation type' drop down box.
3. Open the 'Source' drop down box without closing the other drop down boxes.
You now see that all the drop down boxes that were above the previously opened drop down boxes fall below the previously opened drop down boxes.
In the screenshot below, I selected the top item of the 2nd drop down box from above.

##### Example 2 - top drop down -> bottom drop down -> top drop down
1. Go to https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/new and open the 'Aggregation type' drop down box.
2. Open the 'Source' drop down box without closing the 'Aggregation type' drop down box.
You now see that all the items of the top drop down fall below the bottom drop down box. Because the upper drop down box is larger than the bottom drop down box, you start with seeing items of the upper drop down box, than items of the bottom drop down box, than items of the upper drop down box below the items of the bottom drop down box again.
In the screenshot below, I selected the top item of the 2nd drop down box from above.

#### Who noticed it?
Madeleine (intern)

### Noticed where
Staging:
https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/new

### Used browser
Chrome (default for testing) 

#### Example 1 - 3 overlapping drop down
![20210131-management-screen-staging-multiple-dropdown-boxes-over-each-other-2.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/a9b08904-d316-4ae5-b3c9-b7f4478ea7e3)

#### Example 2 - top drop down -> bottom drop down -> top drop down
![20210131-management-screen-staging-multiple-dropdown-boxes-over-each-other.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/addb7530-b424-40cb-9e6b-427e1d2012ad)

Good luck!

**Comment by GeOdin** [comment]
@lexvand 

Hey Lex :)

While testing the raster upload screens, I noticed that the drop down boxes can overlap.
It could cause confusion for the user, if they do not understand which drop down items below to which drop down.
They might also think that certain drop down box items of drop down boxes below the selected top drop down box belong to the selected top drop down box.
If the drop down boxes are closed again, you can still see the proper items in the proper drop down box. So it might just cause confusion and does not interfere with the data.

I am not sure, but this might be a bit more difficult to fix.

Kind regards,
Madeleine

**Comment by Derryrover** [comment]
@GeOdin 
Thanks for reporting !
I will fix it as part of this ticket:
https://github.com/nens/lizard-management-client/issues/614

**Comment by hoanphungt** [comment]
Solved as part of https://github.com/nens/lizard-management-client/issues/614
