### ISSUE TITLE
Custom colormap modal lots of white space and needs scrolling to save (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-management-client#622]
#### What went wrong?
When you open the custom color map modal you need to scroll down before you can save the color map.
This happens on resolutions 1366x768 and 1920x1080 (screenshots below are from 1366x768 which is supposedly the most used browser.

Noticed while testing Colormap modal to create custom colormap for raster layer #503: https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/503

#### What did you do in which order?
Go to the raster layer table page: https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers
Select a raster or press on the '+ NEW ITEM' button to create a new raster.
Open the custom color map modal (screen resolution 1366x768 or 1920x1080).

#### Who noticed it?
Madeleine (intern)

### Noticed where
Staging (edit/ create raster form):
https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/7551eee3-8362-48d7-85e4-dfa0fccb7840/

### Used browser
Chrome (default for testing)

### Screenshot

![20210202-management-screen-staging-custom-color-map-modal-needs-scrolling-1366x768-and-1920x1080.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/a058180e-d11c-45a0-b720-aa593e86c904)

![20210202-management-screen-staging-custom-color-map-modal-needs-scrolling-1366x768-and-1920x1080-2.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/d5d15a6a-2538-4320-8087-cf61c588fe3c)

Good luck!

**Comment by GeOdin** [comment]
@lexvand 

Hey Lex :)

When testing the custom color map, I noticed that there is quite some white space before the save button.
On resolution 1366x768 and 1920x1080, you have to scroll down quite a bit.

Maybe we can improve this by having less white space?

Kind regards,
Madeleine

**Comment by Derryrover** [comment]
On unbuntu chrome I only have this problem when setting my resolution to 1368 768.
I could fix it by setting the removing the "height 385px styling from the allColormapSteps StepContainer class

**Comment by Derryrover** [comment]
https://github.com/nens/lizard-management-client/pull/629

Above pr works, but is not perfect.
Might investigate more.

Currently I cannot test on windows (because of some authorisation issue?)

**Comment by Derryrover** [comment]
improved scrolling with flexbox.
Merged without review.
