### ISSUE TITLE
Possibility to select (empty name)/blanc raster source for raster layer (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-management-client#623]
#### What went wrong?
Currently there are multiple raster sources that have '(empty name)' in the raster source table.
You can select any of these raster sources as 'Data source' when creating a new raster layer.
This results in a list with a lot of blanc lines for the data source when creating a raster.
The user will not be able to distinguish between them.
Would it be better to also add a unique id of some kind in the data source drop down of the create raster layer form (similar to the aggregation type drop down box on the create raster layer form that also shows 2 properties in the dropdown)?
Or only show unique options (though the upper solution would probably be more suitable).

Noticed while testing Upload files raster form #476
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/476

#### What did you do in which order?
Go to https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/new
Press on the drop down for 2: DATA Source
You now see a lot of empty lines in the dropdown.

#### Who noticed it?
Madeleine (intern)

### Noticed where
Staging:
https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/new

### Used browser
Chrome (default for testing)

### Screenshot
![20210130-management-screen-staging-possibility-to-select-empty-raster-source_as-source.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/8ef6bb01-326b-4005-a47a-4dbfc00f9a44)

Good luck!

**Comment by GeOdin** [comment]
@lexvand 

Hey Lex :)

While testing the upload files raster form, I noticed that you can choose a lot of blanc (empty name) raster sources as 2: DATA Source for a new raster layer.
Would it be an idea to let users be able to distinguish between these no named rasters and/ or rasters with the same name?

Would it be better to also add a unique id of some kind in the data source drop down of the create raster layer form (similar to the aggregation type drop down box on the create raster layer form that also shows 2 properties in the dropdown)?
Or only show unique options (though the upper solution would probably be more suitable).

Kind regards,
Madeleine

Edit: I accidentally made this ticket for the wrong repo.
I will close the previous ticket after submitting this one:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/threedi-live-site/857

**Comment by lexvand** [comment]
@GeOdin This is partly something that is going to be fixed by excluding scenario results from the raster management (needs to be applied in form as well. I will create an issue for that) and the other part is a data issue. Towards the release we need to have a look which raster sources do not have a name and which we can update by giving a name. Again, a lot of these sources are scenario results.

**Comment by hoanphungt** [comment]
Raster source with empty name is now displayed by their UUIDs.
