### ISSUE TITLE
Show * after required 'Choose a color map' for raster layers (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-management-client#630]
#### What went wrong?
The color map is required for raster layers, but the field does not show a '*'.
It would be nice to also add a '*' after 'Choose a color map', just like the other fields that are required (for example 'Source', 'Aggregation type' and 'Observation type' for raster layers). This is the case when creating a new raster layer and when opening an already existing raster layer.

Noticed while testing:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/476

#### Who noticed it?
Madeleine (intern)

### Noticed where
Staging:
https://nxt3.staging.lizard.net/management/#/data_management/rasters/layers/new

### Used browser
Chrome (default for testing)

### Screenshot
![20210203-management-screen-staging-color-map-is-required-but-no-star.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/30eec25d-ba77-4e4e-8c33-cbb472799802)

Good luck!

**Comment by GeOdin** [comment]
@lexvand 

Hey Lex :)

This is the ticket for the missing asterix * for the required color maps field.

Could you plan it in?

Kind regards,
Madeleine

**Comment by hoanphungt** [comment]
Asterix has been added to the color map field in raster layer form.
