### ISSUE TITLE
Api keys only visible fur users with (at least) user role (staging)

### ISSUE THREAD

**Issue by GeOdin** [nens/lizard-management-client#632]
#### What went wrong?
If you are a user that does not have a user role for an organization, you cannot go to the personal api keys management page.

Edit: this was found while testing for this ticket:
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-management-client/595

#### What did you do in which order?
Make sure that you are part of an organisation for which you do not have the user role. Any combination of admin, manager and supplier is okay. As long as you don't have the user role. For example an organisation for which you only have the admin, only the manager or only the supplier role. For me, that organisation was 'N&S IT' (with only the supplier role).

You can either go to the management main screen. If you are part of an organisation for which you do not have the user role, the personal api keys tile is greyed out.
https://nxt3.staging.lizard.net/management/#/

Or you could go to the personal api keys page for an organisation for which you do have the user role. Then on the personal api keys page, press on the organisation in the list. You would see '! Not authorized to visit current page for this organization !' for organisations for which you do not have the user role.
https://nxt3.staging.lizard.net/management/#/personal_api_keys

#### Who noticed it?
Lex, Madeleine (intern)

### Noticed where
Staging:
https://nxt3.staging.lizard.net/management/#/

### Used browser
Chrome (default for testing)

#### Personal api keys greyed out if user does not have user role
![20210205-management-screen-only-for-at-least-user-role.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/10c1a6c7-14ae-4cf0-b054-2fcbf5633207)

![20210205-management-screen-only-for-at-least-user-role-2.png](https://images.zenhubusercontent.com/5edf4283e96d4a7cab88d584/cce79308-d821-48ca-a91e-c140fe27ef66)

Good luck!

**Comment by Derryrover** [comment]
@GeOdin 
@lexvand 

Hi Madeleine en Lex,

1. - If I understand correct the problem arises if the user has 'manager', 'admin' or 'supplier' role but no 'user' role. Correct?
2. - Or is it possible for users to have no roles at all (not even 'user')? What should happen then?
3. - Should I always assume that someone with 'manager' 'admin'  or 'supplier' is having all rights that a 'user' role has as well? Does the backend also work like that?

I will continue investigating, but my first impression tells me that maybe this user should always have the 'user' role for any organisation she is part of. But this depends on what backend thinks as well.

kr Tom

**Comment by Derryrover** [comment]
@GeOdin 
@lexvand 

Ah I see I was wrong.
It is better to make the tile 'personal api keys' available for all roles.
This is how we solved it with other tiles as well, and probably also how the backend works.
Let me know if you think otherwise

kr Tom

**Comment by lexvand** [comment]
@Derryrover 

1. True
2. That is technically possible, but practically we do not have to support that for now. It would conflict with the selected organisation in the top right dropdown, I guess. So management is only available to users that have at least one role.
3. That is a valid assumption. I think manager role is the only one that is not "user+", but in this case it is good to treat it the same as other roles.

**Comment by Derryrover** [comment]
@lexvand 

Thanks Lex,

I implemented as you described in bullet 3
https://github.com/nens/lizard-management-client/pull/634

merged without review
