### ISSUE TITLE
Design for alarm management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#636]
Part of the design has already been made in the general design. This needs to be updated, mainly focusing on functionality.

Focus points:
- Split raster and timeseries alarms
- Correct filter and ordering options in tables
- Add alarm forms
- Any specific styling that can't be derived from the designs for the other management components

Design of whole flow:
https://xd.adobe.com/view/63185198-afa0-4a27-9d61-dc0395753bf9-364b/

**Comment by lexvand** [comment]
@LirryPinter I specified the work in the description.

**Comment by LirryPinter** [comment]
@Derryrover @hoanphungt @lexvand 

The design is in the description. All the lists are finished, do not use the other stuff yet! Will keep you posted

**Comment by LirryPinter** [comment]
Think about the amount of timeseries for the timeseries form: Aka how are we going to filter these in a nice way

**Comment by hoanphungt** [comment]
@LirryPinter do you mean the timeseries alarms? We now have an async select dropdown (used for observation types and raster source in the raster layer form - you can check out how it works there), so it filters based on the input and gives 10 results back (or more depends on our preference).

**Comment by LirryPinter** [comment]
Questions for @lexvand  & Chris Gooch

Is a relative start/end always used?
How does it work in the backend?
What happens if you don't use relative start or end?
