### ISSUE TITLE
custom radio select drier

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#642]
https://github.com/nens/lizard-management-client/pull/641

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

I changed the custome radio select.
Wonder what you think
https://github.com/nens/lizard-management-client/pull/641

kr Tom

**Comment by hoanphungt** [comment]
Looks good :)

**Comment by lexvand** [comment]
@Derryrover Not sure what this is and how it can be tested. Can you give me a clue?

**Comment by Derryrover** [comment]
@lexvand 

basically a code improvement.
The radio button in the colormapmodal need regression test.
