### ISSUE TITLE
Uploads of raster files use the wrong url

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#644]
Remove "/management" from the url to upload the files to: nxt3.staging.lizard.net/**management**/api/v4/tasks/

**Comment by hoanphungt** [comment]
Fixed under this commit: https://github.com/nens/lizard-management-client/pull/474/commits/4ac7bbc18a05fd401b06ae5b167b64dd07a51b98. Reason is the proxy URL is missing a `/` at the beginning for the proxy to work properly.
