### ISSUE TITLE
Add field for attribute "temporal" to raster layers

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#645]
Remco found an issue with raster layers not being registered as temporal if the source is temporal. 

Backend should first make this manageable in the API: nens/lizard-nxt#4837

Then we should add this field to the raster layer form. In the workflow "create new source --> create new layer" the field for the layer should inherit from the source.

**Comment by caspervdw** [comment]
Just checking: does the RasterLayer mgmt screen have an "interval" field? It should not.

**Comment by lexvand** [comment]
@caspervdw No, it doesn't.

**Comment by lexvand** [comment]
@Derryrover Backend is ready on staging.

**Comment by Derryrover** [comment]
WIP
https://github.com/nens/lizard-management-client/pull/666

**Comment by Derryrover** [comment]
merged without review

**Comment by lexvand** [comment]
Works correctly. Great!
