### ISSUE TITLE
Raster alarm - Form

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#646]

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR for raster alarm form: https://github.com/nens/lizard-management-client/pull/691? It's quite a large PR though. Let me know if you need anything.

Thanks!

Kr, Hoan

**Comment by Derryrover** [comment]
Hi Hoan,

I think the code is overall good.
I think this is a form with 4 new difficult fields (relative-start-end, rasterpoint, thresholds, recipients), so therefore a difficult task.
I left 2 comments in the pr concerning the rasterpoint map.

For the recipient and threshold components I would personally prefer if they would look and behave the same as the custom colormap steps component for raster layer. Now they look different and therefore re-using the custom colormap steps code becomes less interesting.
So the dilemma is now if we should go to the trouble of attempting to re-use the code of the colormap here yes or no.
I think a first step could be to talk to Lirry how he feels about making the behaviour+look between the recipient, thresholds and custom colorpmap steps more the same. What do you think?
I made a ticket here:
https://github.com/nens/lizard-management-client/issues/723

Anyway, this is ready to merge after you deal with the comments in the pr.

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Thanks for your comments.

 I fixed the 2 comments that you had in the PR.

For the recipient, threshold and custom colormap steps components, I think it would be nice if we can reuse 1 component for them all. It would then require a more consistent layout/design for all 3 of them. Right now, they are all over place (the recipient uses the dropdown, the threshold uses HTML text + number input, the color map step component uses a color picker). So it makes it difficult to reuse them. I think your suggestion is good, first we need to discuss with Lirry how to make these component's behaviour and look similar to each other first and then continue to refactor them to 1 reusable component. Nice that you already made an issue for it.

Kr, Hoan
