### ISSUE TITLE
Timeseries - Tiles

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#648]
Tiles for timeseries, monitoring networks and locations.

Ready to proceed: Icons are now added to the adobe design

**Comment by Derryrover** [comment]
First draft here:
https://github.com/nens/lizard-management-client/pull/732
Todo: add correct icons

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

I am looking for the icons here:
https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/
Also I seem not to have rights to inspect the code for this adobe file.

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover 

Hi Tom,

I made the design in to dev, so if you open the same link, it should be with downloadable assets.
Just to be sure i will put the icons in this ticket.
https://app.zenhub.com/workspaces/design-5ee3984c6bdf745fdd56cd2e/issues/nens/lizard-management-client/461

**Comment by hoanphungt** [comment]
Icons updated with icons from the design
