### ISSUE TITLE
Timeseries - table

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#649]

**Comment by Derryrover** [comment]
Add new button:
https://github.com/nens/lizard-management-client/pull/741

**Comment by Derryrover** [comment]
merged without review

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I just noticed that the timeseries tables do not have the checkbox and the delete feature. Are there any reason why you don't include them yet? Shall I continue with it (for the accessibility modal)?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Yes please proceed with adding the features from the design.
Reason is that I sometimes do not add certain features right away is most of the time because I want to start with features that are little work but high value first. This way we add value to the business fastest.

**Comment by hoanphungt** [comment]
Ah nice! I thought maybe it's because DELETE is not supported by Backend yet. I will continue with the checkbox.
