### ISSUE TITLE
table search toggle - toggle to which field search applies

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#651]
Sometimes we search on name, sometimes for observation type or location code.
This feature should be configurable in the table.

Locations, for example, also needs it. It needs to search on name or code.
https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/screen/57ac9dda-b7c3-41de-9ada-65f3793ac1b5

**Comment by hoanphungt** [comment]
@lexvand 
I need this feature for the contact list since it can apply filter on `first_name` or `last_name` etc

**Comment by hoanphungt** [comment]
Solved in PR: https://github.com/nens/lizard-management-client/pull/668/

**Comment by hoanphungt** [comment]
Test by going to the contact management page: https://nxt3.staging.lizard.net/management/#/alarms/contacts. Here you can search by either first name or last name.
