### ISSUE TITLE
Timeseries form 

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#653]

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/750/? There is one field left that I have not added to the form which is the monitoring network field. I don't see this field in the API yet so I will leave it out for now and create a separate ticket for it. 

@lexvand I checked the API and found out that the monitoring network is not a field in the API timeseries endpoint but it is included in the design of the timeseries form. Do you have any suggestion?

Kr, Hoan

**Comment by lexvand** [comment]
@hoanphungt You're right, that is not yet supported. Leave it out for now. Adding a timeseries to a network is covered by the bulk action.

I will create an issue for backend to include it at least in the detail view for timeseries.

**Comment by Derryrover** [comment]
@hoanphungt 
@lexvand 

Hi Hoan,
Looks good! ready to merge
2 points of improvement for which i made tickets in this sprint.

I find it a bit hard to find locations. Made this ticket:
https://github.com/nens/lizard-management-client/issues/760

I cannot save my new timeseries "unauthorised to save timeseries for Purmerend". Appearently because I choose a purmerend locaation but do not have the rights.
https://github.com/nens/lizard-management-client/issues/761

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Ah thanks for your review and for making the new tickets. Good observation on the location field.
