### ISSUE TITLE
Timeseries Table- modal for adding timeseries to monitoringsnetwork

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#654]

**Comment by hoanphungt** [comment]
@lexvand @byrman 
Hi Lex and Carsten,

Could you show me how to add timeseries to a monitoring network (for example: https://nxt3.staging.lizard.net/api/v4/monitoringnetworks/c2960f13-a6a2-486b-af52-326251ef710b/)? I couldn't find any documentation on how to add timeseries to monitoring network. Also, it seems that the timeseries subendpoint: https://nxt3.staging.lizard.net/api/v4/monitoringnetworks/c2960f13-a6a2-486b-af52-326251ef710b/timeseries/ doesn't support `PATCH` request.

Kr, Hoan

**Comment by lexvand** [comment]
@hoanphungt 
Adding is done by a POST of a list of timeseries UUID's. Removing is done by a DELETE with a list of timeseries UUID's.

![image](https://user-images.githubusercontent.com/5370809/113318113-677df580-9310-11eb-965c-d2f48cdbb317.png)

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/767?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
@LirryPinter 

Hi Hoan and Lirry,
Code technically good.
But functionally I am missing the following features:

- Ability to see to which monitoring network a timeseries belongs.
- Ability to remove timeseries from monitoring network again.
- Also after monitoringnetwork api calls are done the checkboxes are still checked, not sure if this is by design or bug.

I also noted that this situation is actually according to design as here:
https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/screen/57ffea3d-6252-49ea-b88b-10cbd34b0af7/

and that there is an additional ticket to delete timeseries from monitoring networks here:
https://github.com/nens/lizard-management-client/issues/713
And also plans to have an overview of which timeseries belong to which monitoring networks (although I couldnot find the ticket).

Anyway, with all this information combined I tend to think that:
- This modal on itself can not be considered a 'complete feature'. Should we for example rather also pick up ticket 713 within this ticket?
- The feature itself might be too permissive. Is it really a customer desire to add multiple timeseries to multiple networks at once? Would it not be good enough to add mutiple timeseries to one monitoring network at once? That way we could support this feature in the monitoringnetwork form instead. We could also support the delete and overview in the same gui.

Please let me know if something I say is unclear.

kr Tom

**Comment by LirryPinter** [comment]
@Derryrover @hoanphungt 

Hi tom, on your points:

1 Ability to see to which monitoring network a timeseries belongs.

> This can be multiple ones (since its many to many), and thus not really usable in the listview, if that was wat you are aiming at.

2.  Ability to remove timeseries from monitoring network again.

![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/1c534d97-e52f-407e-96c8-0b11e4df402b)

> This is in the design, as shown above.

**Comment by Derryrover** [comment]
@LirryPinter 
Hi Lirry,

Thanks for the reply.
Then in addition to the "add timeseries to monitoring-network" modal (from this ticket) I would like to propose:

In this modal from the design:
https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/screen/1127dc2f-d1af-4e2f-916e-1681ff912aa1/
could we instead maybe use the multiple select field as can be seen under "contacts" field here?:
https://nxt3.staging.lizard.net/management/#/alarms/groups/1

That we we can:
- add multiple timeseries to that monitoring network
- delete multiple timeseries from that monitoring network
- see which timeseries are in that monitoring network

It is easier for the user (unless I am missing something) and less dev work.

kr Tom

**Comment by lexvand** [comment]
Just discussed it with Tom. The proposed solution is not applicable here, because it wouldn't work for large sets of timeseries.

**Comment by hoanphungt** [comment]
@Derryrover @lexvand 
So I merged the PR. The only improvement that I made is that the checkboxes are unchecked after the action. Workflow is still like in the design.
