### ISSUE TITLE
location form

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#658]
Proceed here:
https://github.com/nens/lizard-management-client/issues/770

**Comment by Derryrover** [comment]
in progress:
https://github.com/nens/lizard-management-client/pull/756

**Comment by Derryrover** [comment]
@LirryPinter 

Hi Lirry,

I am looking at the design for the asset selection here:
https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/screen/a25e4561-7aa3-45ba-aaa0-beb61ec40d3b/

There are some similarities to the map field here. Should they work the same?:
https://nxt3.staging.lizard.net/management/#/alarms/notifications/raster_alarms/new

Would it be possible to work out in some more detail the interactions for this field?
Also backend technical it is possible to have a location with a asset (in object field), but the geometry field is not identical to the geometry of the asset. 
I am afraid we need to cover this situation in the frontend too. Maybe not needed that the user can choose a different geometry from the selected asset, but it is probably needed that if they already differ that the user can somehow see that (and recover from it).

In the meantime I progress as follows:
- In case the geometry of selected asset and location differ, user sees a red text under geometry + a button "remove overwritten geometry".
- User sees on  the map all assets that pass the filter. (since many assets exist, I may need to paginate)

kr Tom

**Comment by Derryrover** [comment]
Problem with backend here:
https://github.com/nens/lizard-nxt/issues/4942

I will investigate if it is because I am unauthorized to use this asset for this organisation.

**Comment by Derryrover** [comment]
@lexvand 
@LirryPinter 
@byrman 

Apart from the json field on location, I also did not add the supplier field.
Supplier seems not exposed in the endpoint

**Comment by Derryrover** [comment]
Proceed here:
https://github.com/nens/lizard-management-client/issues/770

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Do you have time to review?:
https://github.com/nens/lizard-management-client/pull/756

I know it is not finished so we can proceed here:
https://github.com/nens/lizard-management-client/issues/770

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Looks good.

**Comment by Derryrover** [comment]
@hoanphungt 
Hi Hoan,

Good that you further picked up this ticket.
If you still need improvements from me  in the pr please let me know.

kr Tom
