### ISSUE TITLE
Functional and technical improvements management client

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#662]
Issues that were part of Epic #241, but have not been delivered in first development phase.

**Comment by lexvand** [comment]
@Derryrover @hoanphungt I think it is good to close this Epic as the group of first/second iteration improvements of the management client. It doesn't make sense to keep it open forever. We can use the B&O epics as an alternative to plan these kind of issues. 

Do you agree?

**Comment by Derryrover** [comment]
Yes agree. This epic is to broad and abstract to ever end.
