### ISSUE TITLE
Make "raster source" field in Raster Layer management clickable. 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-management-client#663]
Currently a user is unable to select the raster source related to the raster layer. This makes is cumbersome to search for the raster source and e.g. look up how much GB the raster source contains... 

![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/7d63c0b2-d38d-4563-92ba-4f76c2f0aaaf)

Can we the raster source field clickable and make it lead to the raster source page?

@lexvand @LirryPinter 

p.s. this is not needed for coming release and can be picked up at a later stage.

**Comment by lexvand** [comment]
Field needs to be reconsidered all together. It can be just one of the sources used in a Geoblock and I can imagine we would like to make it manageable for "simple" layers.

To be discussed.

**Comment by Derryrover** [comment]
@joeriverheijden 
@lexvand 

I created a new ticket to discuss handling for 1 vs multiple raster-sources:
https://github.com/nens/lizard-management-client/issues/857

In the layer table now already the feature that you can click to the rastersource.
In the form we should have the same feature? I think yes so I moved it in the next sprint.

**Comment by hoanphungt** [comment]
@lexvand @Derryrover 
Similar to the manage timeseries button in the monitoring network form, I made a **View** button in the raster layer form that will open a modal to view the list of connected sources of the layer. Here are some screenshots:

![Screenshot from 2021-06-15 16-53-42](https://user-images.githubusercontent.com/43402556/122075596-8150b400-cdfa-11eb-8595-d7f4341186c2.png)

![Screenshot from 2021-06-15 16-53-59](https://user-images.githubusercontent.com/43402556/122075639-87469500-cdfa-11eb-99e6-ca3c3319f95f.png)

Any comment/suggestion for improvement?

Apart from this modal, when you create a new raster layer form, the raster source field is a single selection field in which you can only connect the layer to one source. Should it be indeed a multiple selection field?
