### ISSUE TITLE
Available alarm message template variables have changed

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#664]
Error; {"status":400,"code":20,"message":"Incomplete request content. #400.20","detail":{"text":["Template variables {'name', 'from', 'from_email'} are not in the available options ('alarm_name', 'trigger_timestamp', 'warning_value', 'warning_level', 'warning_timestamp', 'first_timestamp', 'threshold_timestamp', 'email', 'first_name', 'last_name')."]}}

**Comment by lexvand** [comment]
@caspervdw There are still some message template with var:name, var:from and var:from_email. These variables are not in the TEMPLATE_VARS list for validation. Do you know if these still work and should they be added to the list? Or should they be removed from the options in the management screens and replaced/removed in the existing messages?

I can't find where José got his information from when he implemented the validation.

**Comment by caspervdw** [comment]
Jose got his information from understanding the code that leads to the message templating.

As I can see now, the only variables that actually work are listed correctly in the `TEMPLATE_VARS`. I don't think that var:name, var:from and var:from_email work. Maybe they have worked in a previous implementation.

The name can be constructed from var:first_name and var:last_name. I don't understand why you would need to use var:from and var:from_email . You can just hardcode these things.

**Comment by hoanphungt** [comment]
@lexvand @caspervdw 
I think Casper's explanation makes sense.

**Comment by hoanphungt** [comment]
@lexvand @caspervdw 
For sms alarm template, there is another variable that is no longer supported by backend in api v4: `phone_number` which is the telephone number of the recipient. How important is this variable and shall I remove it from the new template form?

**Comment by lexvand** [comment]
Yes, please remove it. Can't think of a sensible use of that variable. It isn't used in any of the existing templates.

**Comment by hoanphungt** [comment]
Fixed under: https://github.com/nens/lizard-management-client/pull/678 by removing unavailable parameters: `name` `from` `from_email` and `phone_number` from the available parameter list.
