### ISSUE TITLE
Mistake in description of Personal API Key page

### ISSUE THREAD

**Issue by caspervdw** [nens/lizard-management-client#669]
@Derryrover  There is a mistake in the description of the Personal API Key

It states that you should do `<username>:<key>`, while you should do:

username: `__key__`
password: `abcdefg.examplekey`

**Comment by Derryrover** [comment]
@caspervdw 
@LirryPinter 

Hi Casper and Lirry,
I made a fix on staging.
Could you give feedback?
kr Tom
https://nxt3.staging.lizard.net/management/#/personal_api_keys

**Comment by caspervdw** [comment]
Looks good!

**Comment by Derryrover** [comment]
deployed to production

**Comment by hoanphungt** [comment]
@Derryrover 
Just one side note, I noticed that the explain box for the personal API key is now too long and caused a scroll bar for the whole page which is not very nice.

**Comment by Derryrover** [comment]
@hoanphungt 
Hi Hoan,
Good observation.
I updated this ticket to fix it:
https://github.com/nens/lizard-management-client/issues/591
kr Tom
