### ISSUE TITLE
Shared with organisations checkbox does not work correctly

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#674]
Shared with organisations checkbox does not work correctly. For a shared layer, if we uncheck the checkbox and save the layer, the layer is still shared with other organisations. Correctly, all the shared organisations should be removed.

This bug happens with the "Shared with other organisations" field in the WMS layer and Raster layer forms.

**Comment by hoanphungt** [comment]
@lexvand 
I found this bug

**Comment by lexvand** [comment]
Works correctly now.
