### ISSUE TITLE
Simple form of storage usage in scenario and raster management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#679]
We cannot yet show a pie chart as we do not have the total available storage per organisation. Therefore we should just show the current storage based on /api/v4/organisations/{uuid}/usage, as in the old management pages.

Please make the basic setup as in the design, but with a simple textual presentation of the used storage instead of the pie chart.

**Comment by lexvand** [comment]
@Derryrover When do you think we can deliver this temporary feature? Can we make it this week? @joeriverheijden would like to communicate this to the customer. Please add the estimate to the issue.

**Comment by Derryrover** [comment]
WIP:
https://github.com/nens/lizard-management-client/pull/687

done: do this for scenario's
todo: do this for rasters

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I have a question in the PR about the use of selectedOrganisation from local storage and also have a bug related to this one. If I clear the local storage then there will be an error that `cannot read property roles of null` and there is no way to recover from this. 

Apart from this, there is some other minor comments. You can just leave it as is (especially the work-around that you used for the ExplanationSideColunm component).

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
I made quite some changes.
- I fixed the bug with selected organisation localstorage being empty causing crash
- I fixed a related bug in the routing (unauthorized user didnot get redirected on form)
- I improved and factored out some authorization redirect logic

Could you have another look?

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Looks good! You can merge. The 2 bugs are both fixed.

Kr, Hoan
