### ISSUE TITLE
Alarm template in form does not display Enter/newline

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#685]
This problem is already on prod staging and dev.
Low prio, but possibly annoying if you like to make a pretty alarm email.

**Comment by Derryrover** [comment]
@lexvand 
Hi Lex,
Also found this low prio problem.
kr Tom

**Comment by Derryrover** [comment]
merged without review

**Comment by hoanphungt** [comment]
tested and deployed to production
