### ISSUE TITLE
Alarm template add var in middle of text sets cursor to end

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#686]
Low prio. User can manually reset cursor
Existing issue on prod staging and dev. Not newly introduced.

When adding a var in the middle of the text body the cursor moves to the end of the text.
The cursor should stay to right after the just added var.
Probably quite a complicated fix needed for this small problem, so probably skip it for now.

**steps to reproduce**

- Add some text in the email template: "hello mevrouw, dank u wel"
- move cursor to center of this text: "hello mevrouw |, dank u wel"
- add variable "first_name" by clicking on variables on the left
- Desired situation: "hello mevrouw [[firstname]]|, dank u wel" (cursor should be after just added var)
Actual situation: "hello mevrouw [[firstname]], dank u wel|" (cursor is after and of text)

**Comment by Derryrover** [comment]
@lexvand 
Also this one

**Comment by Derryrover** [comment]
pr:
https://github.com/nens/lizard-management-client/pull/848

**Comment by hoanphungt** [comment]
tested and deployed to production
