### ISSUE TITLE
Bulk action set accessibility for scenarios

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#690]
Users want to be able to make scenario results public, especially for use of WMS on related rasters. This comes with some complications as for this purpose both the scenario, related raster layers and related raster sources should be patched.

Therefore it seems logical to make this a bulk action in the scenario management table. What the client should be able to handle is:
1. (Multi) Select scenarios
2. Perform bulk action
3. ~~Lookup related raster layers and sources~~ (handled by backend)
4. ~~Patch the scenario and all related objects~~ (handled by backend)

EDIT:
--
Apply accessibility modal like in timeseries management

**Comment by lexvand** [comment]
@Derryrover Do you think this is technically possible? If so, please make an estimate for it.

**Comment by joeriverheijden** [comment]
I also would like to see this in the design before we move on.

**Comment by joeriverheijden** [comment]
Let Wouter van Esse en Anne Leskens know about this feature @joeriverheijden

**Comment by Derryrover** [comment]
I estimated 3 points.
It is technically feasible, but the technical implementation in the description is maybe not technically desirable.

The options we have:

1. - The datastructure of how scenario's relate to raster sources and raster-layers now becomes entangled in the client. Is this desirable? Is the datamodel battle tested (or possibly immature)? We could work around this by letting the backend keep all the authentication of the related records in sync. **Possibly easiest solution**
Another disadvantage of solving this in the client is that the chance exists that on patch goes wrong and we will need to handle that error somehow to prevent being in limbo state.
2. - Our authorization model seems not optimal for this sort of changes. We previously decided that user cannot edit raster acces_modifier after creation, but now we make a exception. How long will it take before these exceptions become the norm? What does this tell us about our authorization model? Should it maybe not rather be that the authentication of a raster can depend on the authentication of its parent scenario? This way we do not need to keep these in sync. **Possibly best solution, but high risk and lots of work**
3. - We could also show the related raster sources and layers in the scenario form as a related-list and let the user perform bulk actions there. **If it fulfills requirements it may be best solution**
4. - We do as described in the description. We keep the authorization of the related records in sync via seperated api calls in the client. **as far as I can tell worst solution **
