### ISSUE TITLE
Crash during contact deletion

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#695]
Until now happened to me twice. When deleting items (once single and once bulk) the modal opens, but a spinner keeps spinning and the text "Deleting..." shows. You can't confirm or cancel the delete action. No error in console.

![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/c36ad16e-4a84-49d9-98b2-f4c5d5cb9213)

**Comment by hoanphungt** [comment]
This is a bug that happens to all other Tables as well when you do bulk deletion of multiple objects. There are 2 cases that it can happen:

1. When deleting object(s) using the checkbox. After the deletion, now if we want to delete more items, it will always show the delete modal with the spinner
2. When delete object(s) using the checkbox or the 3 dots action and quickly close the modal while deleting. Next time open the modal, it will show the spinner

**Comment by hoanphungt** [comment]
This is a bug that happens to some other Tables as well (including contacts, groups, templates and WMS layers) when you do bulk deletion of multiple objects (or one object) by using the checkbox. The reason is that after the `DELETE` action, it does not set the `busyDeleting` state back to false.
