### ISSUE TITLE
Refactor tiles and routing to functional components + typescript

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#702]
Proceed from this ticket:
https://github.com/nens/lizard-management-client/issues/665

- The items still use classes, but we should use functional components with typescript.
- Also the hardcoded routing should probably be nested like here:

https://reactrouter.com/web/example/nesting

**Comment by Derryrover** [comment]
@lexvand 
@remcogerlich 

Hi,
Made this ticket for the next sprint based on Remco's comments in pr:
https://github.com/nens/lizard-management-client/pull/637
kr Tom

**Comment by Derryrover** [comment]
draft here:
https://github.com/nens/lizard-management-client/pull/724

**Comment by Derryrover** [comment]
Merged before review to avoid conflicts

**Comment by Derryrover** [comment]
Proceed in this ticket:
https://github.com/nens/lizard-management-client/issues/730

**Comment by lexvand** [comment]
On production, so closing this issue.
