### ISSUE TITLE
Management page keeps loading

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-management-client#705]
**Topdesk 2103 0057 Chris Kerklaan**

![image](https://user-images.githubusercontent.com/33685743/110335318-ff473700-8023-11eb-96d5-5c737dfe83de.png)

It seems that if you have insufficient rights, or the organisation has insufficient rights, the management page keeps loading.
It is also not possible to switch to another organisation. 
This is the case for: data management, alarms and personal api keys. 
User management works fine. 

I think this is since the release. I noticed it since today myself. Please fix with priority. 

@joeriverheijden  @lexvand  

Only errors I could find via F12

- Error while trying to use the following icon from the Manifest: https://nens.lizard.net/management/favicon.ico (Resource size is not correct - typo in the Manifest?)

- Uncaught (in promise) TypeError: Cannot read property 'replace' of null

    at main.8b2549b5.chunk.js:1
    at Array.map (<anonymous>)
    at main.8b2549b5.chunk.js:1

**Comment by joeriverheijden** [comment]
@Derryrover @lexvand can you pick this up with a high prio?

**Comment by Derryrover** [comment]
@lisannewapstra 
Hi Lisanne,
I tried to test with this user on staging, but cannot login with new sso somehow (even after resetting pw)
tom.test.user.role
Do you have a user to test on staging maybe?
kr Tom

**Comment by Derryrover** [comment]
Currently on production 0.2.25.

**Comment by Derryrover** [comment]
I have reproduced on dev by proxying to production.
Turns out that one of the organisations on prod does not have a uuid:

{ url: null, uuid: null, name: "Regenradar", roles: [] }
https://demo.lizard.net/api/v4/organisations/?name__icontains=regenradar

**Comment by remcogerlich** [comment]
I deleted the whole organisation now, apologies!

Yesterday already came to the conclusion that this problem existed but I thought it was only for users in that organisation (me). Not so, apparently.

There is an existing rain radar organisation that I will use instead.

**Comment by Derryrover** [comment]
@remcogerlich 
@byrman 
@lexvand 

To evaluate:
How are we supposed to create a new organisation?

**Comment by Derryrover** [comment]
@lisannewapstra 

Solved with data on backend.
No production deploy required

**Comment by Derryrover** [comment]
@remcogerlich 
@byrman 
@lexvand 
@lisannewapstra 
@WolfSchouten 

We investigated the issue.
Seems that creating a new organisation is maybe not foolproof enough.

We can continue in the following ticket:
https://github.com/nens/lizard-nxt/issues/4898
