### ISSUE TITLE
Location form - modal for related asset selection (has become part of the form, not a modal)

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#711]
Object field needs to be filled in with this modal (or section in the form). 

Can be posted/patched with for instance:
`{
    "object": {
        "type": "measuringstation",
        "id": 1236
    }
}`

**Comment by hoanphungt** [comment]
@lexvand 
Do we have somewhere in the lizard documentation a list of all the asset types that can be selected? I can of course go through the API v3 endpoint: https://nxt3.staging.lizard.net/api/v3/ to look for them but not sure if I am gonna miss something.

**Comment by lexvand** [comment]
@hoanphungt 
The list of options supported by the search endpoint that are relevant to location relation:
"culvert"
"groundwaterstation"
"manhole"
"measuringstation" (will probably be used the most)
"monitoringwell"
"overflow"
"pumpstation"
"sluice"
"wastewatertreatmentplant"
"weir"
"parcel" (_is a polygon; how to handle filling in point geometry?_)

Other relevant types that are not supported in search endpoint (we need to have a look at future improvement to also support these):
"filter"
"pump"
"fixeddrainagelevelarea"

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Is it correct that you are already picking this up as well as part of ticket:
https://github.com/nens/lizard-management-client/issues/770 ?

I assigned it to you. You can correct it if I am mistaken.

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover yes, its correct. Thanks!

**Comment by hoanphungt** [comment]
Done as part of PR: https://github.com/nens/lizard-management-client/pull/785/

**Comment by Derryrover** [comment]
reviewed as part of 770
