### ISSUE TITLE
Add edit action to the 3 dots action in all table

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#715]
Coming from Chris Gooch's feedback during the demo for the alarm management page. 

To Do: add an edit option to the action list when click on the 3 dots button. The edit action will bring users to the management page of the selected object (similar to click on the name of the object).

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/725/? Currently, my solution is to add the "EDIT" action directly to the `TableActionButtons` component as we would like to have the "EDIT" action for all the table. What do you think about this approach?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
Looks and works well!
Minor comment in the pr that you may take into consideration.
For the rest all ready to merge.
Good job fixing the bug with the > after the nav
kr Tom
