### ISSUE TITLE
Add alarm contact(s) to alarm group from the alarm contact table 

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#716]
Coming from Chris Gooch's feedback during the demo:

- Add contact to group using the 3 dots button (maybe an action called: "Add to group"?)
- Since we can add a contact to group using the 3 dots button. Is it possible to add multiple contacts to group using the checkbox?

**Comment by hoanphungt** [comment]
@lexvand @LirryPinter 
I created an issue for this based on feedback from Chris during the demo. I think we need a design for the modal or we can reuse the modal that Lirry designed for the timeseries page.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/issues/738?

Kr, Hoan

**Comment by Derryrover** [comment]
Nice ready to merge ;)
