### ISSUE TITLE
Small styling improvements for scenario management

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#718]
Minor comments:

- [x] "Used storage" is too vague: lets do "Used storage (organization name)" -> Split up into 2 rows: Organisation and Used Storage

- [x] This header is too thick because of the raw data column, can we put it in one line so that the header is the same size as all the other ones. 
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/349ace14-8ded-4f3a-9fce-2de06a76a3ce)

- [x] The size column is too narrow, which often causes the unit to drop off and it becomes useless.
![image](https://user-images.githubusercontent.com/5370809/111608121-2a2a4b80-87d9-11eb-8655-c2047eb0e08f.png)

- [ ] This is not a undo icon, but a reset icon. Can we use the undo icon I used in the design?
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/d1a78e6c-b147-4ab1-9e12-f74da02103d5)

**Comment by hoanphungt** [comment]
@LirryPinter 
Hi Lirry,

According to font-awesome library for icons, the icon for undo action is correctly used for undo action as seen here: https://fontawesome.com/v4.7.0/icon/undo. Do you want me to change it to the icon that you used in the design here: https://xd.adobe.com/view/c69b4792-e778-401c-982d-5c57caedf761-93c8/screen/142121a6-d2b9-4d50-8f83-24947f486209/specs/? In this case, could you update the icon with a download link for the asset?

**Comment by lexvand** [comment]
First three bullets are properly fixed. The fourth may be picked up in another issue.
