### ISSUE TITLE
Scroll bar issues in all tables

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#751]
All tables in the management client do not handle scroll bars well. There are two main issues with them:
- Titles in the header are no longer aligned with the column once the vertical scroll bar is introduced.
- Vertical scroll bar disappears when horizontal scroll bar is introduced. You need to scroll all the way to the right to see the vertical scroll bar.

**Comment by lexvand** [comment]
@hoanphungt You mentioned a fix for one of this issues in #727. Can this issue be closed entirely?

**Comment by hoanphungt** [comment]
Only the first bullet is fixed. I have not touched the second one. Anyway, the second one is a bit doubtful to me as users can always scroll using the mouse or the pad without really using the vertical scrollbar.

**Comment by lexvand** [comment]
In that case we consider this issue fixed by #727. I agree that the second bullet is less of a problem for users.
