### ISSUE TITLE
Alarm forms - Change field names

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#753]
I think the current field titles for "relative time" and snoozing are unclear/not "covering the load". Of course we want to give them extensive explanation in the sidebar, but the titles should be clearer.

I propose:
- Change "Use relative data" to "Limit to relative period"
- Snoozing: Change "After breaking threshold" to "Trigger after N times" and "After no further impact" to "Withdraw after N times"

@LirryPinter Do you agree?

**Comment by LirryPinter** [comment]
@lexvand 

Agree
