### ISSUE TITLE
Raster alarm form - Add editable geometry fields (x and y) below map

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#754]
This was discussed with @LirryPinter, but apparently wasn't included in the design. Similar to the [location form in timeseries management](https://xd.adobe.com/view/64bdf742-fee5-4907-a0f1-e9f27ecac3fc-31ee/screen/a25e4561-7aa3-45ba-aaa0-beb61ec40d3b/).

- Fill in the coordinates once the user selected a point or asset.
- Coordinates can be changed. Update map location.

**Comment by hoanphungt** [comment]
@Derryrover 
Since you are working on the Location form which also has this geometry field. I figure it's best if you pick this up along the location form. Do you agree?

**Comment by Derryrover** [comment]
Yes is good. You can skip geometry .

**Comment by hoanphungt** [comment]
@lexvand 
Hi Lex,

I was wondering if a raster alarm can be set on a raster with no spatial bounds? For example, I want to set up an alarm for this Raster: https://nxt3.staging.lizard.net/api/v4/rasters/edef2b11-7b1e-4806-bbd5-d440539efa14/. The spatial bounds of this alarm is null. I can prevent user to create an alarm if the raster doesn't contain spatial bounds information. Is it what we want?

**Comment by lexvand** [comment]
@hoanphungt If there is no spatial bounds it means the layer doesn't contain data (yet). In reality this could happen. I guess it means you can't zoom in to the data extent on the map, right? In that case it would be okay to zoom to the whole world.

Does this answer your question?

**Comment by hoanphungt** [comment]
Yes, in this case, you can select any point on the map since there is no data extent on the map. Currently, the map will automatically zoom to the center of the Netherlands, so this is not my concern.

The current situation is that if no spatial bounds of the raster, you cannot select any point on the map. Hence, you cannot create a new alarm based on this raster as this field is required in the API. I wonder whether this is desirable or not?

**Comment by lexvand** [comment]
So, it is a matter of not being able to validate whether the alarm is set for a valid location. Is this validation done in the frontend or doesn't the API accept a point outside the spatial bounds?

We could handle it by showing a message to the user: "The raster layer should have at least one timestep filled with data to be able to set an alarm for it." That should be acceptable.

**Comment by hoanphungt** [comment]
For now, if a raster does not contain any spatial bounds (probably means user has not updated any data to this raster), it is allowed to select any point on the map.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/pull/787/? I did two things with this PR:

1. Add geometry field (x and y) to the Raster Alarm form
2. Refactor the RasterPointSelection.tsx, GeometryField and MapAssetPointSelection components to reuse them for both the RasterAlarmForm and the LocationForm

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Looks good !
Ready to merge.

kr Tom

**Comment by lexvand** [comment]
Works great! (Almost like a mini game ;))

Useful to users to both set exact locations and retrieve the geometry of an alarm location to use elsewhere (e.g. dashboard configuration).
