### ISSUE TITLE
Import export timeseries

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#759]
Currently exporting timeseries is done is .xlsx format (microsoft excel).

In what format should we do the import?
Should we change the export format?

**Conclusion**:
We (Carsten and me) concluded that multiple options are open, but fastest is probably:

- Leave export in .xlsx excel format
- import in .csv format
- User can transform .xlsx herself from excel to csv with microsoft-excel or libre-office
- Importing in bulk with csv will require multiple csv files (see analysis) so bulk will initially not be supported
- Lateron extend functionality

**Analysis**
Options are .xlsx .csv or .json.
Initially we thought the format of export to be the same as format of import, but users can easily transform from .xlsx to csv and back with excel or libre-office.

1. .xlsx
We already use this for export. For export this seems better then csv, because it supports extra text for metadata and various tabs. Very convenient for user. 
For import it is not so convenient for the programmer, because there will be a lot of  edgecases. Therefore we recommend against using the import as .xlsx. 
There might be parts in Lizard that can already import a standardized .xlsx file, but this would require more investigation. Also a automatically generated .xlsx file is easier to parse then one created by a real user (user might add all sort of info in the sheet that crashes parsing)
2. CSV
For exporting csv seems not sufficient, because it does not support multiple tabs or metadata easily. If user likes to export multiple timeseries that means it is needed to export multiple csv files and possibly extra files for metadata.
For importing single timeseries csv is very good. As long as we do not need to support bulk this is probably easiest
3. JSON
JSON is easy to parsse for import and export, but has a big disadvantage:
There is no standardized json viewer or json transformer for users to view or use the data.
Json viewers do exist, but they are not optimised for table data (at least no industry standard exists).

**Comment by Derryrover** [comment]
@byrman 
@joeriverheijden 
@lexvand 

See above our analysis for import and export timeseries.

**Comment by joeriverheijden** [comment]
Hi Tom, 

Thanks for the very clear analysis. Do you agree that moving forward with the CSV import is best for now (taking in mind that bulk imports are very most likely almost certain wanted by users)? Would a ZIP import containing multiple .csv files be an option for this in the future?

**Comment by Derryrover** [comment]
@joeriverheijden 
@byrman 

Hi Joeri,
Yes I recommend csv for now.
As for bulk imports:

- Yes zipped csv files are our best option from technical perspective.
- It mostly depends if our users are willing to accept multiple csv files as a format. I can imagine users preferring a single excel file with several tabs. The conclusion from a technical point of view is just that importing excel that is manually altered by users can become a possible burden to catch all the edge cases (or write docs about this). 
- Maybe we can make an estimate for a csv solution and in parallel ask customers about import.

kr Tom

kr Tom

**Comment by lexvand** [comment]
Sounds good. Some additional things to consider:
- Column separation: comma vs semicolon
    - I prefer comma as standard, but this conflicts with dutch Excel users
    - Should import support semicolon too?
    - Should an export have an option to use different separators?
- Timezone info
    - Either support datetime with tz or use UTC as standard
- Define a Lizard CSV standard which supports optional headers
    - Include metadata in exports
    - Define timeseries UUID for import mapping
