### ISSUE TITLE
Timeseries form can select locations for which user is not authorissed to create timeseries

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#761]
I cannot save my new timeseries "unauthorised to save timeseries for Purmerend". Appearently because I choose a purmerend location but do not have the rights to do so.

**Comment by lexvand** [comment]
Please use the organisation filter to only look up locations of the organisation that is selected.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I fixed the issue with location authorisation and merged it to the feature branch. Could you check it once again to see if the problem still persists?

Kr, Hoan
