### ISSUE TITLE
Distances between form fields

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#762]
The space between fields is too small, which makes that the fields sometimes are hard to distinguish. See the design for the preferred spacing, especially between sections (e.g. [here](https://xd.adobe.com/view/80bc79b4-fbd2-4d42-9d7f-00b84d2e89c3-d5ef/screen/ce1d67c2-0a01-49c7-9fd2-6255a11f4622))

**Comment by lexvand** [comment]
Very nice. Small change that makes a big difference in the readability of the forms.
