### ISSUE TITLE
Refactor table delete action into a reusable component

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#768]
Currently, the piece of code for the delete action to delete 1 or multiple objects in table is repeated many times. I (Hoan) would like to refactor it to 1 reusable component. 

In addition, the delete action for 1 object and for multiple objects are now separated into 2 different delete functions. These 2 functions can be combined into 1 function only.

**Comment by lexvand** [comment]
Tested deleting different data objects, both in single and multiple deletion mode. All works well.
