### ISSUE TITLE
Code review refactor delete modal

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#771]
Review this ticket:
https://github.com/nens/lizard-management-client/issues/768

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

I have currently little time, but I will review your delete modal refactor later in this ticket.
In the meanwhile you can proceed merge and deploy with the original ticket

kr Tom

**Comment by hoanphungt** [comment]
@Derryrover 
Thanks! Sounds good! I already merged the PR for the other ticket. Here is the link to the PR for your convenience: https://github.com/nens/lizard-management-client/pull/769. There is quite a lot of changes, but the most important ones are:

- The DeleteModal.tsx component
- The deleteActions in Tables that can be used for both single and multiple deletion.

Kr, Hoan

**Comment by Derryrover** [comment]
approved
