### ISSUE TITLE
Edit timeseries alarm form - Add location name to selected timeseries field

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#778]
Currently, when a user goes to the form of an existing timeseries alarm only the timeseries parameter and unit are shown. It would be nice to also indicate which location it belongs to. The timeseries endpoint is already requested and this information is available there. 

It is probable that the user uses the location name in the alarm name, but still it would be good to give the user this information.

I guess it's best to do the same when creating a new alarm, to make it work the same in both use cases.

**Comment by hoanphungt** [comment]
@lexvand 
currently, I format the timeseries input field in this format:

`parameter_code (unit) - location_name`

I attach a screenshot so you can easily imagine. What do you think?
[
![Screenshot from 2021-04-15 14-35-49](https://user-images.githubusercontent.com/43402556/114870127-18e45700-9df8-11eb-87e9-60b371b5ba06.png)
](url)

**Comment by lexvand** [comment]
@hoanphungt Excellent!

**Comment by hoanphungt** [comment]
@lexvand I deployed this one to staging. Tested it and now deployed it to production too. You can test it both on staging and production.
