### ISSUE TITLE
Wrong filtering in timeseries table

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#784]
"&organisation__uuid={organisation_uuid}" should become "&location__organisation__uuid={organisation_uuid}".

**Comment by Derryrover** [comment]
merged without review:
https://github.com/nens/lizard-management-client/pull/789

**Comment by Derryrover** [comment]
@lexvand 
@byrman 

Hi Lex and Carsten,

I solved above issue on the client, but was also wondering:
Is it actually desired that the existence of the 4 authorization fields (organisation, shared with organisation, supplier, acces modifier) is different per table? Would it not be nicer if each table always has all these 4 fields? Now each table has its own 'surprises' so to speak.

kr Tom
