### ISSUE TITLE
Location form - Investigate further the case of location geometry which is available in both the location and asset API

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#792]
@lexvand @Derryrover 
While working on the location form, Tom found out that it it technically possible to create a location with different geometry from its related asset --> it's correct that it is possible to have location with different geometry from its related asset (see explanation by Lex in the comment below)

Previous comment by Tom about this issue: https://github.com/nens/lizard-management-client/issues/658#issuecomment-810007238. 

The current situation of the location form does not cover this edge case yet. We need to investigate further to see how this issue will impact the use of the location form and to find the best solution for this issue. 

**--> currently the related asset and the geometry field of a location are connected with each other. Editing the geometry field will remove the currently selected asset. However, this is not desired. Editing the geometry of the location should not remove the related asset. A location can have a different geometry than geometry of its own related asset. (look at the diagram by Lex in the comment)**

**Comment by hoanphungt** [comment]
@lexvand 
Here is an example of how a location can have different geometry from its related asset: https://nxt3.staging.lizard.net/management/#/data_management/timeseries/locations/083a1c0d-1f3d-421e-9be3-e3d9a75632bb

**Comment by lexvand** [comment]
![image](https://user-images.githubusercontent.com/5370809/115233100-c9fc3180-a117-11eb-8bc4-9a8f4f789aa6.png)

In text: Point on map is based on location.geometry, not on asset.geometry. Location.geometry is updated when asset relation changes or when user changes X,Y fields. Asset relation should not be reset when location.geometry changes.

**Comment by hoanphungt** [comment]
@lexvand Ah interesting how they work! Could you explain a bit further why a location and its related asset can have different geometry? In this case, what is the use of related asset for the location?

**Comment by lexvand** [comment]
@hoanphungt This excellent question has been raised many times over the last couple of years. Hopefully I can clarify it here (once and for all).

Assets and timeseries (and their location) often are managed in different systems at the customer side. They have asset management systems, especially for assets related to the sewerage and surface water systems. Timeseries are often stored in telemetry systems, which have their own registration.

In Lizard we need to be able to handle data from both these types of systems separately AND combined for different use cases. The combination is especially for showing related timeseries for an asset e.g. in the Lizard client. The role of locations and their geometry (being optional) are the result of two important features that Lizard supports:
- Import from Pi-XML: widely used timeseries data format in the Dutch sector, in which location geometry is optional.
- Digitale Delta API: API standard in the Dutch water domain that has a location data model including geometry.

Locations with missing geometry haven't been an issue until we started using them in the Catalogue (map presentation and filtering). We know it may be beneficial to get rid of the location model and use asset information instead, but earlier attempts to figure out how to get there were fruitless. We might do another attempt when looking at possible improvements for the asset data model.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I improved the geometry field and the location form a bit so it reflects how it should work per comment and diagram by Lex. Two main changes are:

- Edit geometry of location (either by clicking on the map or editing the geometry field manually) no longer remove the selected asset
- Remove both X and Y of location will reset geometry of location to null

Link to the PR: https://github.com/nens/lizard-management-client/pull/798. Could you review?

Kr, Hoan

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this issue? The PR for it is here: https://github.com/nens/lizard-management-client/pull/798. 

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Code looks good and conforms to tree above.
I did not test it.
But seems good. Ready to merge!

kr Tom

**Comment by lexvand** [comment]
Works correctly now. Excellent!
