### ISSUE TITLE
Improvements Timeseries table

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#793]
Things that should be improved:
- [x] Filter on UUID doesn't support partial input. Remove the option.
- [x] Add `location__name` and `location__code` filtering --> added `location__name__startswith` and `location__code__startswith` filterings
- [x] Ordering on location doesn't work properly (ordering based on id or last_modified instead of code or name). This will be confusing to users. Remove it if there is no alternative way of correct ordering on location. --> try with `ordering=location__code` or `ordering=location__name` but they both don't work so for now, I remove this ordering from the table.

To be discussed:
- [x] Add code column and option to filter on that? --> linked issue: https://github.com/nens/lizard-management-client/issues/800
- [x] How to handle filtering if `icontains` is not supported? Can we explain to the user that we use `startswith`? --> solved as discussed in comment below

**Comment by hoanphungt** [comment]
@lexvand and @LirryPinter 
- For the filtering, in case if we don't use `icontains` but `startswith` filter option, I think we can display a `*` at the end of the filter option (for example: `Name *`) and below the search box, we show some note, for example: `* only support filtering by first letters`

- The timeseries table is quite clustered already. Do you see a lot of added value by adding the `code` column? If so then we can also do that.

**Comment by hoanphungt** [comment]
@lexvand I created a separate issue: https://github.com/nens/lizard-management-client/issues/800 for the code column in the timeseries table
