### ISSUE TITLE
Improvements Monitoring networks

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#795]
Thing that should be improved:

- [x] Remove UUID filter option
- [x] Ordering on access_modifier doesn't work. Remove option.
- [x] Make accessibility field in form writable

**Comment by hoanphungt** [comment]
@lexvand 
I see that UUID partial input filtering is also not supported here for Monitoring network and they are removed from the other two tables (timeseries and location). Is it more consistent to also remove the UUID filter here?

**Comment by lexvand** [comment]
Yes, please do so.
