### ISSUE TITLE
List uses wrong terminology

### ISSUE THREAD

**Issue by LirryPinter** [nens/lizard-management-client#799]
@lexvand @hoanphungt 

Hi guys,
Found a small "bug"
![image.png](https://images.zenhubusercontent.com/5edf4fb3573d27e45d88f233/d89ff21f-b17c-4164-b470-0638c07ab7db)

The list shows "common" as value, but we called it "Logged in" now!

We should change it

**Comment by hoanphungt** [comment]
Name `Common` coming from the API. I changed it to `Login` now.

Also, for the authorisation field in the form, I changed from `Login required (logged in only)` to `Login (login required)` as I think this is shorter and as clear as the previous one.
