### ISSUE TITLE
Timeseries table - Add code column and option to filter on that

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#800]

**Comment by hoanphungt** [comment]
@lexvand 
I added the code column as in the screenshot below:

![Screenshot from 2021-06-07 15-29-55](https://user-images.githubusercontent.com/43402556/121025350-5dabbf00-c7a5-11eb-96ed-d76b876432e4.png)

What do you think?

**Comment by lexvand** [comment]
@hoanphungt The way the entries are cut off doesn't look great in this example, but given the variation in length of all these fields and the lack of natural breaking points there is not much we can do to improve that right now. Let's go through with it and see what we can improve later on. We know it is in most case important information for the user.
