### ISSUE TITLE
Option for "No further impact" should be included in Template form

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#801]
The `no_further_impact` boolean option in Templates determines whether it is a message to be sent on alarm trigger (= false) or when the alarm is withdrawn (= true).

This option is currently missing in the management form. It is an important feature for Parramatta.

**Comment by joeriverheijden** [comment]
@LirryPinter @lexvand This hasn't been discussed with Chris Gooch yet but should be in there indeed.

**Comment by hoanphungt** [comment]
@lexvand @LirryPinter @joeriverheijden 
I added the **No further impact option** field as in the picture:

![Screenshot from 2021-05-05 14-07-54](https://user-images.githubusercontent.com/43402556/117138523-6d517580-adab-11eb-8af3-76c4b0772725.png)

I also plan to add some explanation text to the template form as it is quite complex. 

Please let me know if you have any idea/comment.

**Comment by hoanphungt** [comment]
@lexvand @joeriverheijden @LirryPinter 
I updated it with the help text as in the screenshot:
![Screenshot from 2021-05-05 14-44-16](https://user-images.githubusercontent.com/43402556/117142856-7b55c500-adb0-11eb-92c0-66b4af722f87.png)
