### ISSUE TITLE
Add UUID field to forms

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#804]
Comment from Joeri: https://github.com/nens/lizard-management-client/issues/803#issue-870944838

> (Prio 2) Currently a user can search for the uuid of a time series, monitoring network or location. However it's not very intuitive where they can find the uuid of the object. Can we add a UUID field to the form for existing objects (that have a uuid). We do something similar for label types, and i think with a little tweak we can apply this to time series, monitoring networks, locations, raster sources, raster layers, wms layers and 3di scenarios

![pic](https://user-images.githubusercontent.com/43402556/116669162-89fe3f80-a99e-11eb-8108-3c74cc75bcd6.png)

Note: This feature can be added before or after the next release on 26th May.

**Comment by lexvand** [comment]
@hoanphungt I planned it in the next sprint for now. We first focus on finishing what we had planned,
