### ISSUE TITLE
Admin wheel in Catalogue leads to old raster link instead of new raster layer link to management 

### ISSUE THREAD

**Issue by joeriverheijden** [nens/lizard-management-client#806]
![image.png](https://images.zenhubusercontent.com/5ee202aafc0246e4d9971397/26d07f7c-6ac4-421e-9228-531559b919dd)

**Comment by joeriverheijden** [comment]
@hoanphungt @lexvand

**Comment by Derryrover** [comment]
A classical example of Linkrot:
https://nl.wikipedia.org/wiki/Linkrot

As handy as links are, they are very sensitive to it.
Modern saas applications might prevent this by saving links to pages centralized (see also "Linkrot vermijden" on the wikipedia page).

**Comment by hoanphungt** [comment]
@Derryrover I fixed the link for now. What you suggested is also nice, I don't quite understand your last point though: 

> Modern saas applications might prevent this by saving links to pages centralized (see also "Linkrot vermijden" on the wikipedia page).

Does it mean we store our links in a database?

**Comment by hoanphungt** [comment]
Fixed and merged to master

**Comment by Derryrover** [comment]
> @Derryrover I fixed the link for now. What you suggested is also nice, I don't quite understand your last point though:
> 
> > Modern saas applications might prevent this by saving links to pages centralized (see also "Linkrot vermijden" on the wikipedia page).
> 
> Does it mean we store our links in a database?

Yes. Links are "content". Content should be data(base) driven. Not hardcoded in the program routines. Pragmatically it can be faster to hardcode links of course, but usually big systems use "content management" for this.
