### ISSUE TITLE
Timeseries management - Fields to be added to forms

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#809]
- [x] Timeseries datasource (retrieve options from /api/v4/datasources/)
- [x] Timeseries extra_metadata (free json field)
- [x] Locations extra_metadata (free json field)

**Comment by lexvand** [comment]
@hoanphungt The backend work for the extra_metadata field for locations is done and on staging (goes to prod on June 2nd). We can pick up this ticket now that the validation of the JSON is in place.

Can you first add an estimate?

**Comment by hoanphungt** [comment]
@lexvand does this mean that only the 3rd checkbox can be done at the moment and that we are gonna leave the 2 first ones out for now?

**Comment by lexvand** [comment]
I think it wouldn't be a problem to implement them all three already. Or do you expect issues in json validation when we release this to production before the backend has released? I changed all current content on both staging and production to valid json, so I think it shouldn't be problematic.

**Comment by hoanphungt** [comment]
@lexvand currently, if you leave the json field empty then it would in the background send an API request with the extra_metadata = {}. I make it this way so this field is not a mandatory field to fill in.

**Comment by hoanphungt** [comment]
@lexvand 
I am missing the explanation text for the added fields:

1. timeseries data source
2. timeseries json field
3. location json field

**Comment by lexvand** [comment]
@hoanphungt I added them to the docs.

**Comment by hoanphungt** [comment]
@lexvand I couldn't find them. Which doc are you referring to? I couldn't find them in the doc Lirry made:
https://docs.google.com/document/d/16eU5w9JL1vSBLpeTH4lAXq3sMylvf_XQbLL0W1cvMAI/edit

**Comment by lexvand** [comment]
Probably because Lirry has to accept my changes.
### Timeseries:
**Datasource**:
Choose the datasource this timeseries originates from
**Extra metadata**:
Free JSON field to add information to this object.

_Example: ‘{“long_term_average”: -1.43}’_

### Locations
**Extra metadata**:
Free JSON field to add information to this object.

_Example: ‘{“Location description”: “Near weir with code KST-43668”}’_
