### ISSUE TITLE
Also show location name in monitoring network modal

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#815]
Relates to: #713.

We currently only show timeseries_name in the list. This is often not enough information for the user. 

Change the format to "{location_name} - {timeseries_name}".

Following issue: This may lead to entries that are too long for the width of the column, especially when location names are very long. We could handle this by applying something like "{location_name[:30]}{...} - {timeseries_name}". Would that be doable?

**Comment by hoanphungt** [comment]
@lexvand 
Currently, when the entry name is too long then it will wrap into multiple lines. This shouldn't be a problem since we already have a scrollbar anyway.

**Comment by lexvand** [comment]
Great!
