### ISSUE TITLE
Roles are no longer available in organisation endpoint

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#820]
From @byrman:

> This has been removed intentionally. I wasn't completely sure whether this would break things though.
> 
> Why has this field been removed?
> It only displayed roles of the currently logged-in user. We wanted a way to show the roles of any user.
> 
> How should it be used now?
> /api/v4/organisations/{uuid}/users/ shows all users of an organisation and their roles.
> 
> https://nxt3.staging.lizard.net/api/v4/users/{pk}/organisations/ shows all organisations a user is in and his roles.

Front-end needs to adapt to this change. User roles are stored in Redux store and used in different places (e.g. forms, organisation switcher, etc).

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

I changed the action to fetchLizardBootstrap and fetchOrganisations a little bit to adapt to the new change by backend for the organisation endpoint. Could you review this PR: https://github.com/nens/lizard-management-client/pull/821?

Thanks in advance!
Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
Thanks for picking this up Hoan.
Looks and works well.
Ready to merge

kr Tom
