### ISSUE TITLE
Repeating requests for fonts and icons

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#826]
The following requests are done at each interaction in the management screens:

![image.png](https://images.zenhubusercontent.com/5ede3192cc5c2c4503d452e7/60cd037f-e0a4-4c19-81d3-6c7a52b566b0)

@hoanphungt Is this something we can/should fix?

**Comment by lexvand** [comment]
@Derryrover Can you check if this is still the case?

**Comment by Derryrover** [comment]
I couldnot reproduce that these network calls are repeated when I click through different tiles and open different forms on nxt3.staging.lizard.net.
It also didnot happen when I created a new raster-layer via the form.

I thus conclude this problem no longer exists
