### ISSUE TITLE
Handle raster source data upload timeout

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#858]
Reported by @WolfSchouten :

> blijkbaar zit er een timeout van 30 seconden op een upload
> na die 30 seconden is het POST request gefaald/timed out, zonder terugkoppeling in de management client

Hoan:

> the exclamation mark appears when there is one (or more) uploads happenning
> once the upload is done, it will disappear
> its true that it doesn't take care of the timeout case yet so in that case, the exclamation mark will be there forever I guess :wink: or until you refresh the page

**Comment by hoanphungt** [comment]
@WolfSchouten 
I deployed the fix to handle timeout case when upload data to raster source to staging. I couldn't reproduce it unfortunately. Could you try and see if you can reproduce it and if it is handled correctly?

**Comment by hoanphungt** [comment]
@lexvand @byrman 
I updated the notification in case of a timeout to `Gateway timeout uploading {filename}. File is too big, please split into smaller files.`

In addition, during the last sprint meeting, we discussed about the raster data upload file with file size larger than 1GB. I remember that files larger than 1GB are restricted from uploading to the lizard server. Could you confirm if this is true? If this is the case, I can also make a client validation for the size of upload files.

**Comment by RonaldWillemsen** [comment]
@Lex if this notification is correct by business the ticket can be closed, since the notification is indeed adjusted.

**Comment by lexvand** [comment]
@hoanphungt @RonaldWillemsen Excellent! Can be closed.
