### ISSUE TITLE
landing page -  first iteration

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#866]
Estimate here:
https://github.com/nens/frontend-tasks/issues/39

First iteration. Without configuration.

**Comment by Derryrover** [comment]
https://github.com/nens/lizard-management-client/pull/868

**Comment by Derryrover** [comment]
@hoanphungt 
@remcogerlich 

Hi Hoan and Remco,
Could you have a look at this pr for the landing page?:
https://github.com/nens/lizard-management-client/pull/868

I know there are a lot of changes.
If you want I can walk you through it.

kr Tom

**Comment by lexvand** [comment]
Tested it on staging. All links work. Some issues related to nginx config, but not directly related to this issue. There is also another issue for styling improvements. This issue therefore can be closed.
