### ISSUE TITLE
Rename dataset on layers to "layer collection" 

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#870]

**Comment by Derryrover** [comment]
Added the task to make actual management screens for "layer collection" to a seperate ticket here:
https://github.com/nens/lizard-management-client/issues/905

**Comment by Derryrover** [comment]
Pr ready but wait for resolve inconsistencies backend?
Also do not gorget to merge master into landing page feature branch later
https://github.com/nens/lizard-management-client/pull/912

**Comment by Derryrover** [comment]
merged without review
released as 0.2.70

**Comment by lexvand** [comment]
After spelling corrections it all looks good on staging.
