### ISSUE TITLE
Some improvements for the dropdown and alarm forms

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#872]
@joeriverheijden @lexvand 
Some requests from Joeri:

- [x] By default, show 40 results in the dropdown instead of 10 (all dropdowns) -> reduce to 20
- [x] In the raster alarm form, the temporal raster field supports to search for raster by both name and UUID. Either change the placeholder to `- Search for name or UUID -` or add to the help text a note: `You can search for raster by name or UUID` --> add to help text a note `You can search for raster layer by name or UUID`
- [x] In the timeseries alarm form, also apply the above solution to the timeseries field --> not neccessary as the timeseries field in the timeseries alarm form already shows all the possible related timeseries of a selected asset.

Places to check for the dropdowns:
- temporal raster field in raster alarm form
- organisation, supplier and shared with other organisation fields in multiple forms (raster layer, raster source, WMS layer ...)
- observation type field in raster layer form and timeseries form

**Comment by hoanphungt** [comment]
@joeriverheijden 
Hi Joeri,

I am thinking again about the number of results to show in the dropdown. My previous proposal is to increase it to 40 results but I had another thought about it. Although, it's good to show more results in the dropdown, it has a disadvantage that the search box is an interactive search input so it sends API requests on every key strokes, so a lot of requests with the `page_size=40` query can slow it down. So I am thinking maybe reduce it to show only 20 results in all of the dropdowns. 

For the raster field and timeseries field in the raster alarm and timeseries alarm forms, it is with the ability to search by UUID so this shouldn't be a problem.

**Comment by joeriverheijden** [comment]
Ok. 20 is good.

**Comment by RonaldWillemsen** [comment]
This has been tested and approved
