### ISSUE TITLE
Bug in uploading data to temporal raster

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#878]
Steps to reproducde:

1, Go to raster source form to create a new raster source
2. Select temporal option
3. Don't touch the interval field and leave it at "0 00:00:00"
4. Upload a .tif file
5. Click on Save

--> Result:

A notification of "Error uploading ***.tif file" is displayed. Open the network tab and check the POST request to the `/data` endpoint, it returns 400 with message: `Unknown interval for temporal store`. This is because the temporal raster doesn't have an interval.

--> Solution: the interval field should be validated so that it cannot be `null` or `0 00:00:00`.

@RonaldWillemsen

**Comment by RonaldWillemsen** [comment]
@hoanphungt I'm not sure if this already is done, but could you link it with the epic?
