### ISSUE TITLE
landing page according to design

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#885]

**Comment by Derryrover** [comment]
Draft pr:
https://github.com/nens/lizard-management-client/pull/887

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,
Could you review this pr?

https://github.com/nens/lizard-management-client/pull/887

I also fixed your recommendations from https://github.com/nens/lizard-management-client/pull/868 in the new branch 887.
Unfortunately I cannot yet test on staging.

kr Tom

**Comment by Derryrover** [comment]
merged the branch.
Put this ticket back to todo for the remaining styling

**Comment by Derryrover** [comment]
Draft pr:
https://github.com/nens/lizard-management-client/pull/917

Todo: make subtitles texts right

**Comment by RonaldWillemsen** [comment]
@Derryrover @lexvand If the internetbrowser is set to 90% or 100% the display of the tiles is as this:
![image.png](https://images.zenhubusercontent.com/60d2e391ade8db8d3edd71ef/85f2fb62-22f5-4a70-9a2e-fcce4cb2726c)

Only by 80% it works as designed. 

Some people have there zoom on 100% and I do not think this looks pretty

**Comment by RonaldWillemsen** [comment]
In the design format the grey lines are exactly the same length as the tiles.
On staging however this is not the case.

![image.png](https://images.zenhubusercontent.com/60d2e391ade8db8d3edd71ef/20d7543d-def6-4cd2-a7f6-ad46877e8017)

**Comment by RonaldWillemsen** [comment]
I also found some odd choices for the drop down menu.
![image.png](https://images.zenhubusercontent.com/60d2e391ade8db8d3edd71ef/a51ac1d6-fc40-4805-8a24-a75ff955adcf)

**Comment by RonaldWillemsen** [comment]
Scaling issue en drop down menu is resolved, looks great
