### ISSUE TITLE
Use react-query for lizard-management-client

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#889]
Instead of using usePaginatedFetch, use react-query to fetch pagniated data.

Tip: use the `enabled` parameter from react-query

**Comment by hoanphungt** [comment]
@Derryrover 
After working with the react-query in the lizard-catalogue, I think for the management client, it's possible to use react-query to replace the usePaginatedFetch hook in multiple places. In this case, it can be quite beneficial.

However, I am not convinced yet to use react-query to replace Redux. Since we already had the Redux store and used them in many places, it is complicated to detach the app from Redux or some parts of the app from Redux. Needs to investigate more on this.

**Comment by Derryrover** [comment]
This one is also part of release 0.2.70 on the landing page branch

**Comment by lexvand** [comment]
Test on staging:
- Probably related issue: #916

**Comment by lexvand** [comment]
Checked different tables and forms and all works well. Relation of #916 with this change was questionable according to Tom.
