### ISSUE TITLE
Overload of task status requests after upload of (multiple) geotiff file(s)

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#890]
When I upload around 30 geotiff files to a raster source in a single action the task list is filled correctly. I checked the network logging and I see a very long list of high frequently repeating requests to get the status of the same task UUID. This may overload the backend or lead to throttling (if that would be in place). Maybe the number of open tasks is playing a role in this, triggering the check mechanism too often. We need to fix this.

**Comment by Derryrover** [comment]
Possibly fixed in https://github.com/nens/lizard-management-client/pull/868

**Comment by Derryrover** [comment]
@hoanphungt 

Thanks
Okey Hoan I merged the pr

**Comment by Derryrover** [comment]
deployed to staging. Ready for test on staging

**Comment by lexvand** [comment]
Tested on staging: No more overload of status requests.
