### ISSUE TITLE
Failed tasks have a `FAILURE` status instead of `FAILED` as previously

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#893]
Previously, for the `task` endpoint, a failed task has a status of `FAILED`. However, checking the lizard-nxt repo, the status of a failed task has been changed to `FAILURE`. This cause the upload queue to not being able to track if a task has been failed.

Code found from the lizard-nxt repo (master):

```
#: Task state is unknown (assumed pending since you know the id).
PENDING = 'PENDING'
#: Task was received by a worker (only used in events).
RECEIVED = 'RECEIVED'
#: Task was started by a worker (:setting:`task_track_started`).
STARTED = 'STARTED'
#: Task succeeded
SUCCESS = 'SUCCESS'
#: Task failed
FAILURE = 'FAILURE'
#: Task was revoked.
REVOKED = 'REVOKED'
#: Task was rejected (only used in events).
REJECTED = 'REJECTED'
#: Task is waiting for retry.
RETRY = 'RETRY'
IGNORED = 'IGNORED'

READY_STATES = frozenset({SUCCESS, FAILURE, REVOKED})
UNREADY_STATES = frozenset({PENDING, RECEIVED, STARTED, REJECTED, RETRY})
EXCEPTION_STATES = frozenset({RETRY, FAILURE, REVOKED})
PROPAGATE_STATES = frozenset({FAILURE, REVOKED})

ALL_STATES = frozenset({
    PENDING, RECEIVED, STARTED, SUCCESS, FAILURE, RETRY, REVOKED,
})
```

**Comment by hoanphungt** [comment]
@lexvand I found this bug with the upload queue

**Comment by lexvand** [comment]
@daanvaningen Do you know why this changed? Do we know forward Celery status? Hoan also ran into a new status `RETRY`. Any possibly breaking issues in API v3 related to this?

**Comment by hoanphungt** [comment]
@lexvand @daanvaningen 
Look at the list of statuses, I guess the following statuses can all be categorized as `FAILED` in the upload queue:

1. `FAILURE`
2. `REVOKED`
3. `REJECTED`
4. `IGNORED`

Currently, it is checking only the `FAILURE` state. Please let me know if you think differently.

**Comment by daanvaningen** [comment]
I have no idea what caused the change. Need to take a look at the changes made.

**Comment by hoanphungt** [comment]
Tested with `hoan-test-raster-source` on staging. The reason for the failure is `Object is locked`.
