### ISSUE TITLE
Investigate remove # from url

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#894]
Investigate remove # from url

Also investigate to fix this comment:
https://github.com/nens/lizard-management-client/pull/887#discussion_r672941719

**Comment by Derryrover** [comment]
merged to feature branch without review:
https://github.com/nens/lizard-management-client/pull/897

**Comment by lexvand** [comment]
@Derryrover What are the risks of breaking anything for this change? We (@RonaldWillemsen) would like to know so we can properly test it.

**Comment by Derryrover** [comment]
Internal links from management page to management page could break (but probably most will work).
External links from other apps to the management page will be broken, but they already were from the landing page change.
So basically this does not add more risk then already introduced I think

**Comment by RonaldWillemsen** [comment]
@lexvand @Derryrover FYI

I've tested all the functions on the Landingpage and I came to the following findings:

Every upload in the tile alarm leads to the same error. 

- Raster Alarms & Time series Alarms
- Groups
- Contacts
- Templates

The same error also applies on Personal Api 

In all cases the user is directed to an empty screen

**Comment by lexvand** [comment]
Works properly after fix #918.
