### ISSUE TITLE
As a customer I want to assign a new raster source to a supplier

### ISSUE THREAD

**Issue by RonaldWillemsen** [nens/lizard-management-client#898]
**Repo steps**

1) Go to https://demo.lizard.net/management/#/
2) Click on Data
3) Click on Rasters
4) Click on Raster Sources
5) Click on '+ new item'
6) Give the raster source a name, upload a tif file and select a supplier
7) Click on save

**Result**
Nothing happens, no indication that it has worked, you are not directed to the page to create a raster layer. The customer is 'softlocked' unless he/she deselect a supplier.

**Expected Result**
I would like to see the same behaviour when you do not select a supplier. (automaticly direct to create a raster layer)

**Comment by RonaldWillemsen** [comment]
@lexvand @joeriverheijden This bug came back to production, I was able to reproduce it. It's op to business if there is need for a hotfix.

It's not a problem to create a new raster source if there isn't a supplier selected, however I do not understand the program good enough to judge the possible impact.

Please verify if this needs to be fixed asap or in upcomming sprint.

**Comment by lexvand** [comment]
@hoanphungt Can you check if this is a frontend or backend issue? The API doesn't accept this input when posting or patching a raster source:
`{...,"supplier": 27,...}`

**Comment by hoanphungt** [comment]
This is a front-end issue. The POST and PATCH requests to create/edit a raster source require the supplier field to be `username` of the supplier, not the `user id` of the supplier. So it should be something like: `supplier: hoan.phung`.

**Comment by RonaldWillemsen** [comment]
@lexvand @joeriverheijden @hoanphungt FYI

I've tested this on production and the fix has been implemented correctly. On staging however this is not yet changed. ''Tom made some configuration to the staging that it's temporary not working if I deploy a new version''

Not sure to close this ticket since it works/fixed on production or keep it in the backlog since staging needs to be equal to production (as much as possible)

**Comment by hoanphungt** [comment]
@RonaldWillemsen 
It can be fixed by merging latest master to Tom's branch for the landing-page and deploy a new pre-release version to staging. I will have a look at this option.

**Comment by hoanphungt** [comment]
The fix is also on staging now
