### ISSUE TITLE
Add UUID and observation type to raster dropdown list in raster alarm form

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#900]
Reported by @joeriverheijden :

Adding UUID and observation type to this list would enhance the ability of the user to distinquish the right raster.

Please make this consistent with https://github.com/nens/lizard-management-client/issues/899

![image](https://user-images.githubusercontent.com/43402556/126640360-354838fd-24b5-46b2-9413-505f692f55dd.png)

**Comment by hoanphungt** [comment]
@lexvand Is it something we still want for the raster dropdown list in the raster alarm form?

**Comment by lexvand** [comment]
I think adding the UUID is good, as you can also filter on it. Not sure if observation type is going to give a whole lot of additional information and it may become quite tight to have three columns. Can you investigate that a bit based on staging data?

**Comment by hoanphungt** [comment]
@lexvand 
I make it work similar to the timeseries field in the timeseries alarm form.

So in the dropdown, it will show the raster in this format:

- `{raster_name} - {observation-type_parameter} ({observation-type_unit})` plus with its `UUID`

In the input placeholder, the selected raster will also be shown with the same format but without the UUID.

It is useful in certain cases, for example, there are 3 Regen raster layers on staging, now it shows:

- Regen
- Regen - Regen (mm)
- Regen - NEERSG (mm)

In addition, there is a bug in the timeseries field of the timeseries alarm form on both staging and production that retrieve the timeseries from the `/api/v4/timeseriesalarms/{uuid}/` endpoint instead of `/api/v4/timeseries/{uuid}/` endpoint. This makes the timeseries field in the timeseries alarm form always `undefined`. I think this must be changed accidentally not so long ago by the front-end because it used to work correctly. I also fixed it in the connected PR.

**Comment by lexvand** [comment]
@hoanphungt I do not really like the way this solution works out. It becomes quite messy and it doesn't make use of the available horizontal space optimally.

![image](https://user-images.githubusercontent.com/5370809/143470055-2bb7aa37-3e71-42f6-b0b4-c0c4ba94a1dc.png)
I propose to leave the observation type out, as it often doesn't add much information. What can be done about the column width so that the name isn't cut off in so many cases?

**Comment by hoanphungt** [comment]
@lexvand 
If you think observation type doesn't add information for the users then we should definitely leave it out to create more white space. For the position of the 2 columns in the dropdown list, I will change the percentage between them. The reason I kept them tight like that because in the Group form, there is another dropdown to add contacts to groups. For this dropdown, the 2nd column requires a lot of space because it is an email address and there is also another phone number colunm behind it. However, I fix it by recognizing the UUID pattern to distinguish between the group form and the alarm form.

Here is a preview:
![Screenshot from 2021-11-26 10-47-43](https://user-images.githubusercontent.com/43402556/143562003-b04457ac-d78a-48dc-8c10-041f0f747926.png)

**Comment by lexvand** [comment]
Clear, looks much better.
