### ISSUE TITLE
Bugs with landing page:

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#901]
Comments uit slack:

Remco Gerlich  3:52 PM
1 puntje gezien: als ik op een link klik, geeft hij zo'n "This page is asking you to confirm that you want to leave — information you’ve entered may not be saved." dialog --> https://github.com/nens/lizard-management-client/issues/904

Wolf Schouten:house_with_garden:  4:18 PM
hoe kan je vanuit de viewer weer terugklikken naar de startpagina? --> https://github.com/nens/lizard-client/issues/1176

hmm, waarom heet de startpagina in mijn browser history 'management'? --> Done, To be deployed to staging.  Veranderd in "Lizard"

From Joeri:
Organisation picker should if possible not be shown in the landing page (only in management page ) -> Done, to be deployed to staging

**Comment by lexvand** [comment]
Test on staging: Bullets 3 and 4 have been fixed.
