### ISSUE TITLE
As a user I want to assign a supplier to a raster layer

### ISSUE THREAD

**Issue by RonaldWillemsen** [nens/lizard-management-client#902]
**Repo steps**

1) Go to https://demo.lizard.net/management/#/
2) Click on Data
3) Click on Rasters
4) Click on Raster Sources
5) Click on '+ new item'
6) Give the raster source a name, upload a tif file and select a supplier
7) Click on save
8) User is redirected to the raster layer
9) Fill in the required info and select a supplier

**Result**
The customer recieves a weird message that its internet connection is not working, he or she can't continue. unless he/she deselect a supplier.

**Expected Result**
I would like to see the same behaviour when you do not select a supplier.

**UPDATE**

Same behaviour also happens with other forms with the supplier field, including:

- Raster source form (already fixed)
- Raster Layer form
- WMS layer form
- Timeseries form

They all accept username instead of user id in the body of the POST/PATCH request.

All are fixed in this ticket.

**Comment by hoanphungt** [comment]
Deployed to production and tested on production. All are working correctly now. 

To do: investigate if this is due to a backend or front-end change.

**Comment by hoanphungt** [comment]
@lexvand 
This issue is due to a front-end change to make the dropdown in the supplier field to become an async dropdown. So no breaking change has been introduced by the backend.

**Comment by lexvand** [comment]
@hoanphungt That's a relief.

**Comment by RonaldWillemsen** [comment]
Nice (y)
