### ISSUE TITLE
Make "are you sure you want to leave page" only popup if needed

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#904]
**Problem**

The popup "are you sure you want to leave this page" now happens to often.
This popup is needed in situations (that I can think of now. There might be more):

- When the user has  opened a form, but hasnot submit it yet
- When the user is busy uploading data

The original tickets regarding this feature I can not find...
https://github.com/nens/lizard-management-client/issues?q=is%3Aissue+leave+
https://github.com/nens/lizard-management-client/issues?q=is%3Aissue+confirm+
maybe try more with better search terms?

The technical difficulty is that the confirm leave feature is not handled by react or redux, but instead by the browser. Maybe we should use a react library to handle keeping this in sync?

A technical problem in relation to GUI is that when the user is uploading data this can be anywhere in the management page.
It is thus required to always keep track of this.

Another technical problem resulting in different styling: We can not really show the confirm-leave if the user moves within the app, so we might need a custom modal. This modal cannot be made when the user leaves the app, so we will have 2 different situations.

** FINAL SOLUTION ** (as proposed by Lirry)
When a user uploads the files, then right after it the upload queue automatically opens.
As long as the files are not all yet uploaded to the server the user cannot close this modal.
The user can close the browser or tab, but during this time (and only during this time) the user will be asked for a confirm leave.
If the user wishes to continue working (and not wait for the files to upload) then she can do so in a new tab.

**Solution**
Handle the confirm leave in the forms themselves. Maybe in the useForm hook? Or maybe make a form component.
Should it also show when the user navigates out of the form? What if the user has not made changes to the form?
Or quich and dirty: do not handle the confirm leave for the form at all?

The confirm leave for uploading data should be handled by the app.js ? It should update anytime the upload data updates. Also, since data upload is not shown in the landing page, it should be shown while navigating from management to landing page?

**Alternative solution**
Not viable on the short term, but I would prefer a situation where the user explicitly calls to "edit" a form (instead of that opening a record assumes a edit.
Also when choosing "edit" the user can then not navigate out of the form, but only either "save" or "discard changes".
For the data upload and download I would prefer this data to stay within the form that was used to do the uploading, instead of to a global queue. This way way can re-use the form logic for any confirm leave, instead of now needing to handle this globally.

**Current situation on prod**
Currently on prod the forms do not have a confirm leave.
Should we add this that forms also have "confirm leave"? Yes, no, or later?

**Problem with fix in pr 907 below**
Since the upload queue is not shown in the landing page. This is extra confusing. In the management page the queue at least gave a red indicator.
Possibly we can:

- move the queue also to the landing page
- indicate via another way that the user should look at the queue. Does the onbeforeclose have a callback?

**Comment by Derryrover** [comment]
Merged without review:
https://github.com/nens/lizard-management-client/pull/907
fixes that the confirm leaves happens correct when the user has upload files in queue

**Comment by Derryrover** [comment]
New pr to show upload queue:
https://github.com/nens/lizard-management-client/pull/908

**Comment by Derryrover** [comment]
@hoanphungt 

Hi Hoan,

Could you review this pr:
https://github.com/nens/lizard-management-client/pull/908
The solution chosen is the "final solution" as in the description

kr Tom

**Comment by lexvand** [comment]
@Derryrover Can this wait for Hoan to return from his holiday or should Remco have a look?

**Comment by Derryrover** [comment]
@remcogerlich 

Hi Remco,

Could you review this pr:
#908
The solution chosen is the "final solution" as in the description

kr Tom

**Comment by lexvand** [comment]
Tested on staging. Solution works well. Opening the Upload queue is nice and it gives proper information on the status and the consequences of closing the tab.
