### ISSUE TITLE
Make layer collection management screen

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#905]
Requirements (by Lex):
- Table columns:
  - Slug (ordering enabled)
  - [**no API support yet**] Accessibility (access_modifier, ordering enabled)
- Table filters:
  - Slug (icontains)
- Table bulk actions:
  - Delete
  - Change rights (set accessibility)
- New item button enabled
- Form fields:
  - Slug (editable)
  - [**no API support yet**] Accessibility (i.e. access_modifier, editable)
  - [**no API support yet**] Supplier (editable)
- Form actions:
  - Delete

**Comment by lexvand** [comment]
I found out the API is not ready yet. Created this issue: nens/lizard-nxt#5213

**Comment by hoanphungt** [comment]
Wait till the feature branch for the lizard landing page is merged to master

**Comment by Derryrover** [comment]
draft pr:
https://github.com/nens/lizard-management-client/pull/935

**Comment by lexvand** [comment]
Staging test: Apart from two small issues (see blocked by dependencies) it al works correctly. Remains open while these issues haven't been fixed.
