### ISSUE TITLE
Sizing and wrapping of tile on homepage + length of header underlines

### ISSUE THREAD

**Issue by Derryrover** [nens/lizard-management-client#920]
The header underline is in the design just as wide as the tiles below it.

We might consider changing some layout to make the styling more perfect.

Anyway we probably need to change quite some css and possibly the react-spring library for this. Not sure.
I placed it out of scope for release 5.9, because I think there are more urgent problems.

**Comment by lexvand** [comment]
This isn't considered to be a real problem, now that the page scales better with different resolutions.
