### ISSUE TITLE
Clicking cancel in personal API key and user form directs to wrong url

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#924]
Similar to #918, but caused by a different action. It seems to only occur in the personal API key and user form, both when editing an existing item and creating a new one.

**Comment by Derryrover** [comment]
Fixed here in landing page branch:
https://github.com/nens/lizard-management-client/pull/868/commits/c828f665c0a7245307648881d18b66db92eb3897

**Comment by lexvand** [comment]
@Derryrover The commit only concerns the API keys. That same happens in the user form.

**Comment by Derryrover** [comment]
@lexvand 
Aangepast
