### ISSUE TITLE
Investigate the use of a json viewer + editor library for viewing and editing geoblock

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#943]
Investigate to use one of the 2 following libraries to view and edit json of a geoblock:

1. https://www.npmjs.com/package/react-json-view
2. https://www.npmjs.com/package/react-json-editor-ajrm

**Comment by hoanphungt** [comment]
Compare 2 libraries:

1. React-JSON-view: 285k downloads/week, 140Kb in size, last publish 6 months ago, 28 contributors and 18.3K users.

2. react-json-editor-ajrm: 28k downloads/week, 350Kb in size, last publish a year ago, 18 contributors, no info on users.

Conclusion: use React-JSON-view library to view and edit JSON source of a geoblock as this is much more popular and better maintained. It is also easier to edit JSON with this library.

**Comment by lexvand** [comment]
Works on staging. Need to gather user feedback to see if it useful this way.
