### ISSUE TITLE
Investigate libraries to visualize json data in blocks with connections

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#944]
From the design: https://xd.adobe.com/view/d2ef027c-c01f-45e7-9bac-c871f4bcdbf4-87bc/screen/f645e286-fe29-420d-891c-cbc017c0a082. 

The goal is to visualize the json data into blocks and connection lines.

Rete.js is the library suggested by Lirry and Casper to display these blocks: https://rete.js.org/#/. This library is compatible with React.

We can decide to use Rete.js or another library to achieve the goal.

**Comment by hoanphungt** [comment]
@caspervdw @daanvaningen 
Hi Casper and Daan,

In order to visualize a geoblock as in the design, I need to have more knowledge on the type of operations it can support and which arguments are allowed for each operation.

For example, as far as I know:

**Available operations for building a geoblock:**
- Clip
- Subtract
- Snap
- Mask Below
- ...

**Argument types for an operation:**
- UUID of a raster source
- a constant
- a block
- ...

Could you help me to complete the list? I am also gonna plan a meeting with you guys and Remco to discuss more about this visualization of a geoblock when I have a simple prototype of how the graph should look like.

Best,
Hoan

**Comment by daanvaningen** [comment]
Hi Hoan,

This is something we still need to implement, the idea is to create a protocol between django-geoblocks and the management client which supplies this information. This is something Casper and I discussed and I sent an email about this 14/7/2021. This is all quite far away though, especially since I will switching teams.

So for now you would indeed need a (static) description of the possibilities. I will see if I can pick this up on monday.

**Comment by hoanphungt** [comment]
@daanvaningen 
Arjan sent me a link to the documentation of dask-geomodeling and there I found the list of operations and parameters supported for Raster blocks. Here is the link: https://dask-geomodeling.readthedocs.io/en/latest/raster.html?highlight=Snap#module-dask_geomodeling.raster.base. Is it also what you are expecting to give to me?

**Comment by daanvaningen** [comment]
Yes! And I was also thinking about a format to supply this in which we want to use when we set this information up dynamically via an API. 

But I will not have time to set this up so I leave this up to you guys :)

**Comment by hoanphungt** [comment]
Decided to go with React-flow-renderer library: https://reactflow.dev/ instead of rete.js. The reasons are:

1. rete.js is not really built for React. Although they do have a plugin for React (rete-react-render-plugin), it is still not compatible with React-hooks and typescript. There is also little documentation on how to make it with React and none with React-hooks.
2. Configuration of a node using rete.js is rather complicated.
3. React-flow-renderer is built specifically for React. The documentation is great. The components are highly reusable and also customisable to suit our own requirements.

A demo can be found at: ...

**Comment by hoanphungt** [comment]
After several demos and technical discussion, we decided to use react-flow to create the visualisation of a geoblock.
