### ISSUE TITLE
Show correct message when trying to create a layer collection with a slug that already exists

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#955]
There is a unique constraint on the slug of a dataset, independent of the organisation it lives in. When you create or change a layer collection with an existing slug, the API returns a 400 error. This is not passed to the user in the snackbar correctly.

API response `{"status":400,"code":20,"message":"Incomplete request content. #400.20","detail":{"slug":["layer collection with this slug already exists."]}}` should result in a message: "This slug is already in use. Try another one."

Nice addition would be that the field in the form is indicated as invalid, but I'm not sure if this corresponds to the mechanic of field validation.

**Comment by hoanphungt** [comment]
@lexvand can I use the `code: 20` in the API response to identify if the slug is already in use? I find it better than checking for the detail message as the message can be changed.

**Comment by lexvand** [comment]
I'm not familiar with the meaning of the `code: 20` and whether it is used for other types of errors, which could lead to incorrect notifications.

Hopefully @byrman can give us insight on this.

**Comment by lexvand** [comment]
@hoanphungt I've looked it up. The code is defined [here](https://github.com/nens/lizard-nxt/blob/1a144191cb042d7589c3e6272bea7e2fb36e1929/lizard_nxt/exceptions.py#L21).

It is not specific for a nonunique slug, so we need to somehow use the text anyway.

**Comment by Derryrover** [comment]
**Review Test**
When I create a layercollection withslug= "123slugexists" the solution seems not to work.

**Comment by hoanphungt** [comment]
@Derryrover 
Ah yes, I forgot to also check when creating a new layer collection. Could you review again?

**Comment by Derryrover** [comment]
@hoanphungt 

Good factored out to handle the error.
Approved !
