### ISSUE TITLE
Missing fields in Geoblocks form

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#961]
The form for Geoblocks should contain the same fields as normal raster layers. Otherwise the configuration is incomplete.

The ones that are currently missing (also in the design) are:
- UUID (read only)
- Layer collections
- Aggregation type
- All related to colormaps
- Rescalable
- Shared with organisations

**Comment by Derryrover** [comment]
@hoanphungt 
Hi Hoan, time to review this one?
kr Tom
