### ISSUE TITLE
Loading of rights takes a while / tiles stay greyed out

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-management-client#963]
I have to wait around 10 seconds to use the management interface.
I am logged in, but the tiles remain greyed out for a while.
When they do appear, the interface works fine. 
![image](https://user-images.githubusercontent.com/33685743/134638794-d93c3a7d-e78f-4496-a1b9-b1a153984786.png)
![image](https://user-images.githubusercontent.com/33685743/134638837-062ce16e-d27f-4721-bd33-d8eef955615a.png)
![image](https://user-images.githubusercontent.com/33685743/134639162-540013ff-50cd-495d-9f29-23a3451ae6ba.png)

I can share my screen it if that helps 

I have many rights, so maybe it is just me. no other reports yet
![image](https://user-images.githubusercontent.com/33685743/134638968-b356b111-6169-48a6-bb60-deb3ec2ccee4.png)

@lexvand

**Comment by lexvand** [comment]
This may be the result of the paginated requests for organisation roles. It shouldn't be a problem for normal users.

I also see that the request for layer collections took more than 3 seconds. I can't really relate that to the other paginated requests. Maybe the server was just slightly less responsive. 

We already have issue nens/lizard-catalogue#283 for research on the effect of paginated requests. Therefore I'm closing this one.
