### ISSUE TITLE
Add text editor next to the JSON editor in the geoblock build modal

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#967]
After the geoblock demo with Remo, we decided that it is useful for user to have a normal text editor to edit the JSON of a geoblock. There should a button to switch between the text editor and the JSON editor with some basic validation for the text editor. The text editor should be shown by default instead of the JSON editor.

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom, 
Could you review?
Kr, Hoan

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/issues/969 for the JSON text editor?

Kr, Hoan

**Comment by lexvand** [comment]
We are going to implement another library for the JSON text/structured editor. I close this issue without testing.
