### ISSUE TITLE
New JSON editor library for the geoblock build

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#983]
Based on this JSON online editor: http://jsoneditoronline.org/

with the following libraries:
https://github.com/josdejong/jsoneditor
https://github.com/vankop/jsoneditor-react

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR: https://github.com/nens/lizard-management-client/issues/989?

I removed the previous JSON editing library (react-json-view). The new one is inspired by http://jsoneditoronline.org/

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
Approve ;)

**Comment by lexvand** [comment]
Looks and works nicely. Code mode is a good default.
