### ISSUE TITLE
Validation regex mail adress needs extending

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-management-client#985]
In the user management, I got an error while adding the mail adress 'zyao@vc.systems'

![image](https://user-images.githubusercontent.com/33685743/139675088-c33754bc-f0c1-490b-97ac-8392b945ddf3.png)

From Wolf/Reinout on Slack
It's TLD (top level domain), .systems

"Misschien dat er in de validator voor het emailadres alleen rekening gehouden wordt met 2 of 3 letterige TLDs zoals .nl en .com? "

 **validator regex**
(/^\w+([+.-]\w+)*@\w+([.-]\w+)*(\.\w{2,3})+$/.test(address))

2,3 is not enough and needs to be at least 7 in this case. 

See also http://emailregex.com/

@lexvand

**Comment by Derryrover** [comment]
Thanks for the report !
I will have a look.

**Comment by Derryrover** [comment]
Okey deployed to staging:
https://github.com/nens/lizard-management-client/releases/tag/0.2.89

**Comment by lexvand** [comment]
Tested it successfully on staging using: "test+something@some.company"
