### ISSUE TITLE
Set up Geoblocks management MVP test protocol

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-management-client#995]
What things should be tested explicitly in the new Geoblocks management interface, both for specifically delivering the MVP and for future regular test runs? What are important edge cases? What validation aspects should be looked at?

@hoanphungt Let's discuss this and make a list.

**Comment by hoanphungt** [comment]
@lexvand 

I made a list of things to discuss below. Be aware that they are coming from my perspective and it might be not subjective enough.

**MVP**

1. Geoblock list
2. Geoblock form
3. Geoblock build modal
- JSON editor that supports copy/paste to create/edit a geoblock
- Visual editor to create/edit a geoblock
- Validation: both client-side and server-side
- Show cost per tile while building

**Client validation**
- Check if geoblock source is not empty and includes both "name" and "graph" tags

Below validations are done only for the visual editor:
- Check if a LizardRasterSource blocks contains a raster input
- Check if graph contains orphan parts and if more than 1 output blocks are found (output block = block without any further connection)
- Check if all input fields are filled in
- Check if at least 1 raster block is included as input in case of an operation that accepts 2 numbers or 2 boolean values (e.g. Add and And operations)
- Check if array input field contains valid JSON input
- Check if you connect a block to a handle that has already been occupied by another block


**Backend Validation**


**Edge cases to check**

- Blocks that contain 2 inputs that can be either a number/boolean or a raster block must contain at least 1 raster block. E.g. Add, Add, Equal, Greater, GreaterEqual, Less, LessEqual, Multiply, NotEqual, Or, Xor, Power, Substract
- Array input: e.g. anchor and coordinates inputs of the Place operation
- Enum input: e.g. statistic input of the Place operation
- Projection input: a string, e.g projection of the Place operation
- Frequency input: a string, e.g. frequency of the Cumulative operation
- timezone input: a string, e.g. timezone of the Cumulative operation

**Testing**

1. Geoblock table:
- Pagination
- New button
- Delete action
- Checkbox
- Sorting feature
- Search feature with name & UUID

2. GeoBlock form:
- Check all the fields
- Delete action
- Save action

3. GeoBlock Build Modal:

- Build a new geoblock from scratch
- Edit an existing geoblock
- Check if the cost of the geoblock is shown and updated correctly during editing
- Use the search function in the right sidebar to search for a block
- Click on one of the block in the right sidebar to learn more about the block
- Add a new raster block to the graph using the right sidebar
- Add a new operation block to the graph using the right sidebar
- Connect raster blocks with operation blocks and connect operation blocks with each other
- Create a new raster block without selecting a raster from the dropdown menu
- Create orphan part(s) in the graph
- Create more than 1 output block
- Leave some input fields empty
- Create an Add operation block and add 2 numbers in the 2 input fields
- Create an And operation block and add 2 boolean values in the 2 input fields
- Create a Place operation block with invalid projection, coordinates and anchor values
- Create a Cummulative operation block with invalid frequency and timezone values
- Switch between the JSON editor and the Visual editor to see if they are in sync with each other
- Swith from the Visual Editor to the JSON Editor while the block is still invalid
- Test the check validation button
- Test the Save button
- Test the Close button and the X

**Comment by lexvand** [comment]
General test protocol can be found here: https://nelenschuurmans.sharepoint.com/:x:/s/Dev-Lizard/EVnBmmPXFZtKttUvU_znDaoB9Q7vGhQtRE9aG2N7_X6Bqg?e=Awi3NV
