### ISSUE TITLE
Show number of operations for geoblocks

### ISSUE THREAD

**Issue by hoanphungt** [nens/lizard-management-client#996]
Number of operations of a geoblock will become a field in the geoblock API and will be shown in the frontend.

To do:

- [x] Figure out where to show this information (in the Table and the Editor)
- [x] Show this info in Table
- [x] Show this info in the Editor --> Visual editor only
- [x] Update this info while editing the geoblock

**Comment by hoanphungt** [comment]
@lexvand 
For the number of operations of a geoblock (the `weight` in backend), I see that the backend is currently calculating it purely as a number of blocks in the graph. Is it correct calcultation? If this is just the number of blocks in the graph, I can easily update it live in the geoblock editor without the need to send an API request for it.

**Comment by lexvand** [comment]
Yes, that was confirmed by Casper. Is there a logical place in the editor GUI to indicate/update the weight while changing a Geoblock?

**Comment by hoanphungt** [comment]
I am currently put it here (see screenshot) next to a refresh button to send an API request with `dry-run` query to update this number (this will also perform validation for the geoblock as only validated geoblock can return a good response to read). However, I can easily recalculate the number of blocks in the graph each time the graph changed, so the number will be updated automatically with every changes. Faster and separated with the function of the `validate` button.
![Screenshot from 2021-11-29 11-14-56](https://user-images.githubusercontent.com/43402556/143850110-6cdb87cc-a67b-4bd9-abe4-6fdfbf3c044f.png)
