### ISSUE TITLE
Personal API keys only available for admin's

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-management-client#998]
Users with any role should be able to open the Personal API key tile and create a new one.
However, it is only avaible for users with admin rights.
For other roles, it is greyed out. 

This must have been changed in the last month or last fews months. 

Found by incident by Lisanne, not reported yet by other users.

**Comment by lexvand** [comment]
Tested on staging. Fixed.

**Comment by hoanphungt** [comment]
on production
