### ISSUE TITLE
User roles not updated automatically - local storage

### ISSUE THREAD

**Issue by lisannewapstra** [nens/lizard-management-client#999]
New user roles are available directly in the API, but not in the management client. 
If you are logged in in the management screen, you have to change organizations or use a new portal to update the rights.
A new login or even a hard refresh does not do the trick.

In the network tab it appears that the roles are stored in the local storage.

**Comment by hoanphungt** [comment]
@lisannewapstra, 
I still don't understand the process to reproduce this bug yet. Would you able to help me or to explain how you did it? Thanks in advance!

**Comment by lisannewapstra** [comment]
Sure, do you need it on staging or production?

**Comment by hoanphungt** [comment]
@lisannewapstra 
Best is on staging, otherwise production is also fine. But you can just desribe the steps that you made and I can try to reproduce it.

**Comment by lisannewapstra** [comment]
OK. Here's how to reproduce:

1. Open https://nxt3.staging.lizard.net/management/users and login with an account with manager rights, e.g. hoan.phung for N&S IT
![image](https://user-images.githubusercontent.com/33685743/142031415-796a65dc-7e53-4b6f-b4d8-8e3717f4dcf9.png)

2. Open a second screen in incognito mode and go to https://nxt3.staging.lizard.net/management/ and login as another user, e.g. username/password stagingdemo/Demo1234
![image](https://user-images.githubusercontent.com/33685743/142031465-f6bad142-4a13-405c-8553-f78220516b00.png)

3. Change the rights for stagingdemo from user to admin or manager in your first screen

![image](https://user-images.githubusercontent.com/33685743/142031515-235c2348-acbb-4ba6-b612-e1c1238e7cf5.png)

4. Open your incognito window, refresh, and see if the rights change
![image](https://user-images.githubusercontent.com/33685743/142031584-7182deda-c24a-4767-9b85-ba8a481fee52.png)

(for me they did not change)

**Comment by hoanphungt** [comment]
That's perfect! I reproduced it succesfully. Thanks!

**Comment by hoanphungt** [comment]
@Derryrover 
Hi Tom,

Could you review this PR https://github.com/nens/lizard-management-client/pull/1001?

Kr, Hoan

**Comment by Derryrover** [comment]
@hoanphungt 
aproved ready to merge

**Comment by lexvand** [comment]
Tested on staging. Roles now update on refresh and are no longer used from local storage.

**Comment by hoanphungt** [comment]
on production
